"""Regenerate ``tests/fixtures/cylinder_stats_golden.json`` (#488 cylinder-scale golden).

An **independent oracle**, not a characterization snapshot: ``calculate_trait_statistics``
computes parameter-free textbook arithmetic (mean/std/quantiles/skewness/kurtosis), so every
recorded value here is independently hand-verifiable from ``cylinder_raw_data.csv`` — same
spirit as ``turface_19_stats_golden.json`` (see tests/fixtures/README.md), just re-derived by
script rather than by hand given the trait count.

Records ALL 846 certified-clean cylinder trait columns (not a representative subset): the
descriptive_stats tool is the one granular tool whose output is inherently per-trait-shaped at
the full, un-reduced cylinder scale (unlike PCA/clustering, which restrict to a much smaller
component/feature set), so under-sampling the golden would leave exactly the scale-specific risk
(a column-ordering bug, the 50-trait summary cap, or a truncated persisted CSV silently losing
rows) unexercised.

Run:  cd bloommcp && uv run --frozen python scripts/gen_stats_golden.py
"""

from __future__ import annotations

import json
from pathlib import Path

import pandas as pd
import sleap_roots_analyze as sra
from sleap_roots_analyze import calculate_trait_statistics, clean_traits_for_analysis

from bloom_mcp.experiment_utils import detect_columns

_FIXTURES = Path(__file__).resolve().parents[1] / "tests" / "fixtures"
_RAW = _FIXTURES / "cylinder_raw_data.csv"
_OUT = _FIXTURES / "cylinder_stats_golden.json"

# Same canonical qc_clean defaults every other cylinder golden in this file family uses.
_CLEANING_PARAMS = {
    "max_zeros_per_trait": 0.5,
    "max_nans_per_trait": 0.2,
    "max_nans_per_sample": 0.0,
    "min_samples_per_trait": 10,
}


def _roles(det: dict) -> dict[str, str]:
    roles = {
        "barcode_col": det["sample_id_col"],
        "genotype_col": det["genotype_col"],
        "replicate_col": det["replicate_col"],
    }
    return {k: v for k, v in roles.items() if v is not None}


def build() -> dict:
    raw = pd.read_csv(_RAW, encoding="utf-8")
    det = detect_columns(raw)
    roles = _roles(det)
    cleaned, kept_trait_cols, _log = clean_traits_for_analysis(
        raw, trait_cols=det["trait_cols"], **roles
    )

    results = calculate_trait_statistics(cleaned, kept_trait_cols)
    stats_per_trait = {
        trait: {
            "count": int(r["count"]),
            "mean": float(r["mean"]),
            "std": float(r["std"]),
            "min": float(r["min"]),
            "max": float(r["max"]),
            "median": float(r["median"]),
            "q25": float(r["q25"]),
            "q75": float(r["q75"]),
            "cv": float(r["cv"]),
            "skewness": float(r["skewness"]),
            "kurtosis": float(r["kurtosis"]),
        }
        for trait, r in results.items()
    }

    return {
        "_comment": (
            "Independently computed (not through the descriptive_stats MCP tool) via "
            "sleap_roots_analyze.calculate_trait_statistics on the canonical-default "
            "qc_clean output of cylinder_raw_data.csv -- the cylinder-scale (846-trait) "
            "counterpart to turface_19_stats_golden.json. Regenerated by "
            "bloommcp/scripts/gen_stats_golden.py from calculate_trait_statistics -- every "
            "literal is machine-derived, never hand-authored."
        ),
        "_raw_source": "bloommcp/tests/fixtures/cylinder_raw_data.csv",
        "_reproduced_by_sleap_roots_analyze_version": sra.__version__,
        "role_columns": {
            "barcode_col": roles.get("barcode_col"),
            "genotype_col": roles.get("genotype_col"),
            "replicate_col": roles.get("replicate_col"),
        },
        "cleaning_params": _CLEANING_PARAMS,
        "cleaned_samples": len(cleaned),
        "kept_trait_columns": list(kept_trait_cols),
        "stats_per_trait": stats_per_trait,
    }


def main() -> None:
    payload = build()
    _OUT.write_text(json.dumps(payload, indent=2, ensure_ascii=False) + "\n")
    print(f"wrote {_OUT.relative_to(_FIXTURES.parents[1])}")
    print(f"cleaned_samples={payload['cleaned_samples']}")
    print(f"kept_trait_columns={len(payload['kept_trait_columns'])}")


if __name__ == "__main__":
    main()
