"""Devendor invariants for `devendor-bloommcp-analysis` (bloommcp-packaging spec).

Landed incrementally across the change's commit plan (see openspec tasks.md), each
xfail(strict=True) flipping to a plain assert the moment its premise genuinely holds
— not all at once at the end:

* C2.3 (parity: every deleted symbol exists upstream) — green from the start; a
  frozen, hand-committed record of the pre-deletion import graph, never a live scan
  of the repointed tree (which would pass vacuously once the imports are gone).
* C2.1 (no shipped module imports vendored analysis) — xfail until C9 (C4/C5/C7/C8
  repoint every consumer but one; C9 deletes the last, correlation_tools.py), then
  flipped there — ahead of C10, which only deletes the now-unimported files.
* C2.2 (vendored files are gone from the tree) — xfail until this commit (C10).
* C5.3/C6.4/C9.2 — positive-absence tests for inspect_data_quality, the retired
  workflow tools, and the retired correlation tools (added as each is removed).
* C11 — the exact tool surface + the tool-name-list drift guard (not yet added here).

All assertions are AST-based (real Import/ImportFrom nodes), not substring matches.
"""

from __future__ import annotations

import ast
import importlib
from pathlib import Path

import pytest

_SRC = Path(__file__).resolve().parents[1] / "src" / "bloom_mcp"

# The nine vendored analysis/plotting modules this change deletes.
_VENDORED_MODULES = (
    "pca",
    "clustering",
    "cluster_visualization",
    "outlier_detection",
    "outlier_visualization",
    "visualization",
    "data_cleanup",
    "data_utils",
    "cross_experiment_correlations",
)


def _vendored_imports_in(py: Path) -> list[str]:
    """Every import in `py` that resolves to a deleted vendored analysis module —
    both `import bloom_mcp.<vendored>[.sub]` / `from bloom_mcp.<vendored>[.sub]
    import Y` (module path names the vendored module) and `from bloom_mcp import
    <vendored>` (the vendored module is imported as a direct child name of the
    `bloom_mcp` package, e.g. the historical `from bloom_mcp import data_cleanup
    as cleanup` / `... import cross_experiment_correlations as corr` style)."""
    tree = ast.parse(py.read_text(encoding="utf-8"), filename=str(py))
    hits: list[str] = []
    for node in ast.walk(tree):
        if isinstance(node, ast.Import):
            for alias in node.names:
                parts = alias.name.split(".")
                if (
                    len(parts) >= 2
                    and parts[0] == "bloom_mcp"
                    and parts[1] in _VENDORED_MODULES
                ):
                    hits.append(f"{py.relative_to(_SRC)}: import {alias.name}")
        elif isinstance(node, ast.ImportFrom):
            if node.level != 0 or not node.module:
                continue
            parts = node.module.split(".")
            if parts[0] != "bloom_mcp":
                continue
            if len(parts) >= 2 and parts[1] in _VENDORED_MODULES:
                hits.append(f"{py.relative_to(_SRC)}: from {node.module} import ...")
            elif len(parts) == 1:
                # from bloom_mcp import <name> — <name> itself may be the vendored
                # module (a package-relative import of a top-level sibling module).
                for alias in node.names:
                    if alias.name in _VENDORED_MODULES:
                        hits.append(
                            f"{py.relative_to(_SRC)}: from bloom_mcp import {alias.name}"
                        )
    return hits


def test_no_shipped_module_imports_vendored_analysis():
    """No module under src/bloom_mcp/** imports a deleted vendored analysis module.

    (bloommcp-packaging: 'No shipped module imports a vendored analysis module'.)

    Genuinely green as of C9 (not waiting for C10): C4/C5/C7/C8 repointed every
    consumer, and C9 deleted the last one (correlation_tools.py). C10 only deletes
    the now-unimported vendored files themselves — test_vendored_analysis_modules_absent
    covers that and stays xfail until then.
    """
    offenders: list[str] = []
    for py in _SRC.rglob("*.py"):
        offenders.extend(_vendored_imports_in(py))
    assert (
        not offenders
    ), "shipped modules still import vendored analysis code:\n" + "\n".join(offenders)


def test_vendored_analysis_modules_absent():
    """The nine vendored modules are gone from src/bloom_mcp/.

    (bloommcp-packaging: 'Deleted vendored files are gone from the tree'.)
    """
    present = [name for name in _VENDORED_MODULES if (_SRC / f"{name}.py").exists()]
    assert not present, f"vendored modules still present: {present}"


# Frozen (hand-committed) record of the pre-deletion import graph: vendored module ->
# the symbol names any shipped module imported from it before the repoint. This is
# NOT regenerated by scanning the (already-repointed) live tree — that would trivially
# pass once the imports are gone. Two symbols are intentionally excluded per the
# proposal (design.md Risks / tasks.md C2.3): `cluster_visualization.create_dendrogram`
# and `outlier_visualization.create_comprehensive_outlier_comparison` are deleted, not
# repointed (their owning plot tools are dropped, not migrated), so nothing imports them
# post-change and they need no upstream home. `cross_experiment_correlations` is excluded
# entirely — its upstream twin has a different contract (design.md D2) and the module is
# deleted together with its sole consumer, not repointed.
_DELETED_VENDORED_SYMBOLS: dict[str, list[str]] = {
    "pca": ["run_pca_and_export_artifacts"],
    "clustering": [
        "calculate_cluster_quality_metrics",
        "cut_dendrogram",
        "perform_gmm_clustering",
        "perform_hierarchical_clustering",
        "perform_kmeans_clustering",
    ],
    "cluster_visualization": [],  # create_dendrogram excluded — see module docstring
    "outlier_detection": [
        "combine_outlier_methods",
        "detect_outliers_isolation_forest",
        "detect_outliers_mahalanobis",
        "detect_outliers_pca",
        "remove_outliers_from_data",
    ],
    "outlier_visualization": [],  # create_comprehensive_outlier_comparison excluded
    "visualization": [
        "create_trait_histograms",
        "create_trait_boxplots_by_genotype",
        "create_correlation_heatmap",
        "create_heritability_plot",
        "create_variance_decomposition_plot",
    ],
    "data_cleanup": ["apply_data_cleanup_filters", "inspect_nan_samples"],
    "data_utils": ["convert_to_json_serializable"],
    # cross_experiment_correlations: intentionally absent — see docstring above.
}


def test_convert_to_json_serializable_importable_from_submodule():
    """`convert_to_json_serializable` is not in `sleap_roots_analyze`'s top-level
    `__all__` — it must be imported via the `.data_utils` submodule path (the
    import-path trap design.md's Risks calls out). C5 repoints qc_clean_tool,
    qc_inspect_tool, and remove_outliers_tool from `bloom_mcp.data_utils` to this
    exact path.
    """
    from sleap_roots_analyze.data_utils import convert_to_json_serializable

    assert callable(convert_to_json_serializable)
    assert convert_to_json_serializable({"a": 1}) == {"a": 1}


def test_deleted_symbols_exist_upstream():
    """Every symbol shipped code imported from a deleted vendored module exists in
    the pinned `sleap_roots_analyze` by the same name (module-level or the documented
    submodule path).

    (bloommcp-packaging: 'Every deleted symbol is proven present upstream'.) This proves
    no functionality is lost by deleting the vendored copy — the guarantee is
    symbol-existence, not behavior parity, for capabilities with no surviving
    through-tool; the surviving consumers additionally carry golden/delegation tests.
    """
    missing: list[str] = []
    for module, symbols in _DELETED_VENDORED_SYMBOLS.items():
        upstream = importlib.import_module(f"sleap_roots_analyze.{module}")
        for symbol in symbols:
            if not hasattr(upstream, symbol):
                missing.append(f"sleap_roots_analyze.{module}.{symbol}")
    assert not missing, "deleted vendored symbols missing upstream:\n" + "\n".join(
        missing
    )


# ── Retired / dropped tool-surface absence (C5.3, C6.4, C9.2, C11.6) ───────────


async def _live_tool_names() -> set[str]:
    from fastmcp import Client

    import bloom_mcp.server as server

    async with Client(server.mcp) as client:
        tools = await client.list_tools()
    return {t.name for t in tools}


def test_inspect_data_quality_absent():
    """inspect_data_quality is removed — qc_inspect covers its use.

    (bloommcp-tool-sections: 'inspect_data_quality is removed'.)
    """
    import asyncio

    import bloom_mcp.tools.qc_tools as qc_tools

    assert not hasattr(qc_tools, "inspect_data_quality")
    assert "inspect_data_quality" not in asyncio.run(_live_tool_names())


_RETIRED_WORKFLOW_TOOLS = (
    "run_qc_workflow",
    "run_outlier_workflow",
    "run_descriptive_stats_workflow",  # note: not "run_stats_workflow"
    "run_dimensionality_reduction_workflow",
    "run_clustering_workflow",
)


def test_retired_workflow_tools_absent_and_package_gone():
    """None of the five run_*_workflow tools is registered, and the whole
    tools/workflows package is gone.

    (bloommcp-tool-sections: 'Retired workflow tools are absent from the surface'.)
    """
    import asyncio

    live = asyncio.run(_live_tool_names())
    present = [name for name in _RETIRED_WORKFLOW_TOOLS if name in live]
    assert not present, f"retired workflow tools still registered: {present}"

    with pytest.raises(ModuleNotFoundError):
        importlib.import_module("bloom_mcp.tools.workflows")


_RETIRED_CORRELATION_TOOLS = (
    "list_experiments",
    "run_cross_experiment_correlations",
    "plot_trait_correlation",
    "plot_correlation_heatmap",
    "plot_genotype_boxplots",
    "check_correlation_power",
    "find_redundant_traits",
    "compare_trait_across_experiments",
)


def test_correlation_tools_absent():
    """None of the 8 correlation tools is registered, and both correlation_tools.py
    and cross_experiment_correlations.py are gone (deleted together, not rewired —
    upstream cross_experiment_analysis has a different contract).

    (bloommcp-experiment-read: 'The deleted cross-experiment local-CSV read path is
    gone'.)
    """
    import asyncio

    live = asyncio.run(_live_tool_names())
    present = [name for name in _RETIRED_CORRELATION_TOOLS if name in live]
    assert not present, f"retired correlation tools still registered: {present}"

    with pytest.raises(ModuleNotFoundError):
        importlib.import_module("bloom_mcp.tools.correlation_tools")
    with pytest.raises(ModuleNotFoundError):
        importlib.import_module("bloom_mcp.cross_experiment_correlations")


# ── C10.2: server boots clean after every vendored module is deleted ──────────

# Every bloom-specific env var the package reads (mirrors test_package_baseline.py) —
# a fresh interpreter must build the app with none of these set.
_BLOOM_ENV_VARS = (
    "SUPABASE_URL",
    "BLOOM_AGENT_KEY",
    "BLOOM_TRAITS_DIR",
    "BLOOM_OUTPUT_DIR",
    "BLOOM_PLOTS_DIR",
    "BLOOM_PLOTS_URL",
)


def test_server_boots_after_devendor():
    """`import bloom_mcp.server` + `build_app()` succeed in a clean env now that
    every vendored analysis module is deleted — catches any dangling import a
    registered module might still have (e.g. a lazy import inside a function body,
    which the AST-based C2.1 scan also catches statically, but this exercises the
    real import machinery end to end).

    (bloommcp-tool-sections: 'No dangling registration or import'.)
    """
    import os
    import subprocess
    import sys

    env = {k: v for k, v in os.environ.items() if k not in _BLOOM_ENV_VARS}
    result = subprocess.run(
        [
            sys.executable,
            "-c",
            "import bloom_mcp.server as s; s.build_app()",
        ],
        env=env,
        capture_output=True,
        text=True,
    )
    assert result.returncode == 0, result.stderr
