"""Scratch fixtures for the fix-prod-sequences-behind tests (bloom#1022).

`setval` survives ROLLBACK, so every fixture table is created inside the test's open
transaction, under a `_seq1022_<uid>_` prefix: rollback drops it and its sequence. The
advance body itself also visits the real `public` tables, so `snapshot` +
`assert_real_sequences_only_moved_forward` check it left them alone (design D8).

The body comes from the migration, or, when SEQ1022_RED_SKETCH=1, from RED_SKETCH: the
issue's rejected GREATEST sketch (design D1), limited to `_seq1022_%` tables so it can
never touch a real sequence. It is never a file under supabase/.
"""

import os
import re
import uuid
from dataclasses import dataclass
from pathlib import Path

from tests.integration.cyl_recipe_helpers import REPO_ROOT, sql_body

MIGRATION_GLOB = "*_advance_lagging_id_sequences.sql"
PREFIX = "_seq1022_"
FOUR_ROLES = "postgres, anon, authenticated, service_role"

ADVANCED = re.compile(
    r"^advanced (?P<seq>\S+) for public\.(?P<table>\S+)\.(?P<col>\S+): "
    r"next value (?P<old>-?\d+) -> (?P<new>-?\d+) \(max = (?P<max>-?\d+)\)$"
)
SUMMARY = re.compile(r"^advance_behind_sequences: (\d+) of (\d+) sequences advanced$")

RED_SKETCH = r"""
DO $sketch$
DECLARE
  r record;
  m bigint;
  lv bigint;
BEGIN
  FOR r IN
    SELECT c.relname AS t, a.attname AS col,
           pg_get_serial_sequence(format('public.%I', c.relname), a.attname) AS q
      FROM pg_class c
      JOIN pg_namespace n ON n.oid = c.relnamespace
      JOIN pg_attribute a ON a.attrelid = c.oid AND a.attnum > 0 AND NOT a.attisdropped
     WHERE n.nspname = 'public' AND c.relkind IN ('r', 'p') AND NOT c.relispartition
       AND c.relname LIKE '\_seq1022\_%'
       AND pg_get_serial_sequence(format('public.%I', c.relname), a.attname) IS NOT NULL
  LOOP
    EXECUTE format('SELECT max(%I) FROM public.%I', r.col, r.t) INTO m;
    IF m IS NOT NULL THEN
      EXECUTE format('SELECT last_value FROM %s', r.q) INTO lv;
      PERFORM setval(r.q, GREATEST(m, lv), true);
    END IF;
  END LOOP;
END
$sketch$;
"""


def migration_path() -> Path:
    matches = sorted((REPO_ROOT / "supabase" / "migrations").glob(MIGRATION_GLOB))
    assert len(matches) == 1, f"expected exactly one migrations/{MIGRATION_GLOB}, found {matches}"
    return matches[0]


def advance_body() -> str:
    if os.environ.get("SEQ1022_RED_SKETCH") == "1":
        return RED_SKETCH
    return sql_body(migration_path())


@dataclass(frozen=True)
class Scratch:
    name: str  # unquoted relname
    col: str  # unquoted column name
    seq: str  # pg_get_serial_sequence text

    @property
    def ident(self) -> str:
        return f'public."{self.name}"'


class Fixtures:
    """Builds scratch tables for one test. `label`s sort in the order given, so a table
    labelled "a" is visited before one labelled "b"."""

    def __init__(self, conn):
        self.conn = conn
        self.uid = uuid.uuid4().hex[:8]
        self.notices: list[str] = []
        conn.add_notice_handler(lambda d: self.notices.append(d.message_primary))

    def name(self, label: str) -> str:
        return f"{PREFIX}{self.uid}_{label}"

    def table(
        self,
        label: str,
        *,
        kind: str = "identity",
        type_: str = "bigint",
        col: str = "id",
        as_admin: bool = False,
    ) -> Scratch:
        """A one-column scratch table, owned by postgres (as in prod) unless as_admin."""
        name = self.name(label)
        coltype = {
            ("identity", "bigint"): "bigint GENERATED BY DEFAULT AS IDENTITY",
            ("identity", "integer"): "integer GENERATED BY DEFAULT AS IDENTITY",
            ("serial", "integer"): "serial",
            ("serial", "bigint"): "bigserial",
        }[(kind, type_)]
        with self.conn.cursor() as cur:
            if not as_admin:
                cur.execute("SET LOCAL ROLE postgres")
            cur.execute(f'CREATE TABLE public."{name}" ("{col}" {coltype})')
            if not as_admin:
                cur.execute("RESET ROLE")
            return Scratch(name, col, serial_sequence(cur, name, col))

    def insert(self, t: Scratch, ids) -> None:
        with self.conn.cursor() as cur:
            for i in ids:
                cur.execute(
                    f'INSERT INTO {t.ident} ("{t.col}") OVERRIDING SYSTEM VALUE VALUES (%s)',
                    (i,),
                )

    def setval(self, t: Scratch, value: int, called: bool) -> None:
        with self.conn.cursor() as cur:
            cur.execute("SELECT setval(%s::regclass, %s, %s)", (t.seq, value, called))

    def alter_seq(self, t: Scratch, clause: str) -> None:
        with self.conn.cursor() as cur:
            cur.execute(f"ALTER SEQUENCE {t.seq} {clause}")

    def state(self, t: Scratch) -> tuple[int, bool]:
        with self.conn.cursor() as cur:
            return seq_state(cur, t.seq)

    def next_default(self, t: Scratch) -> int:
        with self.conn.cursor() as cur:
            cur.execute(f"INSERT INTO {t.ident} DEFAULT VALUES RETURNING \"{t.col}\"")
            return cur.fetchone()[0]

    def run(self) -> None:
        """Run the advance body as postgres (as `supabase db push` does)."""
        with self.conn.cursor() as cur:
            cur.execute("SET LOCAL ROLE postgres")
            cur.execute(advance_body())
            cur.execute("RESET ROLE")

    def run_expecting_failure(self):
        """Run the body inside a savepoint; return the exception it raised. The savepoint
        rollback also undoes the SET LOCAL ROLE."""
        import psycopg

        with self.conn.cursor() as cur:
            cur.execute("SAVEPOINT seq1022")
            try:
                cur.execute("SET LOCAL ROLE postgres")
                cur.execute(advance_body())
            except psycopg.Error as exc:
                cur.execute("ROLLBACK TO SAVEPOINT seq1022")
                return exc
            cur.execute("ROLLBACK TO SAVEPOINT seq1022")
        raise AssertionError("the advance body did not raise")

    def advanced(self) -> list[dict]:
        return [m.groupdict() for n in self.notices if (m := ADVANCED.match(n))]

    def advanced_for(self, t: Scratch) -> list[dict]:
        return [a for a in self.advanced() if a["seq"] == t.seq]

    def summaries(self) -> list[tuple[int, int]]:
        return [(int(m[1]), int(m[2])) for n in self.notices if (m := SUMMARY.match(n))]


def serial_sequence(cur, table: str, col: str) -> str:
    cur.execute(
        "SELECT pg_get_serial_sequence(format('public.%%I', %s::text), %s)",
        (table, col),
    )
    return cur.fetchone()[0]


def seq_state(cur, seq: str) -> tuple[int, bool]:
    cur.execute(f"SELECT last_value, is_called FROM {seq}")
    lv, called = cur.fetchone()
    return int(lv), bool(called)


def sequence_columns(cur, schema: str = "public") -> list[tuple[str, str, str]]:
    """(table, column, sequence) for every sequence-backed column the body visits."""
    cur.execute(
        """
        SELECT c.relname, a.attname,
               pg_get_serial_sequence(format('%%I.%%I', n.nspname, c.relname), a.attname)
          FROM pg_class c
          JOIN pg_namespace n ON n.oid = c.relnamespace
          JOIN pg_attribute a ON a.attrelid = c.oid AND a.attnum > 0 AND NOT a.attisdropped
         WHERE n.nspname = %s AND c.relkind IN ('r', 'p') AND NOT c.relispartition
           AND pg_get_serial_sequence(format('%%I.%%I', n.nspname, c.relname), a.attname)
               IS NOT NULL
         ORDER BY c.relname COLLATE "C", a.attnum
        """,
        (schema,),
    )
    return [tuple(r) for r in cur.fetchall()]


def behind(cur, schema: str = "public") -> set[tuple[str, str]]:
    """(table, column) pairs that are behind, by the spec's definition, computed in Python.
    Only ascending sequences are in scope; descending ones are never behind."""
    out = set()
    for table, col, seq in sequence_columns(cur, schema):
        cur.execute("SELECT seqincrement FROM pg_sequence WHERE seqrelid = %s::regclass", (seq,))
        inc = cur.fetchone()[0]
        if inc < 0:
            continue
        cur.execute(f'SELECT max("{col}") FROM "{schema}"."{table}"')
        mx = cur.fetchone()[0]
        if mx is None:
            continue
        lv, called = seq_state(cur, seq)
        nxt = lv + inc if called else lv
        if mx >= nxt:
            out.add((table, col))
    return out


def snapshot(cur) -> dict[str, tuple[int, bool]]:
    return {seq: seq_state(cur, seq) for _, _, seq in sequence_columns(cur)}


def assert_real_sequences_only_moved_forward(cur, before, after, advanced_seqs) -> None:
    """No real sequence decreased. A real one that changed was either named in an
    `advanced` NOTICE, or looks like a concurrent default insert by a dev worker
    (called, and not past its column's max)."""
    maxes = {seq: (table, col) for table, col, seq in sequence_columns(cur)}
    for seq, old in before.items():
        if PREFIX in seq or seq not in after or after[seq] == old:
            continue
        new = after[seq]
        assert _next(new) >= _next(old), f"{seq} moved backwards: {old} -> {new}"
        if seq in advanced_seqs:
            continue
        table, col = maxes[seq]
        cur.execute(f'SELECT max("{col}") FROM public."{table}"')
        mx = cur.fetchone()[0]
        assert new[1] and mx is not None and new[0] <= mx, (
            f"{seq} changed without an `advanced` NOTICE: {old} -> {new}"
        )


def _next(state: tuple[int, bool]) -> int:
    lv, called = state
    return lv + 1 if called else lv


def stop_if_real_sequences_behind(conn) -> None:
    """Skip (fail under CI) when a real public sequence is already behind.

    Running the body would advance it for good (setval survives rollback), so a dev DB
    with loaded data skips. In CI the database is fresh, so a behind sequence there means
    an earlier test or a migration left one behind: fail rather than skip silently."""
    import pytest

    with conn.cursor() as cur:
        real_behind = behind(cur)
    if not real_behind:
        return
    conn.rollback()
    message = (
        f"real public sequences are behind on this database {sorted(real_behind)}; "
        "running the body here would advance them for good. Apply the advance migration first."
    )
    if os.environ.get("CI"):
        pytest.fail(message)
    pytest.skip(message)


def revoke_four(conn, what: str) -> None:
    """Revoke from postgres AND the three roles it inherits rights from (design D8)."""
    with conn.cursor() as cur:
        cur.execute(f"REVOKE {what} FROM {FOUR_ROLES}")
