"""Pixel-level rendering regression tests for the 5 sleap_roots plotting tools (#713).

`test_viz_tools.py` only ever asserted `.is_file()` on a generated PNG -- a dependency
bump (matplotlib, Pillow, numpy) or a refactor that silently changes color mapping, plot
geometry, or layout would ship with every existing assertion still green. This file closes
that gap by comparing each tool's real output against a committed baseline PNG
(`tests/fixtures/plot_baselines/`, generated by `scripts/gen_plot_snapshots_golden.py`)
via `matplotlib.testing.compare.compare_images` -- matplotlib's own image-comparison
utility (used by its own test suite), available with **no new dependency**: Pillow, which
`compare_images` needs to load PNGs, is a hard transitive floor of both `matplotlib` and
`sleap-roots-analyze`, bloommcp's own main dependencies (not an incidental extra), so it
is not at risk of quietly disappearing from the venv.

Tolerance (`_TOL`): `compare_images` scores a pair of images by RMS pixel difference (0 =
bit-identical). Some noise is expected even for a correct render: FreeType hinting differs
slightly across OS/font-stack combinations. **The baselines here were generated on
macOS**, not on Linux (see `plot_baselines/MANIFEST.json` and design.md Decision 3 — Docker
was unavailable to produce a Linux-rendered baseline matching the `python-audit` CI job's
`ubuntu-latest` runner at authoring time), so this test's *first* real cross-platform
comparison is CI's own run, not this docstring's say-so. `_TOL` was picked from a real,
reproducible measurement, not guessed, and checked against **all 5 baselines**, not just
one (design.md Decision 2 has the full table): uniformly dimming each baseline by
2%/5%/10% (`PIL.ImageEnhance.Brightness`) scores RMS≈5.4-5.7 / ≈11.7-12.5 / ≈23.4-24.9
respectively -- the 5 plots agree within ~0.3 RMS at every level despite very different
pixel content, because a *uniform* shift's RMS is dominated by the large shared
white-background area, not each plot's distinct foreground (contrast the localized-
regression case below, whose RMS genuinely does vary a lot by plot type).
`test_tolerance_catches_a_real_regression` reproduces the 10%-dim case for `histograms`
live rather than hardcoding it. `_TOL = 15` sits above the 5%-dim noise floor (leaving
headroom for legitimate cross-platform hinting noise, which manifests as far subtler pixel
deltas than a uniform intensity shift) and comfortably below the 10% case a real
color-rendering regression would plausibly produce -- consistently across all 5. If CI's
first real cross-platform run shows the genuine hinting-noise RMS is closer to `_TOL` than
expected, that is the authoritative signal to revisit this constant or regenerate the
baselines from a Linux run -- see `scripts/gen_plot_snapshots_golden.py`'s module
docstring.

Known limitation -- localized regressions, measured per plot type (not just guessed to
generalize from one), and against **real element sizes**, not an assumed area fraction (a
PR review on #713 correctly rejected an earlier version of this section for testing
`correlation_matrix` at ~6x a real cell's actual pixel footprint -- see
`test_realistic_single_cell_defect_in_correlation_matrix_is_not_caught` below):

RMS is a whole-image average, so a spatially small miscoloring is diluted across every
unaffected pixel, and *how much* it's diluted depends on both the perturbed area's size
*and* the plot's own layout. Measuring a real plotting element's actual pixel footprint
(via `ax.get_window_extent()` against the live delegate call, not guessed):

- **`correlation_matrix`** (11 real traits -> 55 lower-triangle cells): one cell measures
  ~108.8x108.8px = **~11,836px², ~0.455% of the 1690x1539 baseline** (exact, reproducible
  geometry -- see `test_realistic_single_cell_defect_in_correlation_matrix_is_not_caught`).
  Recoloring exactly that footprint to the *most detectable possible* color (opaque orange
  against `coolwarm`'s blue/white/red range -- a real miscolored cell would typically shift
  color **within** the colormap's range, an even smaller RGB delta) scores **RMS≈5.2** --
  nowhere near `_TOL=15`. **A genuine single-cell defect in `correlation_matrix` is not
  reliably caught by this check, full stop** -- not "might slip through under bad luck",
  a bug producing exactly this failure mode would not be flagged. There is no `_TOL` value
  that both survives legitimate cross-platform noise (~5-12 RMS just from FreeType hinting
  differences, see the Tolerance section above) and clears a ~5 RMS single-cell signal --
  the two are the same order of magnitude. This is not a gap this PR closes; it's a real,
  permanent limit of whole-image RMS comparison applied to a 55-cell grid, tracked as
  **#768** rather than left as an implicit assumption.
- **`heritability_bar`** (same 11 traits -> 11 bars): bar *area* varies with each trait's
  H2 value (near-zero for a low-H2 bar up to the full bar height for H2≈1) -- measured
  directly via each bar patch's `get_window_extent()`: real single-bar areas range
  ~0%-2.89% of the image, median ~2.41%. The `test_tolerance_catches_a_localized_regression`
  case below uses 2% -- within the real, measured range for a plausible single-bar defect
  (not merely an assumed number), and clears `_TOL=15` (RMS≈17.0).
- `histograms`/`boxplots`/`variance_decomposition`: not individually re-measured at their
  real single-element size -- all three carry large enough headroom at a uniform 2% probe
  (RMS≈21.7-22.1, well above `_TOL=15`) that a smaller real element is very likely still
  caught, but this is not asserted by a dedicated test the way the two tools above are (see
  the comment on `_SNAPSHOT_TOOLS`/`_LOCALIZED_REGRESSION_CASES` below).

`test_tolerance_catches_a_localized_regression` proves `_TOL` catches a **several-cells-
worth** regression in `correlation_matrix` (~3% area, ~6-7 real cells) -- a plausible
shape for a bug affecting a contiguous block (e.g. one trait's whole row/column), not a
claim that single-cell defects are covered. These measurements are a snapshot of today's
baselines, not a law -- re-measure after any change to a plot's trait count, color
density, or layout.

Scope: the 5 dedicated plotting tools only (matching `test_viz_tools.py`'s existing
`_TOOLS` list) -- the optional plot keys `pca_analysis`/`umap_analysis`/`clustering` can
also emit (`create_pca_biplot`, `create_cluster_scatter_pca`, etc.) are a deliberate
non-goal here; see proposal.md.
"""

from __future__ import annotations

import shutil
import sys
from pathlib import Path

import matplotlib.pyplot as plt
import pandas as pd
import pytest
from matplotlib.testing.compare import compare_images
from matplotlib.testing.exceptions import ImageComparisonFailure
from PIL import Image, ImageDraw, ImageEnhance
from sleap_roots_analyze.visualization import create_correlation_heatmap

from bloom_mcp import experiment_utils as eu
from bloom_mcp.sections.sleap_roots.analysis import (
    plot_correlation_matrix as plot_correlation_matrix_mod,
    plot_heritability_bar as plot_heritability_bar_mod,
    plot_trait_boxplots as plot_trait_boxplots_mod,
    plot_trait_histograms as plot_trait_histograms_mod,
    plot_variance_decomposition as plot_variance_decomposition_mod,
)

_BASELINES = Path(__file__).resolve().parents[1] / "fixtures" / "plot_baselines"
_EXPERIMENT = "turface_19.csv"
# The same CSV `viz_env` copies into TRAITS_DIR — the converged tools read through the
# ExperimentReader port instead, so their FakeReader has to be seeded from it directly.
_RAW_FIXTURE = Path(__file__).resolve().parents[1] / "fixtures" / "turface_19_final_data.csv"

# The converged 3 name their committed PNG after the tool, not after the experiment, so the
# legacy `<label>_turface_19.png` names in _SNAPSHOT_TOOLS don't apply to them. Baselines
# keep their original names — only the produced file's name differs.
_PRODUCED_NAME_OVERRIDES = {
    "histograms": "trait_histograms.png",
    "boxplots": "trait_boxplots.png",
    "correlation_matrix": "correlation_matrix.png",
}

# Empirically derived, not guessed -- see the module docstring's Tolerance and Known
# limitation sections (design.md Decisions 2 & 3 have the full measurement + fallback
# plan). Changing this number should come with a fresh measurement, not a vibe.
_TOL = 15

# (label, tool module, tool fn name, produced PNG name, baseline PNG name)
#
# All 5 are covered by test_plot_matches_baseline_within_tolerance (the production
# comparison). Only `heritability_bar` and `correlation_matrix` additionally get a
# dedicated localized-regression negative-control case below
# (_LOCALIZED_REGRESSION_CASES) -- `histograms`/`boxplots`/`variance_decomposition`'s
# ~2%-area floor is documented in the module docstring's "Known limitation" section but
# NOT independently test-enforced; nothing in CI would catch a future baseline
# regeneration quietly eroding their margin against `_TOL=15`.
_SNAPSHOT_TOOLS = [
    (
        "histograms",
        plot_trait_histograms_mod,
        "plot_trait_histograms",
        "histograms_turface_19.png",
        "histograms_turface_19_baseline.png",
    ),
    (
        "boxplots",
        plot_trait_boxplots_mod,
        "plot_trait_boxplots",
        "boxplots_turface_19.png",
        "boxplots_turface_19_baseline.png",
    ),
    (
        "correlation_matrix",
        plot_correlation_matrix_mod,
        "plot_correlation_matrix",
        "correlation_matrix_turface_19.png",
        "correlation_matrix_turface_19_baseline.png",
    ),
    (
        "heritability_bar",
        plot_heritability_bar_mod,
        "plot_heritability_bar",
        "heritability_turface_19.png",
        "heritability_turface_19_baseline.png",
    ),
    (
        "variance_decomposition",
        plot_variance_decomposition_mod,
        "plot_variance_decomposition",
        "variance_decomposition_turface_19.png",
        "variance_decomposition_turface_19_baseline.png",
    ),
]
_IDS = [label for label, *_ in _SNAPSHOT_TOOLS]

# The 3 tools #466 converged onto `@as_mcp_tool` no longer match the legacy calling
# convention the other 2 still use, so this file can no longer drive all 5 the same way.
# They take a Pydantic params model (not a bare experiment string), return a result model
# (not a "Plot saved: ..." string), and persist their PNG into a ResultStore version dir
# (not PLOTS_DIR). Pixel coverage is preserved for them rather than dropped: the render
# itself is unchanged, and these baselines still match within `_TOL` (verified against the
# committed baselines when this adaptation landed, #466 review round 7).
_CONVERGED = {"histograms", "boxplots", "correlation_matrix"}


def _render_to_dir(label, module, fn_name, viz_env):
    """Run one plotting tool and return the directory its PNG(s) landed in.

    Legacy tools write straight into ``PLOTS_DIR`` (``viz_env``). The converged 3 write
    into a ``ResultStore`` staging dir that ``commit`` deletes on success, so their bytes
    are copied out inside a ``commit`` spy — the last point at which the committed file
    still exists on disk. Capturing at commit (rather than spying on ``savefig``) means the
    bytes compared are exactly the bytes that were committed, not an intermediate render.
    """
    fn = getattr(module, fn_name)
    if label not in _CONVERGED:
        result = fn(_EXPERIMENT)
        assert "Plot saved:" in result
        return viz_env

    import pandas as pd
    from bloom_mcp.data_access import FakeReader, SupabaseReader
    from bloom_mcp.result_store import FakeResultStore, SupabaseResultStore
    from bloom_mcp.tools import _ports

    captured = viz_env / f"_committed_{label}"
    captured.mkdir(parents=True, exist_ok=True)

    reader = FakeReader()
    reader.add_experiment(_EXPERIMENT, pd.read_csv(_RAW_FIXTURE))
    store = FakeResultStore()
    real_commit = store.commit

    def _spy_commit(run, outputs):
        for name in outputs:
            shutil.copy(run.staging_dir / name, captured / name)
        return real_commit(run, outputs)

    store.commit = _spy_commit
    _ports.configure(reader=reader, store=store)
    try:
        fn(experiment=_EXPERIMENT)
    finally:
        _ports.configure(reader=SupabaseReader(), store=SupabaseResultStore())
    return captured


@pytest.mark.parametrize(
    "_label,module,fn_name,produced_name,baseline_name", _SNAPSHOT_TOOLS, ids=_IDS
)
def test_plot_matches_baseline_within_tolerance(
    _label, module, fn_name, produced_name, baseline_name, viz_env
):
    produced_dir = _render_to_dir(_label, module, fn_name, viz_env)

    actual = produced_dir / _PRODUCED_NAME_OVERRIDES.get(_label, produced_name)
    baseline = _BASELINES / baseline_name
    assert actual.is_file()
    assert baseline.is_file(), (
        f"missing baseline {baseline} -- run "
        "`uv run --frozen --extra test python scripts/gen_plot_snapshots_golden.py --yes` to create it"
    )

    _compare_or_fail(baseline, actual)


# Appended to EVERY failure this helper raises, not just the exception path -- a PR review
# on #713 found the original version only attached this pointer inside the `except` block,
# which `compare_images` never actually reaches for the ordinary "RMS exceeded `_TOL`" case
# (that's a plain returned string, not a raised exception -- see the two paths in
# `_compare_or_fail` below). The pointer was therefore dead code for the exact scenario
# `_TOL` itself is calibrated against.
_CROSS_PLATFORM_POINTER = (
    "\nIf this is an RMS-over-tolerance message OR a dimension-mismatch exception, it may "
    "be legitimate cross-platform FreeType-hinting / bbox_inches='tight' canvas-size noise "
    "rather than a content regression -- see design.md Decision 3 before regenerating "
    "baselines or changing _TOL."
)


def _compare_or_fail(baseline: Path, actual: Path) -> None:
    """Compare and fail with `_CROSS_PLATFORM_POINTER` attached either way `compare_images`
    can fail: it raises `ImageComparisonFailure` for a pixel-dimension mismatch (e.g. if
    `bbox_inches="tight"`, `_viz_shared.save_plot`'s save call, produced a different canvas
    size on this platform than the baseline's), but returns a plain failure *string* (no
    exception) for an ordinary RMS-over-`_TOL` mismatch -- both need the same pointer, not
    just the exception path. `OSError` also covers `PIL.UnidentifiedImageError` (a
    committed baseline PNG that's corrupted/truncated) -- low-likelihood since baselines are
    ordinary committed git binaries, but a real failure mode `_load_image` can hit, unlike a
    speculative `ValueError` no path in `matplotlib.testing.compare` actually raises.
    """
    try:
        diff = compare_images(str(baseline), str(actual), tol=_TOL)
    except (ImageComparisonFailure, OSError) as exc:
        pytest.fail(f"{exc}{_CROSS_PLATFORM_POINTER}")
    if diff is not None:
        pytest.fail(f"{diff}{_CROSS_PLATFORM_POINTER}")


def test_tolerance_catches_a_real_regression(tmp_path):
    """`_TOL` must not be so loose it rubber-stamps a genuine rendering regression.

    Dims one real baseline by 10% (`PIL.ImageEnhance.Brightness(0.9)`) -- the same
    perturbation the module docstring cites as scoring RMS≈24.4, reproduced live here
    (not hardcoded) so this stays a real assertion against `compare_images`, not a pinned
    magic number. A uniform intensity shift is a stand-in for "a rendering regression
    large enough to matter", not a literal simulation of any specific known bug.
    """
    baseline = _BASELINES / "histograms_turface_19_baseline.png"
    dimmed = ImageEnhance.Brightness(Image.open(baseline)).enhance(0.9)
    perturbed = tmp_path / "dimmed.png"
    dimmed.save(perturbed)

    diff = compare_images(str(baseline), str(perturbed), tol=_TOL)
    assert diff is not None, (
        f"a 10%-dimmed baseline compared equal to itself -- _TOL={_TOL} is too loose "
        "to catch a real regression"
    )


_LOCALIZED_REGRESSION_CASES = [
    # (baseline filename, area fraction). heritability_bar's 2% is within the real,
    # measured single-bar-area range (~0%-2.89%, median ~2.41% -- see module docstring).
    # correlation_matrix's 3% is deliberately NOT a single real cell (one cell measures
    # ~0.455%, see test_realistic_single_cell_defect_in_correlation_matrix_is_not_caught
    # below, which pins that a real single-cell defect is NOT caught) -- 3% represents
    # ~6-7 real cells' worth of area, a plausible "whole row/column wrong" bug shape, with
    # real margin above the ~2.5% RMS-crossing point measured for that size.
    ("heritability_turface_19_baseline.png", 0.02),
    ("correlation_matrix_turface_19_baseline.png", 0.03),
]


@pytest.mark.parametrize(
    "baseline_name,area_fraction",
    _LOCALIZED_REGRESSION_CASES,
    ids=[name.split("_turface")[0] for name, _ in _LOCALIZED_REGRESSION_CASES],
)
def test_tolerance_catches_a_localized_regression(tmp_path, baseline_name, area_fraction):
    """A *global* dim (above) isn't the only regression shape worth proving `_TOL` catches
    -- a spatially small miscoloring only touches part of the image, and RMS is a
    whole-image average (see module docstring's "Known limitation"). Proves `_TOL` catches
    a **several-elements-worth** localized regression on both `heritability_bar` (a
    realistically-sized single bar) and `correlation_matrix` (several cells, NOT a single
    cell -- see the dedicated single-cell test below for that honest negative result).
    """
    baseline = _BASELINES / baseline_name
    img = Image.open(baseline).convert("RGB")
    w, h = img.size
    perturbed_img = img.copy()
    side = int((w * h * area_fraction) ** 0.5)
    x0, y0 = w // 3, h // 3
    ImageDraw.Draw(perturbed_img).rectangle(
        [x0, y0, x0 + side, y0 + side], fill=(255, 165, 0)
    )
    perturbed = tmp_path / "localized.png"
    perturbed_img.save(perturbed)

    diff = compare_images(str(baseline), str(perturbed), tol=_TOL)
    assert diff is not None, (
        f"a ~{area_fraction * 100:.0f}%-area recolored {baseline_name} compared equal to "
        f"itself -- _TOL={_TOL} is too loose to catch even this deliberately-sized "
        "localized regression"
    )


# Exact geometry for turface_19's real correlation_matrix render, measured directly against
# the live delegate call via ax.get_window_extent() (not eyeballed): create_correlation_heatmap
# renders turface_19's 11 real trait columns into an 11x11 grid (mask hides the upper
# triangle + diagonal, leaving 55 real cells) inside a square axes measuring
# 1196.7x1196.7px at the actual save dpi=150. One cell is therefore
# 1196.7/11 = ~108.8px per side = ~11,836px^2 of the baseline's 1690x1539 = 2,600,910px^2
# total -- ~0.455%. Re-derive this (same method: render, `fig.canvas.draw()`,
# `ax.get_window_extent(fig.canvas.get_renderer())`) if the fixture's trait count or the
# delegate's figsize/dpi ever changes; do not just bump the fraction.
_REAL_CORRELATION_CELL_AREA_FRACTION = 11836 / (1690 * 1539)


def _measure_live_correlation_cell_area_fraction() -> float:
    """Independently re-derive `_REAL_CORRELATION_CELL_AREA_FRACTION` by actually rendering
    the live delegate call and measuring its geometry, rather than trusting the hardcoded
    comment above to stay accurate forever -- a third review correctly pointed out that a
    comment telling a human to re-derive a number by hand is exactly the kind of thing that
    silently goes stale (it's how the original 3%-vs-0.455% error happened in the first
    place). Mirrors `scripts/gen_plot_snapshots_golden.py`'s own real-fixture setup, not a
    synthetic stand-in.
    """
    raw = Path(__file__).resolve().parents[1] / "fixtures" / "turface_19_final_data.csv"
    df = pd.read_csv(raw, encoding="utf-8")
    trait_cols = eu.detect_columns(df)["trait_cols"]
    n = len(trait_cols)

    fig = create_correlation_heatmap(df, trait_cols)
    try:
        ax = fig.axes[0]
        fig.canvas.draw()
        ax_bbox = ax.get_window_extent(fig.canvas.get_renderer())
        save_dpi = 150  # matches _viz_shared.save_plot's dpi
        scale = save_dpi / fig.dpi
        cell_area_px = (ax_bbox.width * scale / n) * (ax_bbox.height * scale / n)
    finally:
        plt.close(fig)

    baseline = _BASELINES / "correlation_matrix_turface_19_baseline.png"
    w, h = Image.open(baseline).size
    return cell_area_px / (w * h)


def test_real_correlation_cell_area_fraction_matches_measured_geometry():
    """`_REAL_CORRELATION_CELL_AREA_FRACTION` -- the basis for both the localized-regression
    test sizing and the single-cell pinning test below -- must not silently drift from
    reality. If `turface_19`'s trait count or `create_correlation_heatmap`'s figsize/dpi ever
    changes, this fails loudly (telling a developer to re-derive the constant and update the
    docs/comments that cite it) instead of leaving a stale number nobody notices.
    """
    live = _measure_live_correlation_cell_area_fraction()
    assert live == pytest.approx(_REAL_CORRELATION_CELL_AREA_FRACTION, rel=0.05), (
        f"live-measured cell area fraction ({live:.5f}) has drifted from the hardcoded "
        f"_REAL_CORRELATION_CELL_AREA_FRACTION ({_REAL_CORRELATION_CELL_AREA_FRACTION:.5f}) "
        "-- re-derive the constant (see its comment) and update design.md/#768 if the new "
        "value changes the single-cell-detection conclusion"
    )


def test_realistic_single_cell_defect_in_correlation_matrix_is_not_caught(tmp_path):
    """Honest negative result, not a gap papered over: a real single-cell defect in
    `correlation_matrix` -- the tool where a silent wrong value is most scientifically
    consequential -- is measurably NOT caught by `_TOL=15`. A PR review on #713 correctly
    rejected an earlier version of this suite that tested at ~6x a real cell's actual size
    and called the gap "resolved"; it wasn't. This test locks in the actual, current
    behavior instead: it should fail loudly (telling us something changed, for better or
    worse) if a future baseline regeneration or `_TOL` change ever alters this outcome --
    it must NOT be treated as passing proof the gap is fine to ignore.

    Uses opaque orange -- the same maximally-detectable color the other tests in this file
    use -- which is *more* detectable than a realistic bug: a real miscolored cell under
    `coolwarm` would typically shift color **within** the colormap's blue/white/red range
    (a wrong-but-plausible correlation value), producing an even smaller RGB delta than an
    unrelated hue. If even this generous, easiest-to-detect version of a single-cell defect
    isn't caught, a realistic one certainly isn't either. See #768 for the tracked follow-up
    (this is a structural limit of whole-image RMS on a 55-cell grid, not a TODO expected to
    resolve on its own) and design.md's "Known limitation" section for the full reasoning.
    """
    baseline = _BASELINES / "correlation_matrix_turface_19_baseline.png"
    img = Image.open(baseline).convert("RGB")
    w, h = img.size
    side = int((w * h * _REAL_CORRELATION_CELL_AREA_FRACTION) ** 0.5)
    perturbed_img = img.copy()
    x0, y0 = w // 3, h // 3
    ImageDraw.Draw(perturbed_img).rectangle(
        [x0, y0, x0 + side, y0 + side], fill=(255, 165, 0)
    )
    perturbed = tmp_path / "single_cell.png"
    perturbed_img.save(perturbed)

    diff = compare_images(str(baseline), str(perturbed), tol=_TOL)
    assert diff is None, (
        "a realistic single-cell-sized recolor is now caught by _TOL=15 -- this is an "
        "IMPROVEMENT (great!), but update this test's assertion (and design.md / #768) to "
        "reflect the new reality rather than leaving a stale 'not caught' pin: "
        f"{diff}"
    )


def test_missing_baseline_fails_with_an_actionable_message(monkeypatch, viz_env):
    monkeypatch.setattr(sys.modules[__name__], "_BASELINES", viz_env / "no_such_dir")
    with pytest.raises(AssertionError, match="gen_plot_snapshots_golden"):
        test_plot_matches_baseline_within_tolerance(
            "histograms",
            plot_trait_histograms_mod,
            "plot_trait_histograms",
            "histograms_turface_19.png",
            "histograms_turface_19_baseline.png",
            viz_env,
        )
