"""Pixel-level rendering regression tests for the 3 sleap_roots plotting tools (#713).

The former `test_viz_tools.py` only ever asserted `.is_file()` on a generated PNG -- a dependency
bump (matplotlib, Pillow, numpy) or a refactor that silently changes color mapping, plot
geometry, or layout would ship with every existing assertion still green. This file closes
that gap by comparing each tool's real output against a committed baseline PNG
(`tests/fixtures/plot_baselines/`, generated by `scripts/gen_plot_snapshots_golden.py`)
via `matplotlib.testing.compare.compare_images` -- matplotlib's own image-comparison
utility (used by its own test suite), available with **no new dependency**: Pillow, which
`compare_images` needs to load PNGs, is a hard transitive floor of both `matplotlib` and
`sleap-roots-analyze`, bloommcp's own main dependencies (not an incidental extra), so it
is not at risk of quietly disappearing from the venv.

Tolerance (`_TOL`): `compare_images` scores a pair of images by RMS pixel difference (0 =
bit-identical). Some noise is expected even for a correct render: FreeType hinting differs
slightly across OS/font-stack combinations. **The baselines here were generated on
macOS**, not on Linux (see `plot_baselines/MANIFEST.json` and design.md Decision 3 — Docker
was unavailable to produce a Linux-rendered baseline matching the `python-audit` CI job's
`ubuntu-latest` runner at authoring time), so this test's *first* real cross-platform
comparison is CI's own run, not this docstring's say-so. `_TOL` was picked from a real,
reproducible measurement, not guessed, and checked against **all 5 baselines that existed
when it was measured**, not just one (design.md Decision 2 has the full table): uniformly
dimming each baseline by 2%/5%/10% (`PIL.ImageEnhance.Brightness`) scores RMS≈5.4-5.7 /
≈11.7-12.5 / ≈23.4-24.9 respectively -- the 5 plots agreed within ~0.3 RMS at every level
despite very different pixel content, because a *uniform* shift's RMS is dominated by the
large shared white-background area, not each plot's distinct foreground (contrast the
localized-regression case below, whose RMS genuinely does vary a lot by plot type).

Two of those five (`heritability_bar`, `variance_decomposition`) were retired into
`heritability_analysis` by bloom#462 and their baselines deleted. The ranges above are left
as recorded rather than restated for the surviving 3: they are the measurement that was
actually taken, and the surviving plots' individual figures sat inside those ranges, so
narrowing the quoted band would imply a re-measurement that did not happen. `_TOL` itself
is unchanged and still clears the 5%-dim noise floor for every baseline still present.
`test_tolerance_catches_a_real_regression` reproduces the 10%-dim case for `histograms`
live rather than hardcoding it. `_TOL = 15` sits above the 5%-dim noise floor (leaving
headroom for legitimate cross-platform hinting noise, which manifests as far subtler pixel
deltas than a uniform intensity shift) and comfortably below the 10% case a real
color-rendering regression would plausibly produce -- consistently across all 5. If CI's
first real cross-platform run shows the genuine hinting-noise RMS is closer to `_TOL` than
expected, that is the authoritative signal to revisit this constant or regenerate the
baselines from a Linux run -- see `scripts/gen_plot_snapshots_golden.py`'s module
docstring.

Known limitation -- localized regressions, measured per plot type (not just guessed to
generalize from one), and against **real element sizes**, not an assumed area fraction (a
PR review on #713 correctly rejected an earlier version of this section for testing
`correlation_matrix` at ~6x a real cell's actual pixel footprint -- see
`test_realistic_single_cell_defect_in_correlation_matrix_is_not_caught` below):

RMS is a whole-image average, so a spatially small miscoloring is diluted across every
unaffected pixel, and *how much* it's diluted depends on both the perturbed area's size
*and* the plot's own layout. Measuring a real plotting element's actual pixel footprint
(via `ax.get_window_extent()` against the live delegate call, not guessed):

- **`correlation_matrix`** (11 real traits -> 55 lower-triangle cells): one cell measures
  ~108.8x108.8px = **~11,836px², ~0.455% of the 1690x1539 baseline** (exact, reproducible
  geometry -- see `test_realistic_single_cell_defect_in_correlation_matrix_is_not_caught`).
  Recoloring exactly that footprint to the *most detectable possible* color (opaque orange
  against `coolwarm`'s blue/white/red range -- a real miscolored cell would typically shift
  color **within** the colormap's range, an even smaller RGB delta) scores **RMS≈5.2** --
  nowhere near `_TOL=15`. **A genuine single-cell defect in `correlation_matrix` is not
  reliably caught by this check, full stop** -- not "might slip through under bad luck",
  a bug producing exactly this failure mode would not be flagged. There is no `_TOL` value
  that both survives legitimate cross-platform noise (~5-12 RMS just from FreeType hinting
  differences, see the Tolerance section above) and clears a ~5 RMS single-cell signal --
  the two are the same order of magnitude. This is not a gap this PR closes; it's a real,
  permanent limit of whole-image RMS comparison applied to a 55-cell grid, tracked as
  **#768** rather than left as an implicit assumption.
- **`heritability_bar`** (RETIRED by bloom#462 -- kept here as the record of what was
  measured, since it is what justified the localized-regression probe size): same 11 traits
  -> 11 bars, bar *area* varying with each trait's H2 value (near-zero for a low-H2 bar up
  to the full bar height for H2≈1) -- measured directly via each bar patch's
  `get_window_extent()`: real single-bar areas ranged ~0%-2.89% of the image, median ~2.41%,
  and a 2% probe cleared `_TOL=15` at RMS≈17.0. With that tool retired, the only remaining
  localized-regression case is `correlation_matrix`'s, so **no bar-shaped probe is exercised
  any more** -- an honest reduction in what this file proves, not an oversight.
- `histograms`/`boxplots`: not individually re-measured at their real single-element size --
  both carry large enough headroom at a uniform 2% probe (RMS≈21.7-22.1, well above
  `_TOL=15`) that a smaller real element is very likely still caught, but this is not
  asserted by a dedicated test the way `correlation_matrix` is (see the comment on
  `_SNAPSHOT_TOOLS`/`_LOCALIZED_REGRESSION_CASES` below).

`test_tolerance_catches_a_localized_regression` proves `_TOL` catches a **several-cells-
worth** regression in `correlation_matrix` (~3% area, ~6-7 real cells) -- a plausible
shape for a bug affecting a contiguous block (e.g. one trait's whole row/column), not a
claim that single-cell defects are covered. These measurements are a snapshot of today's
baselines, not a law -- re-measure after any change to a plot's trait count, color
density, or layout.

Scope: the 3 dedicated plotting tools (5 until #462 retired the two heritability plots into
`heritability_analysis`, which renders them through `ResultStore` — see the note on
`_SNAPSHOT_TOOLS`), **plus the 8 optional plot keys** `pca_analysis`/`umap_analysis`/
`clustering` emit under `include_plots=True` (#723, the follow-up #713 scoped out). The
optional-key section lives at the bottom of this file; `_TOL` was re-derived for those 8
rather than assumed to carry over. `heritability_analysis`'s two folded-in figures remain
uncovered -- they need a different fixture, and that is still a follow-up.

**These baselines are a drift gate, not a correctness oracle.** Every baseline is generated
from the code as it renders today, so a figure that is scientifically wrong today is frozen
wrong, and the regeneration gate then defends it. One such defect is already known and
documented rather than silently canonized: `create_feature_contribution_heatmap` is titled
"Feature Loadings (Correlations)" with a "Loading (Correlation)" colorbar, but plots
unit-norm eigenvector components, which are **not** correlations (the trait-PC correlation is
`component x sqrt(eigenvalue)`; on this fixture that understates PC1 by ~2.7x and overstates
PC5 by ~2x, so the error reverses direction across the columns a reader compares). See
`tests/fixtures/README.md`. What these tests prove is that rendering has not *drifted* --
scientific correctness is the numeric goldens' job (`turface_19_pca_golden.json`,
`test_clustering_tool.py`'s oracles), not this file's.
"""

from __future__ import annotations

import shutil
import sys
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import pytest
from matplotlib.testing.compare import compare_images
from matplotlib.testing.exceptions import ImageComparisonFailure
from PIL import Image, ImageDraw, ImageEnhance
from sleap_roots_analyze.visualization import create_correlation_heatmap

from bloom_mcp import experiment_utils as eu
from bloom_mcp.sections.sleap_roots.analysis import (
    plot_correlation_matrix as plot_correlation_matrix_mod,
    plot_trait_boxplots as plot_trait_boxplots_mod,
    plot_trait_histograms as plot_trait_histograms_mod,
)

_BASELINES = Path(__file__).resolve().parents[1] / "fixtures" / "plot_baselines"
_EXPERIMENT = "turface_19.csv"
# The same CSV `viz_env` copies into TRAITS_DIR — the converged tools read through the
# ExperimentReader port instead, so their FakeReader has to be seeded from it directly.
_RAW_FIXTURE = (
    Path(__file__).resolve().parents[1] / "fixtures" / "turface_19_final_data.csv"
)

# The converged 3 name their committed PNG after the tool, not after the experiment, so the
# legacy `<label>_turface_19.png` names in _SNAPSHOT_TOOLS don't apply to them. Baselines
# keep their original names — only the produced file's name differs.
_PRODUCED_NAME_OVERRIDES = {
    "histograms": "trait_histograms.png",
    "boxplots": "trait_boxplots.png",
    "correlation_matrix": "correlation_matrix.png",
}

# Empirically derived, not guessed -- see the module docstring's Tolerance and Known
# limitation sections (design.md Decisions 2 & 3 have the full measurement + fallback
# plan). Changing this number should come with a fresh measurement, not a vibe.
_TOL = 15

# (label, tool module, tool fn name, produced PNG name, baseline PNG name)
#
# All 3 are covered by test_plot_matches_baseline_within_tolerance (the production
# comparison). Only `correlation_matrix` additionally gets a dedicated localized-
# regression negative-control case below (_LOCALIZED_REGRESSION_CASES) --
# `histograms`/`boxplots`'s ~2%-area floor is documented in the module docstring's
# "Known limitation" section but NOT independently test-enforced; nothing in CI would
# catch a future baseline regeneration quietly eroding their margin against `_TOL=15`.
#
# This list was 5 until bloom#462 retired `plot_heritability_bar` and
# `plot_variance_decomposition` into `heritability_analysis`. That tool renders the same
# two figures, but persists them through the `ResultStore` port rather than writing to
# `PLOTS_DIR`, so this harness (built entirely around `viz_env`/`PLOTS_DIR`) does not
# reach them -- snapshot coverage for them would need a different fixture, tracked as a
# follow-up rather than bolted on here.
_SNAPSHOT_TOOLS = [
    (
        "histograms",
        plot_trait_histograms_mod,
        "plot_trait_histograms",
        "histograms_turface_19.png",
        "histograms_turface_19_baseline.png",
    ),
    (
        "boxplots",
        plot_trait_boxplots_mod,
        "plot_trait_boxplots",
        "boxplots_turface_19.png",
        "boxplots_turface_19_baseline.png",
    ),
    (
        "correlation_matrix",
        plot_correlation_matrix_mod,
        "plot_correlation_matrix",
        "correlation_matrix_turface_19.png",
        "correlation_matrix_turface_19_baseline.png",
    ),
]
_IDS = [label for label, *_ in _SNAPSHOT_TOOLS]


# The 3 tools #466 converged onto `@as_mcp_tool` no longer match the legacy calling
# convention the other 2 still use, so this file can no longer drive all 5 the same way.
# They take a Pydantic params model (not a bare experiment string), return a result model
# (not a "Plot saved: ..." string), and persist their PNG into a ResultStore version dir
# (not PLOTS_DIR). Pixel coverage is preserved for them rather than dropped: the render
# itself is unchanged, and these baselines still match within `_TOL` (verified against the
# committed baselines when this adaptation landed, #466 review round 7).
def _render_to_dir(label, module, fn_name, viz_env):
    """Run one plotting tool and return the directory its PNG(s) landed in.

    All 3 tools here write into a ``ResultStore`` staging dir that ``commit`` deletes on
    success, so their bytes are copied out inside a ``commit`` spy — the last point at which
    the committed file still exists on disk. Capturing at commit (rather than spying on
    ``savefig``) means the bytes compared are exactly the bytes that were committed, not an
    intermediate render. (A ``PLOTS_DIR`` branch for the two legacy tools lived here until
    #462 retired them; ``viz_env`` now serves only as scratch space.)
    """
    fn = getattr(module, fn_name)

    import pandas as pd
    from bloom_mcp.data_access import FakeReader, SupabaseReader
    from bloom_mcp.result_store import FakeResultStore, SupabaseResultStore
    from bloom_mcp.tools import _ports

    captured = viz_env / f"_committed_{label}"
    captured.mkdir(parents=True, exist_ok=True)

    reader = FakeReader()
    reader.add_experiment(_EXPERIMENT, pd.read_csv(_RAW_FIXTURE))
    store = FakeResultStore()
    real_commit = store.commit

    def _spy_commit(run, outputs):
        for name in outputs:
            shutil.copy(run.staging_dir / name, captured / name)
        return real_commit(run, outputs)

    store.commit = _spy_commit
    _ports.configure(reader=reader, store=store)
    try:
        fn(experiment=_EXPERIMENT)
    finally:
        _ports.configure(reader=SupabaseReader(), store=SupabaseResultStore())
    return captured


@pytest.mark.parametrize(
    "_label,module,fn_name,produced_name,baseline_name", _SNAPSHOT_TOOLS, ids=_IDS
)
def test_plot_matches_baseline_within_tolerance(
    _label, module, fn_name, produced_name, baseline_name, viz_env
):
    produced_dir = _render_to_dir(_label, module, fn_name, viz_env)

    actual = produced_dir / _PRODUCED_NAME_OVERRIDES.get(_label, produced_name)
    baseline = _BASELINES / baseline_name
    assert actual.is_file()
    assert baseline.is_file(), (
        f"missing baseline {baseline} -- run "
        "`uv run --frozen --extra test python scripts/gen_plot_snapshots_golden.py --yes` to create it"
    )

    _compare_or_fail(baseline, actual)


# Appended to EVERY failure this helper raises, not just the exception path -- a PR review
# on #713 found the original version only attached this pointer inside the `except` block,
# which `compare_images` never actually reaches for the ordinary "RMS exceeded `_TOL`" case
# (that's a plain returned string, not a raised exception -- see the two paths in
# `_compare_or_fail` below). The pointer was therefore dead code for the exact scenario
# `_TOL` itself is calibrated against.
_CROSS_PLATFORM_POINTER = (
    "\nIf this is an RMS-over-tolerance message OR a dimension-mismatch exception, it may "
    "be legitimate cross-platform FreeType-hinting / bbox_inches='tight' canvas-size noise "
    "rather than a content regression -- see design.md Decision 3 before regenerating "
    "baselines or changing _TOL."
)


def _compare_or_fail(baseline: Path, actual: Path) -> None:
    """Compare and fail with `_CROSS_PLATFORM_POINTER` attached either way `compare_images`
    can fail: it raises `ImageComparisonFailure` for a pixel-dimension mismatch (e.g. if
    `bbox_inches="tight"`, `_viz_shared.save_plot`'s save call, produced a different canvas
    size on this platform than the baseline's), but returns a plain failure *string* (no
    exception) for an ordinary RMS-over-`_TOL` mismatch -- both need the same pointer, not
    just the exception path. `OSError` also covers `PIL.UnidentifiedImageError` (a
    committed baseline PNG that's corrupted/truncated) -- low-likelihood since baselines are
    ordinary committed git binaries, but a real failure mode `_load_image` can hit, unlike a
    speculative `ValueError` no path in `matplotlib.testing.compare` actually raises.
    """
    try:
        diff = compare_images(str(baseline), str(actual), tol=_TOL)
    except (ImageComparisonFailure, OSError) as exc:
        pytest.fail(f"{exc}{_CROSS_PLATFORM_POINTER}")
    if diff is not None:
        pytest.fail(f"{diff}{_CROSS_PLATFORM_POINTER}")


def test_tolerance_catches_a_real_regression(tmp_path):
    """`_TOL` must not be so loose it rubber-stamps a genuine rendering regression.

    Dims one real baseline by 10% (`PIL.ImageEnhance.Brightness(0.9)`) -- the same
    perturbation the module docstring cites as scoring RMS≈24.4, reproduced live here
    (not hardcoded) so this stays a real assertion against `compare_images`, not a pinned
    magic number. A uniform intensity shift is a stand-in for "a rendering regression
    large enough to matter", not a literal simulation of any specific known bug.
    """
    baseline = _BASELINES / "histograms_turface_19_baseline.png"
    dimmed = ImageEnhance.Brightness(Image.open(baseline)).enhance(0.9)
    perturbed = tmp_path / "dimmed.png"
    dimmed.save(perturbed)

    diff = compare_images(str(baseline), str(perturbed), tol=_TOL)
    assert diff is not None, (
        f"a 10%-dimmed baseline compared equal to itself -- _TOL={_TOL} is too loose "
        "to catch a real regression"
    )


_LOCALIZED_REGRESSION_CASES = [
    # (baseline filename, area fraction). This held a second entry -- heritability_bar at
    # 2%, the only *bar-shaped* localized probe -- until bloom#462 retired that tool; the
    # measured single-bar range that justified it (~0%-2.89%, median ~2.41%) is kept in the
    # module docstring as the record of what was measured, not silently deleted.
    # correlation_matrix's 3% is deliberately NOT a single real cell (one cell measures
    # ~0.455%, see test_realistic_single_cell_defect_in_correlation_matrix_is_not_caught
    # below, which pins that a real single-cell defect is NOT caught) -- 3% represents
    # ~6-7 real cells' worth of area, a plausible "whole row/column wrong" bug shape, with
    # real margin above the ~2.5% RMS-crossing point measured for that size.
    ("correlation_matrix_turface_19_baseline.png", 0.03),
]


@pytest.mark.parametrize(
    "baseline_name,area_fraction",
    _LOCALIZED_REGRESSION_CASES,
    ids=[name.split("_turface")[0] for name, _ in _LOCALIZED_REGRESSION_CASES],
)
def test_tolerance_catches_a_localized_regression(
    tmp_path, baseline_name, area_fraction
):
    """A *global* dim (above) isn't the only regression shape worth proving `_TOL` catches
    -- a spatially small miscoloring only touches part of the image, and RMS is a
    whole-image average (see module docstring's "Known limitation"). Proves `_TOL` catches
    a **several-elements-worth** localized regression on both `heritability_bar` (a
    realistically-sized single bar) and `correlation_matrix` (several cells, NOT a single
    cell -- see the dedicated single-cell test below for that honest negative result).
    """
    baseline = _BASELINES / baseline_name
    img = Image.open(baseline).convert("RGB")
    w, h = img.size
    perturbed_img = img.copy()
    side = int((w * h * area_fraction) ** 0.5)
    x0, y0 = w // 3, h // 3
    ImageDraw.Draw(perturbed_img).rectangle(
        [x0, y0, x0 + side, y0 + side], fill=(255, 165, 0)
    )
    perturbed = tmp_path / "localized.png"
    perturbed_img.save(perturbed)

    diff = compare_images(str(baseline), str(perturbed), tol=_TOL)
    assert diff is not None, (
        f"a ~{area_fraction * 100:.0f}%-area recolored {baseline_name} compared equal to "
        f"itself -- _TOL={_TOL} is too loose to catch even this deliberately-sized "
        "localized regression"
    )


# Exact geometry for turface_19's real correlation_matrix render, measured directly against
# the live delegate call via ax.get_window_extent() (not eyeballed): create_correlation_heatmap
# renders turface_19's 11 real trait columns into an 11x11 grid (mask hides the upper
# triangle + diagonal, leaving 55 real cells) inside a square axes measuring
# 1196.7x1196.7px at the actual save dpi=150. One cell is therefore
# 1196.7/11 = ~108.8px per side = ~11,836px^2 of the baseline's 1690x1539 = 2,600,910px^2
# total -- ~0.455%. Re-derive this (same method: render, `fig.canvas.draw()`,
# `ax.get_window_extent(fig.canvas.get_renderer())`) if the fixture's trait count or the
# delegate's figsize/dpi ever changes; do not just bump the fraction.
_REAL_CORRELATION_CELL_AREA_FRACTION = 11836 / (1690 * 1539)


def _measure_live_correlation_cell_area_fraction() -> float:
    """Independently re-derive `_REAL_CORRELATION_CELL_AREA_FRACTION` by actually rendering
    the live delegate call and measuring its geometry, rather than trusting the hardcoded
    comment above to stay accurate forever -- a third review correctly pointed out that a
    comment telling a human to re-derive a number by hand is exactly the kind of thing that
    silently goes stale (it's how the original 3%-vs-0.455% error happened in the first
    place). Mirrors `scripts/gen_plot_snapshots_golden.py`'s own real-fixture setup, not a
    synthetic stand-in.
    """
    raw = Path(__file__).resolve().parents[1] / "fixtures" / "turface_19_final_data.csv"
    df = pd.read_csv(raw, encoding="utf-8")
    trait_cols = eu.detect_columns(df)["trait_cols"]
    n = len(trait_cols)

    fig = create_correlation_heatmap(df, trait_cols)
    try:
        ax = fig.axes[0]
        fig.canvas.draw()
        ax_bbox = ax.get_window_extent(fig.canvas.get_renderer())
        save_dpi = 150  # matches the dpi the 3 converged tools pass to savefig
        scale = save_dpi / fig.dpi
        cell_area_px = (ax_bbox.width * scale / n) * (ax_bbox.height * scale / n)
    finally:
        plt.close(fig)

    baseline = _BASELINES / "correlation_matrix_turface_19_baseline.png"
    w, h = Image.open(baseline).size
    return cell_area_px / (w * h)


def test_real_correlation_cell_area_fraction_matches_measured_geometry():
    """`_REAL_CORRELATION_CELL_AREA_FRACTION` -- the basis for both the localized-regression
    test sizing and the single-cell pinning test below -- must not silently drift from
    reality. If `turface_19`'s trait count or `create_correlation_heatmap`'s figsize/dpi ever
    changes, this fails loudly (telling a developer to re-derive the constant and update the
    docs/comments that cite it) instead of leaving a stale number nobody notices.
    """
    live = _measure_live_correlation_cell_area_fraction()
    assert live == pytest.approx(_REAL_CORRELATION_CELL_AREA_FRACTION, rel=0.05), (
        f"live-measured cell area fraction ({live:.5f}) has drifted from the hardcoded "
        f"_REAL_CORRELATION_CELL_AREA_FRACTION ({_REAL_CORRELATION_CELL_AREA_FRACTION:.5f}) "
        "-- re-derive the constant (see its comment) and update design.md/#768 if the new "
        "value changes the single-cell-detection conclusion"
    )


def test_realistic_single_cell_defect_in_correlation_matrix_is_not_caught(tmp_path):
    """Honest negative result, not a gap papered over: a real single-cell defect in
    `correlation_matrix` -- the tool where a silent wrong value is most scientifically
    consequential -- is measurably NOT caught by `_TOL=15`. A PR review on #713 correctly
    rejected an earlier version of this suite that tested at ~6x a real cell's actual size
    and called the gap "resolved"; it wasn't. This test locks in the actual, current
    behavior instead: it should fail loudly (telling us something changed, for better or
    worse) if a future baseline regeneration or `_TOL` change ever alters this outcome --
    it must NOT be treated as passing proof the gap is fine to ignore.

    Uses opaque orange -- the same maximally-detectable color the other tests in this file
    use -- which is *more* detectable than a realistic bug: a real miscolored cell under
    `coolwarm` would typically shift color **within** the colormap's blue/white/red range
    (a wrong-but-plausible correlation value), producing an even smaller RGB delta than an
    unrelated hue. If even this generous, easiest-to-detect version of a single-cell defect
    isn't caught, a realistic one certainly isn't either. See #768 for the tracked follow-up
    (this is a structural limit of whole-image RMS on a 55-cell grid, not a TODO expected to
    resolve on its own) and design.md's "Known limitation" section for the full reasoning.
    """
    baseline = _BASELINES / "correlation_matrix_turface_19_baseline.png"
    img = Image.open(baseline).convert("RGB")
    w, h = img.size
    side = int((w * h * _REAL_CORRELATION_CELL_AREA_FRACTION) ** 0.5)
    perturbed_img = img.copy()
    x0, y0 = w // 3, h // 3
    ImageDraw.Draw(perturbed_img).rectangle(
        [x0, y0, x0 + side, y0 + side], fill=(255, 165, 0)
    )
    perturbed = tmp_path / "single_cell.png"
    perturbed_img.save(perturbed)

    diff = compare_images(str(baseline), str(perturbed), tol=_TOL)
    assert diff is None, (
        "a realistic single-cell-sized recolor is now caught by _TOL=15 -- this is an "
        "IMPROVEMENT (great!), but update this test's assertion (and design.md / #768) to "
        "reflect the new reality rather than leaving a stale 'not caught' pin: "
        f"{diff}"
    )


def test_missing_baseline_fails_with_an_actionable_message(monkeypatch, viz_env):
    monkeypatch.setattr(sys.modules[__name__], "_BASELINES", viz_env / "no_such_dir")
    with pytest.raises(AssertionError, match="gen_plot_snapshots_golden"):
        test_plot_matches_baseline_within_tolerance(
            "histograms",
            plot_trait_histograms_mod,
            "plot_trait_histograms",
            "histograms_turface_19.png",
            "histograms_turface_19_baseline.png",
            viz_env,
        )


# ── Optional plot keys: pca_analysis / umap_analysis / clustering (#723) ─────────────
#
# #713 scoped these out and tracked them as #723; this is that follow-up. They differ from
# the 3 above in two ways that matter to the harness:
#
#   1. They are `require_clean=True` consumers, so their `FakeReader` is seeded with
#      `add_cleaned_version` rather than `add_experiment`.
#   2. They take a Pydantic params model and only emit figures when `include_plots=True`.
#
# Everything else -- the `commit` spy capture, `_compare_or_fail`, `_TOL` -- is shared, and
# `_TOL = 15` was re-derived for these 8 rather than assumed to carry over (design.md
# Decision 1 of add-bloommcp-optional-plot-snapshot-tests has the full dimming table; the
# short version is that it clears every 5%-dim value, max 12.9, and sits under every
# 10%-dim value, min 20.5).
#
# What these baselines do and do not prove: they are a **drift gate, not a correctness
# oracle**. A baseline is generated from the code as it renders today, so a figure that is
# scientifically wrong today is frozen wrong -- see `tests/fixtures/README.md`, which
# records one such known defect in `create_feature_contribution_heatmap`'s title. Two
# measured blind spots are pinned below rather than presented as coverage.

_OPTIONAL_EXPERIMENT = "turface_19.csv"

# (label, params factory, catalog keys) -- one render per tool, memoized, so `pca_analysis`
# is not re-fitted once per parametrized key (measured: a naive per-key render costs ~7.7s
# against ~3.6s memoized, almost all of it umap-learn's numba JIT).
_OPTIONAL_TOOLS = [
    (
        "pca",
        "pca_analysis",
        (
            "create_pca_scree_plot",
            "create_pca_biplot",
            "create_feature_contribution_plot",
            "create_feature_contribution_heatmap",
        ),
    ),
    (
        "umap",
        "umap_analysis",
        ("create_umap_single_trait", "create_umap_colored_by_top_traits"),
    ),
    (
        "clustering",
        "clustering",
        ("create_cluster_scatter_pca", "create_cluster_size_barplot"),
    ),
]

_OPTIONAL_KEYS = [(label, key) for label, _fn, keys in _OPTIONAL_TOOLS for key in keys]
_OPTIONAL_IDS = [key for _label, key in _OPTIONAL_KEYS]

# Memo for the per-tool render. Deliberately a module-level dict rather than a
# `@pytest.fixture(scope="module")`: the natural dependency `viz_env` is function-scoped
# (it takes `monkeypatch`/`tmp_path`/`fake_supabase_storage`), and pytest forbids a
# broader-scoped fixture depending on narrower-scoped ones. These tests need no `viz_env`
# at all -- `FakeReader` bypasses the `TRAITS_DIR` read it exists to set up.
_OPTIONAL_RENDER_CACHE: dict = {}


def _optional_params(fn_name: str, **overrides):
    """Build a tool's params model with `include_plots=True` and otherwise defaults."""
    from bloom_mcp.sections.sleap_roots.analysis.clustering import ClusteringParams
    from bloom_mcp.sections.sleap_roots.analysis.pca_analysis import PCAAnalysisParams
    from bloom_mcp.sections.sleap_roots.analysis.umap_analysis import UMAPAnalysisParams

    models = {
        "pca_analysis": PCAAnalysisParams,
        "umap_analysis": UMAPAnalysisParams,
        "clustering": ClusteringParams,
    }
    return models[fn_name](
        experiment=_OPTIONAL_EXPERIMENT, include_plots=True, **overrides
    )


def _render_optional_to_dir(fn_name: str, capture: Path, **overrides) -> Path:
    """Run one `include_plots=True` tool and return the dir its PNGs landed in.

    Same `commit`-spy capture as `_render_to_dir` -- `FakeResultStore.commit` deletes the
    staging dir on success, so that is the last moment the committed bytes exist on disk,
    and capturing there means the pixels compared are the committed ones rather than an
    intermediate render. Differs only in seeding a *cleaned* version (these tools are
    `require_clean=True`) and in taking a params model.
    """
    from bloom_mcp.data_access import FakeReader, SupabaseReader
    from bloom_mcp.result_store import FakeResultStore, SupabaseResultStore
    from bloom_mcp.sections.sleap_roots.analysis import clustering as clustering_mod
    from bloom_mcp.sections.sleap_roots.analysis import pca_analysis as pca_mod
    from bloom_mcp.sections.sleap_roots.analysis import umap_analysis as umap_mod
    from bloom_mcp.tools import _ports

    fns = {
        "pca_analysis": pca_mod.pca_analysis,
        "umap_analysis": umap_mod.umap_analysis,
        "clustering": clustering_mod.clustering,
    }
    capture.mkdir(parents=True, exist_ok=True)

    reader = FakeReader()
    reader.add_cleaned_version(
        _OPTIONAL_EXPERIMENT, "v1", pd.read_csv(_RAW_FIXTURE), make_latest=True
    )
    store = FakeResultStore()
    real_commit = store.commit

    def _spy_commit(run, outputs):
        for name in outputs:
            if name.endswith(".png"):
                shutil.copy(run.staging_dir / name, capture / name)
        return real_commit(run, outputs)

    store.commit = _spy_commit
    _ports.configure(reader=reader, store=store)
    try:
        fns[fn_name](_optional_params(fn_name, **overrides))
    finally:
        _ports.configure(reader=SupabaseReader(), store=SupabaseResultStore())
    return capture


def _rendered(label: str, tmp_path_factory) -> Path:
    """Memoized default render for one tool, shared across its parametrized keys."""
    if label not in _OPTIONAL_RENDER_CACHE:
        fn_name = next(fn for lbl, fn, _k in _OPTIONAL_TOOLS if lbl == label)
        # Kept under pytest's own tmp root so CI's `/tmp/pytest-of-*/**/*-failed-diff.png`
        # artifact glob still matches any diff `compare_images` writes next to the actual.
        capture = tmp_path_factory.mktemp(f"optional_{label}")
        _OPTIONAL_RENDER_CACHE[label] = _render_optional_to_dir(fn_name, capture)
    return _OPTIONAL_RENDER_CACHE[label]


def _optional_baseline(key: str) -> Path:
    return _BASELINES / f"{key}_turface_19_baseline.png"


def test_optional_plot_keys_render_and_commit(tmp_path_factory):
    """1.1 -- every catalog key actually reaches disk through the tool's commit path."""
    for label, _fn, keys in _OPTIONAL_TOOLS:
        produced = _rendered(label, tmp_path_factory)
        for key in keys:
            assert (
                produced / f"{key}.png"
            ).is_file(), (
                f"{label}: expected {key}.png to be committed with include_plots=True"
            )


def test_baseline_set_matches_the_tool_catalogs():
    """1.3 -- the baseline set tracks the tools' catalogs, in both directions.

    Compared against files on disk rather than against this module's own parametrization
    table: a table-vs-table check would pass while an orphaned baseline sat in the fixtures
    directory after its catalog key was removed.
    """
    from bloom_mcp.sections.sleap_roots.analysis.clustering import (
        _CLUSTERING_CATALOG_KEYS,
    )
    from bloom_mcp.sections.sleap_roots.analysis.pca_analysis import _PCA_CATALOG_KEYS
    from bloom_mcp.sections.sleap_roots.analysis.umap_analysis import _UMAP_CATALOG_KEYS

    catalog = (
        set(_PCA_CATALOG_KEYS) | set(_UMAP_CATALOG_KEYS) | set(_CLUSTERING_CATALOG_KEYS)
    )
    on_disk = {
        p.name[: -len("_turface_19_baseline.png")]
        for p in _BASELINES.glob("create_*_turface_19_baseline.png")
    }
    assert on_disk == catalog, (
        "baseline set and tool catalogs disagree -- missing "
        f"{sorted(catalog - on_disk)}, orphaned {sorted(on_disk - catalog)}. Run "
        "`uv run --frozen --extra test python scripts/gen_plot_snapshots_golden.py --yes`"
    )


@pytest.mark.parametrize("_label,key", _OPTIONAL_KEYS, ids=_OPTIONAL_IDS)
def test_optional_plot_matches_baseline_within_tolerance(_label, key, tmp_path_factory):
    """3.1 -- the production comparison for all 8 optional keys."""
    produced = _rendered(_label, tmp_path_factory)
    actual = produced / f"{key}.png"
    baseline = _optional_baseline(key)
    assert actual.is_file()
    # Re-stated here rather than delegated: `_compare_or_fail` handles only the
    # ImageComparisonFailure/OSError and RMS-string paths, and its message points at
    # design.md Decision 3 -- never at the regeneration script.
    assert baseline.is_file(), (
        f"missing baseline {baseline} -- run "
        "`uv run --frozen --extra test python scripts/gen_plot_snapshots_golden.py --yes` to create it"
    )

    _compare_or_fail(baseline, actual)


def test_missing_optional_baseline_fails_with_an_actionable_message(
    monkeypatch, tmp_path_factory, tmp_path
):
    """3.3 -- the missing-baseline guard is a committed test, not a one-off manual check."""
    monkeypatch.setattr(sys.modules[__name__], "_BASELINES", tmp_path / "no_such_dir")
    with pytest.raises(AssertionError, match="gen_plot_snapshots_golden"):
        test_optional_plot_matches_baseline_within_tolerance(
            "pca", "create_pca_scree_plot", tmp_path_factory
        )


# 3.4 -- positive controls over REAL semantic perturbations, not just a uniform dim.
#
# A uniform brightness shift is the weakest available probe: as this module's docstring
# notes, its RMS is dominated by the large shared white background rather than by each
# plot's own content. These cases instead re-render the tool with a genuinely different
# scientific parameter, which is the regression shape these baselines exist to catch.
# Recorded RMS values are from design.md Decision 2's measurement table.
_REAL_REGRESSION_CASES = [
    ("pca", {"standardize": False}, "create_pca_scree_plot", 110.2),
    ("pca", {"standardize": False}, "create_feature_contribution_plot", 100.6),
    ("clustering", {"n_clusters": 5}, "create_cluster_size_barplot", 67.1),
]


@pytest.mark.parametrize(
    "label,overrides,key,recorded_rms",
    _REAL_REGRESSION_CASES,
    ids=[f"{k}" for _l, _o, k, _r in _REAL_REGRESSION_CASES],
)
def test_tolerance_catches_a_real_parameter_regression(
    label, overrides, key, recorded_rms, tmp_path_factory
):
    """A changed scientific parameter is caught, well clear of `_TOL`."""
    fn_name = next(fn for lbl, fn, _k in _OPTIONAL_TOOLS if lbl == label)
    capture = tmp_path_factory.mktemp(f"regress_{key}")
    produced = _render_optional_to_dir(fn_name, capture, **overrides)
    baseline = _optional_baseline(key)

    try:
        diff = compare_images(str(baseline), str(produced / f"{key}.png"), tol=_TOL)
    except ImageComparisonFailure:
        # A canvas-size change is also a caught regression -- it is how 4 of the 8 keys
        # surface a real parameter change (design.md Decision 2's "what is caught" table).
        return
    assert diff is not None, (
        f"{key}: {overrides} no longer produces a difference over _TOL={_TOL} "
        f"(was RMS~{recorded_rms}). Either the parameter stopped affecting the figure or "
        "the baseline was regenerated from the perturbed render -- both are real problems."
    )


def test_single_cell_loadings_defect_is_caught(tmp_path_factory):
    """3.4 -- a wrong loadings value in the heatmap IS caught (design.md Decision 2).

    Recorded here because an earlier draft of this change claimed the opposite, from a
    measurement taken through the *delegate* with every numeric column (13 rows) instead of
    the tool's 11 certified traits. Re-measured correctly, a real single-cell defect scores
    RMS 40-64: `sns.heatmap(annot=True, fmt=".3f")` prints each cell's value, so a wrong
    loading changes glyphs as well as colour, and seaborn normalises the colormap across the
    whole matrix, so one changed value rescales every other cell. That makes this heatmap the
    opposite of `plot_correlation_matrix`'s 55-cell grid (#768), not another instance of it.
    """
    import copy

    import sleap_roots_analyze as sra
    from sleap_roots_analyze import create_feature_contribution_heatmap

    from bloom_mcp.data_access import FakeReader

    reader = FakeReader()
    reader.add_cleaned_version(
        _OPTIONAL_EXPERIMENT, "v1", pd.read_csv(_RAW_FIXTURE), make_latest=True
    )
    frame = reader.load_experiment(_OPTIONAL_EXPERIMENT, require_clean=True)
    trait_cols = list(frame.trait_cols)
    res = sra.perform_pca_analysis(frame.df[trait_cols], standardize=True)
    result_dict = res if isinstance(res, dict) else dict(res)
    n_comp = len(result_dict["explained_variance_ratio"])

    out = tmp_path_factory.mktemp("heatmap_cell")

    def _render(rd, path):
        fig = create_feature_contribution_heatmap(
            rd, n_components=n_comp, n_features=len(trait_cols), plot_type="loadings"
        )
        fig.savefig(path, bbox_inches="tight")  # the tool's own save call (no dpi=)
        plt.close(fig)

    clean = out / "clean.png"
    _render(result_dict, clean)

    perturbed = copy.deepcopy(result_dict)
    loadings = np.array(perturbed["loadings"], dtype=float)
    loadings.reshape(-1)[0] += 0.20  # one cell, a plausible defect magnitude
    perturbed["loadings"] = loadings
    defect = out / "defect.png"
    _render(perturbed, defect)

    diff = compare_images(str(clean), str(defect), tol=_TOL)
    assert diff is not None, (
        "a single wrong loadings value is no longer caught at _TOL -- design.md Decision 2 "
        "and this test's docstring both need revisiting"
    )


def _rms_or_skip_on_canvas_change(baseline: Path, actual: Path) -> float:
    """RMS between two images, failing loudly (with the pointer) on a canvas-size change.

    The blind-spot pins below compare a LIVE re-render against a committed baseline, so on
    a platform whose font metrics move a `bbox_inches="tight"` canvas, `compare_images`
    raises rather than returning -- which would surface as an error with no explanation
    instead of a failure naming the likely cause.
    """
    try:
        diff = compare_images(str(baseline), str(actual), tol=0, in_decorator=True)
    except (ImageComparisonFailure, OSError) as exc:
        pytest.fail(f"{exc}{_CROSS_PLATFORM_POINTER}")
    return diff["rms"] if diff else 0.0


def test_cluster_scatter_pca_does_not_catch_a_cluster_count_change(tmp_path_factory):
    """4.1 -- PINNED LIMITATION, not coverage (design.md Decision 2, blind spot A).

    `create_cluster_scatter_pca` does not detect a change of cluster assignment at all:
    measured RMS 3.8-11.6 across k=3/4/5/8, gmm and hierarchical, entirely below this
    plot's own 5%-dim noise floor of 12.9 -- so no `_TOL` separates the signal from
    ordinary cross-platform noise. ~153 small markers on a mostly-white canvas dilute the
    whole-image average. Clustering *correctness* is covered numerically by
    `test_clustering_tool.py`; this baseline covers rendering/layout/dependency drift only.

    `n_clusters=8` is pinned deliberately: it is the worst measured case (RMS 11.60), so
    this test has the least headroom to `_TOL` and fails first if the picture changes.
    """
    capture = tmp_path_factory.mktemp("scatter_blind")
    produced = _render_optional_to_dir("clustering", capture, n_clusters=8)
    baseline = _optional_baseline("create_cluster_scatter_pca")
    actual = produced / "create_cluster_scatter_pca.png"

    rms = _rms_or_skip_on_canvas_change(baseline, actual)
    # Two-sided: a bare "not caught" assertion would also pass if the re-render were
    # byte-identical (e.g. a refactor that silently ignored `n_clusters`), making the test
    # vacuous while reading as coverage.
    assert rms > 3.0, (
        f"re-rendering with n_clusters=8 changed the image by only RMS={rms:.2f} -- the "
        "perturbation is not taking effect, so this test proves nothing"
    )
    assert rms < _TOL, (
        f"a cluster-count change is NOW caught at _TOL={_TOL} (RMS={rms:.2f}) -- this is an "
        "IMPROVEMENT, but update design.md Decision 2 and this pin rather than leaving a "
        "stale 'not caught' claim"
    )
    assert rms < 13.0, (
        f"RMS={rms:.2f} has drifted above the measured 3.8-11.6 band -- re-measure before "
        "trusting either this pin or design.md's table"
    )


def test_cluster_size_barplot_does_not_catch_a_same_k_membership_change(
    tmp_path_factory,
):
    """4.2 -- PINNED LIMITATION (design.md Decision 2, blind spot B).

    `method="hierarchical"` returns the same k=2 as the kmeans baseline but different
    cluster sizes, scoring RMS 13.5 -- under `_TOL=15`. Narrower than blind spot A (a
    k-change is caught at 64.7-69.5), but it bounds the design's claim that the barplot
    compensates for the scatter's blindness: the one regression shape the scatter cannot
    see is also the shape the barplot handles worst.
    """
    capture = tmp_path_factory.mktemp("barplot_blind")
    produced = _render_optional_to_dir("clustering", capture, method="hierarchical")
    baseline = _optional_baseline("create_cluster_size_barplot")
    actual = produced / "create_cluster_size_barplot.png"

    rms = _rms_or_skip_on_canvas_change(baseline, actual)
    assert rms > 3.0, (
        f"method='hierarchical' changed the image by only RMS={rms:.2f} -- the perturbation "
        "is not taking effect, so this test proves nothing"
    )
    assert rms < _TOL, (
        f"a same-k membership change is NOW caught at _TOL={_TOL} (RMS={rms:.2f}) -- an "
        "IMPROVEMENT; update design.md Decision 2 and this pin"
    )


# 3.5 -- `_compare_or_fail`'s two failure paths, which 8 more keys now depend on and which
# had only ever been driven through the happy path. #713's own review found a real bug in
# this helper (the cross-platform pointer was dead code for the RMS branch), so the paths
# that fire on a genuine cross-platform failure deserve their own coverage.
def test_compare_or_fail_attaches_pointer_on_dimension_mismatch(tmp_path):
    a, b = tmp_path / "a.png", tmp_path / "b.png"
    Image.new("RGB", (40, 40), "white").save(a)
    Image.new("RGB", (50, 50), "white").save(b)
    with pytest.raises(pytest.fail.Exception, match="design.md Decision 3"):
        _compare_or_fail(a, b)


def test_compare_or_fail_attaches_pointer_on_zero_length_baseline(tmp_path):
    a, b = tmp_path / "a.png", tmp_path / "b.png"
    a.write_bytes(b"")
    Image.new("RGB", (40, 40), "white").save(b)
    with pytest.raises(pytest.fail.Exception, match="design.md Decision 3"):
        _compare_or_fail(a, b)


def test_compare_or_fail_attaches_pointer_on_truncated_baseline(tmp_path):
    a, b = tmp_path / "a.png", tmp_path / "b.png"
    # Noise rather than flat white, so the PNG is large enough that truncating it really
    # does cut the image data stream -- a small flat image compresses to a few hundred
    # bytes, where a "truncation" can still contain the whole IDAT chunk and decode fine.
    rng = np.random.default_rng(0)
    Image.fromarray(rng.integers(0, 255, (200, 200, 3), dtype=np.uint8)).save(b)
    a.write_bytes(b.read_bytes()[: len(b.read_bytes()) // 2])
    with pytest.raises(pytest.fail.Exception, match="design.md Decision 3"):
        _compare_or_fail(a, b)
