"""Pixel-level rendering regression tests for the 5 sleap_roots plotting tools (#713).

`test_viz_tools.py` only ever asserted `.is_file()` on a generated PNG -- a dependency
bump (matplotlib, Pillow, numpy) or a refactor that silently changes color mapping, plot
geometry, or layout would ship with every existing assertion still green. This file closes
that gap by comparing each tool's real output against a committed baseline PNG
(`tests/fixtures/plot_baselines/`, generated by `scripts/gen_plot_snapshots_golden.py`)
via `matplotlib.testing.compare.compare_images` -- matplotlib's own image-comparison
utility (used by its own test suite), available with **no new dependency**: Pillow, which
`compare_images` needs to load PNGs, is a hard transitive floor of both `matplotlib` and
`sleap-roots-analyze`, bloommcp's own main dependencies (not an incidental extra), so it
is not at risk of quietly disappearing from the venv.

Tolerance (`_TOL`): `compare_images` scores a pair of images by RMS pixel difference (0 =
bit-identical). Some noise is expected even for a correct render: FreeType hinting differs
slightly across OS/font-stack combinations. **The baselines here were generated on
macOS**, not on Linux (see `plot_baselines/MANIFEST.json` and design.md Decision 3 — Docker
was unavailable to produce a Linux-rendered baseline matching the `python-audit` CI job's
`ubuntu-latest` runner at authoring time), so this test's *first* real cross-platform
comparison is CI's own run, not this docstring's say-so. `_TOL` was picked from a real,
reproducible measurement, not guessed: uniformly dimming the `histograms` baseline by 2%
(`PIL.ImageEnhance.Brightness(0.98)`) against itself scores RMS≈5.6; 5% scores RMS≈12.2;
10% scores RMS≈24.4 (see `test_tolerance_catches_a_real_regression` below, which
reproduces the 10% case live rather than hardcoding these numbers). `_TOL = 15` sits above
the 5%-dim noise floor (leaving headroom for legitimate cross-platform hinting noise,
which manifests as far subtler pixel deltas than a uniform intensity shift) and
comfortably below the 10% case a real color-rendering regression would plausibly produce.
If CI's first real cross-platform run shows the genuine hinting-noise RMS is closer to
`_TOL` than expected, that is the authoritative signal to revisit this constant or
regenerate the baselines from a Linux run -- see `scripts/gen_plot_snapshots_golden.py`'s
module docstring.

Known limitation -- localized regressions, measured per plot type (not just guessed to
generalize from one): RMS is a whole-image average, so a spatially small miscoloring is
diluted across every unaffected pixel, and *how much* it's diluted depends on the plot's
own layout -- a sparse grid with lots of white margin dilutes less than a dense heatmap
where the perturbed region already sat over saturated color. Measured directly (single
fully-recolored square vs. the original baseline, at increasing area fractions):

| baseline               | ~2% area RMS | floor to clear `_TOL=15` |
|------------------------|--------------|---------------------------|
| histograms             | ≈22.0        | <2%                       |
| boxplots               | ≈21.7        | <2%                       |
| variance_decomposition | ≈22.1        | <2%                       |
| heritability_bar       | ≈17.0        | ~2%                       |
| correlation_matrix     | ≈13.7        | ~2.5% (2% alone is NOT caught) |

`correlation_matrix` is the outlier: its heatmap fills most of the frame with already-
saturated color, so a same-area recolor lands a smaller RGB delta than the same recolor
landing on the sparser plots' white margins -- and it is also the tool where a silent
single-cell error is most scientifically consequential (a shifted correlation value a
researcher would act on). `test_tolerance_catches_a_localized_regression` below is
parametrized over both `heritability_bar` (its own ~2% floor) and `correlation_matrix`
(~3%, chosen with real margin above its measured ~2.5% crossing point) so this isn't
asserted only for the tool with the most headroom. A single bar in an ~18-trait bar chart
or a handful of cells in a correlation heatmap both clear their respective floors in
practice, but an even smaller single-cell change is an accepted tradeoff of a whole-image,
"lightweight" tolerance check (the issue's own word) rather than a per-region diff --
catching every possible single-element miscoloring would need a heavier-weight structural
comparison, out of scope here. This table should be re-measured (not assumed to still
hold) after any change to a plot's own color density or layout.

Scope: the 5 dedicated plotting tools only (matching `test_viz_tools.py`'s existing
`_TOOLS` list) -- the optional plot keys `pca_analysis`/`umap_analysis`/`clustering` can
also emit (`create_pca_biplot`, `create_cluster_scatter_pca`, etc.) are a deliberate
non-goal here; see proposal.md.
"""

from __future__ import annotations

import sys
from pathlib import Path

import pytest
from matplotlib.testing.compare import compare_images
from matplotlib.testing.exceptions import ImageComparisonFailure
from PIL import Image, ImageDraw, ImageEnhance

from bloom_mcp.sections.sleap_roots.analysis import (
    plot_correlation_matrix as plot_correlation_matrix_mod,
    plot_heritability_bar as plot_heritability_bar_mod,
    plot_trait_boxplots as plot_trait_boxplots_mod,
    plot_trait_histograms as plot_trait_histograms_mod,
    plot_variance_decomposition as plot_variance_decomposition_mod,
)

_BASELINES = Path(__file__).resolve().parents[1] / "fixtures" / "plot_baselines"
_EXPERIMENT = "turface_19.csv"

# Empirically derived, not guessed -- see the module docstring's Tolerance and Known
# limitation sections (design.md Decisions 2 & 3 have the full measurement + fallback
# plan). Changing this number should come with a fresh measurement, not a vibe.
_TOL = 15

# (label, tool module, tool fn name, produced PNG name, baseline PNG name)
_SNAPSHOT_TOOLS = [
    (
        "histograms",
        plot_trait_histograms_mod,
        "plot_trait_histograms",
        "histograms_turface_19.png",
        "histograms_turface_19_baseline.png",
    ),
    (
        "boxplots",
        plot_trait_boxplots_mod,
        "plot_trait_boxplots",
        "boxplots_turface_19.png",
        "boxplots_turface_19_baseline.png",
    ),
    (
        "correlation_matrix",
        plot_correlation_matrix_mod,
        "plot_correlation_matrix",
        "correlation_matrix_turface_19.png",
        "correlation_matrix_turface_19_baseline.png",
    ),
    (
        "heritability_bar",
        plot_heritability_bar_mod,
        "plot_heritability_bar",
        "heritability_turface_19.png",
        "heritability_turface_19_baseline.png",
    ),
    (
        "variance_decomposition",
        plot_variance_decomposition_mod,
        "plot_variance_decomposition",
        "variance_decomposition_turface_19.png",
        "variance_decomposition_turface_19_baseline.png",
    ),
]
_IDS = [label for label, *_ in _SNAPSHOT_TOOLS]


@pytest.mark.parametrize(
    "_label,module,fn_name,produced_name,baseline_name", _SNAPSHOT_TOOLS, ids=_IDS
)
def test_plot_matches_baseline_within_tolerance(
    _label, module, fn_name, produced_name, baseline_name, viz_env
):
    fn = getattr(module, fn_name)
    result = fn(_EXPERIMENT)
    assert "Plot saved:" in result

    actual = viz_env / produced_name
    baseline = _BASELINES / baseline_name
    assert actual.is_file()
    assert baseline.is_file(), (
        f"missing baseline {baseline} -- run "
        "`uv run --frozen --extra test python scripts/gen_plot_snapshots_golden.py` to create it"
    )

    diff = _compare_or_fail(baseline, actual)
    assert diff is None, diff


def _compare_or_fail(baseline: Path, actual: Path):
    """`compare_images` raises `ImageComparisonFailure` (not a clean result) when the two
    PNGs differ in pixel dimensions -- e.g. if `bbox_inches="tight"` (`_viz_shared.save_plot`)
    produced a different canvas size on this platform than the baseline's, itself a
    plausible symptom of the same cross-platform font-hinting risk `_TOL` is calibrated
    against (design.md Decision 3). Convert that into the same actionable failure shape as
    an over-tolerance RMS, instead of letting a raw exception obscure the diagnosis.
    """
    try:
        return compare_images(str(baseline), str(actual), tol=_TOL)
    except (ImageComparisonFailure, ValueError) as exc:
        pytest.fail(
            f"{exc}\n"
            "If this is a dimension mismatch (not an RMS-over-tolerance message), it may "
            "be a cross-platform bbox_inches='tight' canvas-size difference rather than a "
            "content regression -- see design.md Decision 3 before regenerating baselines."
        )


def test_tolerance_catches_a_real_regression(tmp_path):
    """`_TOL` must not be so loose it rubber-stamps a genuine rendering regression.

    Dims one real baseline by 10% (`PIL.ImageEnhance.Brightness(0.9)`) -- the same
    perturbation the module docstring cites as scoring RMS≈24.4, reproduced live here
    (not hardcoded) so this stays a real assertion against `compare_images`, not a pinned
    magic number. A uniform intensity shift is a stand-in for "a rendering regression
    large enough to matter", not a literal simulation of any specific known bug.
    """
    baseline = _BASELINES / "histograms_turface_19_baseline.png"
    dimmed = ImageEnhance.Brightness(Image.open(baseline)).enhance(0.9)
    perturbed = tmp_path / "dimmed.png"
    dimmed.save(perturbed)

    diff = compare_images(str(baseline), str(perturbed), tol=_TOL)
    assert diff is not None, (
        f"a 10%-dimmed baseline compared equal to itself -- _TOL={_TOL} is too loose "
        "to catch a real regression"
    )


_LOCALIZED_REGRESSION_CASES = [
    # (baseline filename, area fraction) -- fraction chosen per-baseline from the module
    # docstring's measured table, not one number assumed to generalize: correlation_matrix
    # needs ~3% (real margin above its measured ~2.5% crossing point) where the other 4
    # clear _TOL at 2% or less.
    ("heritability_turface_19_baseline.png", 0.02),
    ("correlation_matrix_turface_19_baseline.png", 0.03),
]


@pytest.mark.parametrize(
    "baseline_name,area_fraction",
    _LOCALIZED_REGRESSION_CASES,
    ids=[name.split("_turface")[0] for name, _ in _LOCALIZED_REGRESSION_CASES],
)
def test_tolerance_catches_a_localized_regression(tmp_path, baseline_name, area_fraction):
    """A *global* dim (above) isn't the only regression shape worth proving `_TOL` catches
    -- a single mis-colored element (one bar, one heatmap cell) only touches part of the
    image, and RMS is a whole-image average (see module docstring's "Known limitation").
    Parametrized over `heritability_bar` and `correlation_matrix` specifically (not just
    whichever baseline has the most headroom): `correlation_matrix`'s heatmap fills most
    of the frame with already-saturated color, so it dilutes a same-area recolor less
    than the sparser plots do, and it is the tool where a silent single-cell error is
    most scientifically consequential -- it should not be validated only by proxy via a
    different tool's floor.
    """
    baseline = _BASELINES / baseline_name
    img = Image.open(baseline).convert("RGB")
    w, h = img.size
    perturbed_img = img.copy()
    side = int((w * h * area_fraction) ** 0.5)
    x0, y0 = w // 3, h // 3
    ImageDraw.Draw(perturbed_img).rectangle(
        [x0, y0, x0 + side, y0 + side], fill=(255, 165, 0)
    )
    perturbed = tmp_path / "localized.png"
    perturbed_img.save(perturbed)

    diff = compare_images(str(baseline), str(perturbed), tol=_TOL)
    assert diff is not None, (
        f"a ~{area_fraction * 100:.0f}%-area recolored {baseline_name} compared equal to "
        f"itself -- _TOL={_TOL} is too loose to catch even this deliberately-sized "
        "localized regression"
    )


def test_missing_baseline_fails_with_an_actionable_message(monkeypatch, viz_env):
    monkeypatch.setattr(sys.modules[__name__], "_BASELINES", viz_env / "no_such_dir")
    with pytest.raises(AssertionError, match="gen_plot_snapshots_golden"):
        test_plot_matches_baseline_within_tolerance(
            "histograms",
            plot_trait_histograms_mod,
            "plot_trait_histograms",
            "histograms_turface_19.png",
            "histograms_turface_19_baseline.png",
            viz_env,
        )
