/**
 * The export's 22 metadata cells must equal what bloomctl's `scans.csv` writer
 * produces for the same row (spec: "Trait export metadata matches bloomctl").
 * The fixture's expected cells were generated by bloomctl itself.
 */

import { describe, expect, it } from 'vitest'

import fixture from './__fixtures__/scan-metadata-parity.json'
import {
  METADATA_COLUMNS,
  metadataCells,
  safeComponent,
  scanPath,
  type ScanExtendedRow,
} from './metadata'

type Case = {
  name: string
  row: ScanExtendedRow
  genotype: string | null
  expected: string[]
}
const cases = fixture.cases as unknown as Case[]

describe('METADATA_COLUMNS', () => {
  it("is bloomctl's scans.csv column list, in order", () => {
    expect(METADATA_COLUMNS).toEqual(fixture.columns)
    expect(METADATA_COLUMNS).toHaveLength(22)
  })
})

describe('metadataCells', () => {
  it.each(cases.map((c) => [c.name, c] as const))('matches bloomctl for %s', (_name, c) => {
    expect(metadataCells(c.row, c.genotype)).toEqual(c.expected)
  })
})

describe('scanPath', () => {
  it('renders a zero plant age as Day0, not DayNone', () => {
    const zero = cases.find((c) => c.name === 'age_zero')!
    expect(scanPath(zero.row)).toBe('images/Wave1/Day0_2024-01-18/SOY-W1-001')
  })

  it("renders a NULL age and date as Python's str(None)", () => {
    const age = cases.find((c) => c.name === 'age_null')!
    const date = cases.find((c) => c.name === 'date_scanned_null')!
    expect(scanPath(age.row)).toContain('/DayNone_')
    expect(scanPath(date.row)).toContain('_None/')
  })

  it('uses Wave0 for a NULL wave number', () => {
    const wave = cases.find((c) => c.name === 'wave_number_null')!
    expect(scanPath(wave.row)).toMatch(/^images\/Wave0\//)
  })
})

describe('safeComponent', () => {
  it.each([
    ['', '_'],
    ['.', '_'],
    ['..', '_'],
    ['...', '_'],
    ['a\\b', 'a_b'],
    ['a/b', 'a_b'],
    ['a:b', 'a_b'],
    ['a\u0000b', 'a_b'],
    ['QR-1 ', 'QR-1 '],
    [null, 'None'],
    [0, '0'],
    [12, '12'],
  ])('safeComponent(%j) is %j', (input, out) => {
    expect(safeComponent(input)).toBe(out)
  })
})
