#!/bin/bash
# =============================================================================
# Generate non-secret environment config for GitHub Secrets
# Usage: ./scripts/generate-env-config.sh [prod|staging]
#
# These are configuration values — not cryptographic secrets, but stored
# in GitHub Secrets to keep them out of the repo.
# =============================================================================

set -e

ENV="${1:-prod}"
PREFIX=$(echo "$ENV" | tr '[:lower:]' '[:upper:]')

if [ "$ENV" = "prod" ]; then
  DOMAIN_MAIN="bloom.salk.edu"
  DOMAIN_STUDIO="studio.bloom.salk.edu"
  DOMAIN_MINIO="minio.bloom.salk.edu"
  CADDY_HTTP_LISTEN_PORT="80"
  CADDY_HTTPS_LISTEN_PORT="443"
  CADDY_HTTP_PORT=""
  MINIO_DATA_PATH="/data/bloom/minio"
  SITE_URL="https://${DOMAIN_MAIN}"
  DEPLOY_PATH="/opt/bloom/production"
elif [ "$ENV" = "staging" ]; then
  DOMAIN_MAIN="staging.bloom.salk.edu"
  DOMAIN_STUDIO="staging-studio.bloom.salk.edu"
  DOMAIN_MINIO="staging-minio.bloom.salk.edu"
  CADDY_HTTP_LISTEN_PORT="8080"
  CADDY_HTTPS_LISTEN_PORT="8443"
  CADDY_HTTP_PORT=""
  MINIO_DATA_PATH="/data/bloom/minio-staging"
  SITE_URL="https://${DOMAIN_MAIN}"
  DEPLOY_PATH="/opt/bloom/staging"
fi

echo "=================================================="
echo "Environment config for: $ENV"
echo "Prefix: ${PREFIX}_"
echo "=================================================="
echo ""
echo "Add these to GitHub → Settings → Secrets → Actions:"
echo ""
echo "Secret Name                              | Value"
echo "-----------------------------------------|------"

# Domains
echo "${PREFIX}_DOMAIN_MAIN                     | $DOMAIN_MAIN"
echo "${PREFIX}_DOMAIN_STUDIO                   | $DOMAIN_STUDIO"
echo "${PREFIX}_DOMAIN_MINIO                    | $DOMAIN_MINIO"
# Caddy
echo "${PREFIX}_CADDY_HTTP_LISTEN_PORT           | $CADDY_HTTP_LISTEN_PORT"
echo "${PREFIX}_CADDY_HTTPS_LISTEN_PORT          | $CADDY_HTTPS_LISTEN_PORT"
echo "${PREFIX}_CADDY_HTTP_PORT                  | $CADDY_HTTP_PORT"

# Database
echo "${PREFIX}_POSTGRES_DB                      | postgres"
echo "${PREFIX}_POSTGRES_USER                    | supabase_admin"
echo "${PREFIX}_POSTGRES_PORT                    | 5432"
echo "${PREFIX}_POSTGRES_HOST                    | db-prod"
echo "${PREFIX}_PGRST_DB_SCHEMAS                 | public,auth,storage"

# Service ports
echo "${PREFIX}_KONG_PORT                        | 8000"
echo "${PREFIX}_BLOOM_WEB_PORT                   | 3000"
echo "${PREFIX}_STUDIO_PORT                      | 3000"
echo "${PREFIX}_MINIO_CONSOLE_PORT               | 9001"

# Pooler
echo "${PREFIX}_POOLER_TENANT_ID                 | default"
echo "${PREFIX}_POOLER_DEFAULT_POOL_SIZE          | 5"
echo "${PREFIX}_POOLER_MAX_CLIENT_CONN            | 100"
echo "${PREFIX}_POOLER_DB_POOL_SIZE               | 10"

# Dashboard
echo "${PREFIX}_DASHBOARD_USERNAME                | admin"
# DASHBOARD_PASSWORD is a secret — generated by generate-secrets.sh

# Studio
echo "${PREFIX}_STUDIO_DEFAULT_ORGANIZATION       | Bloom"
echo "${PREFIX}_STUDIO_DEFAULT_PROJECT             | default"
echo "${PREFIX}_STUDIO_SUPABASE_PUBLIC_URL         | https://${DOMAIN_STUDIO}"

# MinIO
echo "${PREFIX}_MINIO_ROOT_USER                   | supabase"
echo "${PREFIX}_MINIO_DATA_PATH                   | $MINIO_DATA_PATH"
echo "${PREFIX}_MINIO_BROWSER_REDIRECT_URL         | https://${DOMAIN_MINIO}"

# URLs
echo "${PREFIX}_SITE_URL                          | $SITE_URL"
echo "${PREFIX}_API_EXTERNAL_URL                  | ${SITE_URL}/api"
echo "${PREFIX}_ADDITIONAL_REDIRECT_URLS           | $SITE_URL"
echo "${PREFIX}_NEXT_PUBLIC_SUPABASE_URL           | ${SITE_URL}/api"
echo "${PREFIX}_NEXT_PUBLIC_APP_URL                | $SITE_URL"
echo "${PREFIX}_SUPABASE_URL                      | http://kong:8000"
echo "${PREFIX}_SUPABASE_PUBLIC_URL                | ${SITE_URL}/api"
echo "${PREFIX}_SUPABASE_COOKIE_NAME               | sb-bloom-auth-token"
echo "${PREFIX}_IMGPROXY_URL                      | http://imgproxy:5001"
echo "${PREFIX}_IMGPROXY_ENABLE_WEBP_DETECTION     | true"

# Auth
echo "${PREFIX}_ENABLE_ANONYMOUS_USERS             | false"
echo "${PREFIX}_ENABLE_EMAIL_SIGNUP                | true"
echo "${PREFIX}_ENABLE_EMAIL_AUTOCONFIRM           | true"
echo "${PREFIX}_DISABLE_SIGNUP                     | false"
echo "${PREFIX}_JWT_EXPIRY                         | 3600"

# Bloom app
echo "${PREFIX}_BLOOM_PLOTS_DIR                    | /app/data/PLOTS_DIR"
echo "${PREFIX}_BLOOM_PLOTS_URL                    | ${SITE_URL}/plots"
# BLOOMMCP_API_KEY is a secret — generated by generate-secrets.sh
echo "${PREFIX}_BLOOM_MCP_URL                      | http://bloommcp:8811/mcp"
echo "${PREFIX}_CORS_ORIGINS                       | $SITE_URL"
echo "${PREFIX}_OPENAI_API_KEY                     | sk-placeholder"

# LangChain
echo "${PREFIX}_LANGCHAIN_TRACING_V2               | false"
echo "${PREFIX}_LANGCHAIN_API_KEY                  | "
echo "${PREFIX}_LANGCHAIN_PROJECT                  | bloom-${ENV}"

# Deploy
echo "${PREFIX}_DEPLOY_PATH                        | $DEPLOY_PATH"

echo ""
echo "=================================================="
echo "Total: ~45 config values"
echo "Run ./scripts/generate-secrets.sh $ENV for the 9 secret keys"
echo "=================================================="
