"""Keep _WIKI/SUPABASE/erd.md: the tbls ER diagram of the public schema.

Subcommands:
  wrap   read tbls mermaid output on stdin; print erd.md (a generated-by comment and
         one mermaid block, which GitHub renders with zoom and pan)
  guard  read `version|name` rows from supabase_migrations.schema_migrations on stdin;
         exit 1 when they differ from the checkout's migration files, because a
         diagram drawn from that database would not match what CI generates
  tables print the tbls --table list for a PR snapshot, from --tables a,b or from the
         tables the branch's migration changes touch (--changed BASE)
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import Iterable

sys.path.insert(0, str(Path(__file__).resolve().parent))

from migration_changes import RefError, changed_facts  # noqa: E402

HEADER = (
    "<!-- Generated by tbls from a database built by applying every migration. "
    "Do not edit: run `make erd`, or commit the erd artifact from this branch's CI run. -->"
)


def wrap(mermaid: str) -> str:
    lines = [line.rstrip() for line in mermaid.splitlines()]
    while lines and not lines[0]:
        lines.pop(0)
    while lines and not lines[-1]:
        lines.pop()
    return f"{HEADER}\n\n```mermaid\n" + "\n".join(lines) + "\n```\n"


def parse_migration_file(filename: str) -> tuple[str, str]:
    """`20250617163449_insert_image_2.0_rpc.sql` -> (`20250617163449`, `insert_image_2.0_rpc`)."""
    stem = filename[: -len(".sql")] if filename.endswith(".sql") else filename
    version, _, name = stem.partition("_")
    return version, name


def mismatches(recorded: list[tuple[str, str]], files: list[str]) -> list[str]:
    """Differences between applied migrations and the checkout's files, one message each."""
    on_disk = dict(parse_migration_file(f) for f in files)
    in_db = dict(recorded)
    problems = []
    for version in sorted(set(on_disk) | set(in_db)):
        if version not in on_disk:
            problems.append(f"{version} ({in_db[version]}) is applied to the dev database but has no file here")
        elif version not in in_db:
            problems.append(f"{version} ({on_disk[version]}) is in the checkout but not applied to the dev database")
        elif on_disk[version] != in_db[version]:
            problems.append(
                f"{version} is recorded as {in_db[version]!r} but the checkout has {on_disk[version]!r}"
            )
    return problems


def _guard(migrations_dir: Path) -> int:
    recorded = [
        tuple(line.split("|", 1)) for line in sys.stdin.read().splitlines() if "|" in line
    ]
    if not recorded:
        print(
            "No migration rows were read from the dev database (did psql fail, or is it "
            "unmigrated?). Nothing written.",
            file=sys.stderr,
        )
        return 1
    files = sorted(p.name for p in migrations_dir.glob("*.sql"))
    problems = mismatches(recorded, files)
    if not problems:
        return 0
    print("The dev database does not match this checkout, so its diagram would differ from CI's:", file=sys.stderr)
    for problem in problems:
        print(f"  {problem}", file=sys.stderr)
    print(
        "Commit the erd artifact from this branch's CI run instead, "
        "or reset with `make rebuild-dev-fresh` and `make migrate-local`.",
        file=sys.stderr,
    )
    return 1


def qualify(names: Iterable[str]) -> str:
    """The tbls --table list: bare names are public tables."""
    return ",".join(name if "." in name else f"public.{name}" for name in names)


def changed_tables(
    base: str,
    head: str = "HEAD",
    staging_ref: str = "origin/staging",
    repo: Path = Path("."),
) -> list[str]:
    """Tables the branch's migration changes create, structurally alter or rename."""
    return sorted(changed_facts(base, head, staging_ref, repo).tables_touched)


def _tables(args: argparse.Namespace) -> int:
    if args.tables:
        names = [name.strip() for name in args.tables.split(",") if name.strip()]
    else:
        try:
            names = changed_tables(args.changed, args.head, args.staging_ref, Path(args.repo))
        except RefError as exc:
            print(f"Cannot compare with {args.changed}: {exc}", file=sys.stderr)
            return 2
    if not names:
        print("This branch's migrations change no table; pass TABLES=… instead.", file=sys.stderr)
        return 1
    print(qualify(names))
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    sub = parser.add_subparsers(dest="command", required=True)
    sub.add_parser("wrap")
    guard = sub.add_parser("guard")
    guard.add_argument("--migrations-dir", type=Path, default=Path("supabase/migrations"))
    tables = sub.add_parser("tables")
    source = tables.add_mutually_exclusive_group(required=True)
    source.add_argument("--tables", help="comma-separated table names")
    source.add_argument("--changed", metavar="BASE", help="use the tables this branch's migrations touch")
    tables.add_argument("--head", default="HEAD")
    tables.add_argument("--staging-ref", default="origin/staging")
    tables.add_argument("--repo", default=".")
    args = parser.parse_args(argv)

    if args.command == "wrap":
        sys.stdout.write(wrap(sys.stdin.read()))
        return 0
    if args.command == "tables":
        return _tables(args)
    return _guard(args.migrations_dir)


if __name__ == "__main__":
    sys.exit(main())
