#!/usr/bin/env bash
# =============================================================================
# Bloom v2 - Secure Environment File Generator
#
# Usage:
#   ./scripts/setup-env.sh dev          Generate .env.dev with secure secrets
#   ./scripts/setup-env.sh prod         Generate .env.prod with secure secrets
#   ./scripts/setup-env.sh prod --trial Generate .env.prod with TEST credentials
#   ./scripts/setup-env.sh prod --force Overwrite existing .env.prod
# =============================================================================

set -euo pipefail

# --- Colors ---
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

info()  { echo -e "${BLUE}[INFO]${NC} $1"; }
warn()  { echo -e "${YELLOW}[WARN]${NC} $1"; }
ok()    { echo -e "${GREEN}[OK]${NC} $1"; }
err()   { echo -e "${RED}[ERROR]${NC} $1" >&2; }

# --- Parse arguments ---
ENV_MODE=""
TRIAL=false
FORCE=false

for arg in "$@"; do
  case "$arg" in
    dev|prod) ENV_MODE="$arg" ;;
    --trial)  TRIAL=true ;;
    --force)  FORCE=true ;;
    -h|--help)
      echo "Usage: $0 <dev|prod> [--trial] [--force]"
      echo ""
      echo "  dev       Generate .env.dev"
      echo "  prod      Generate .env.prod"
      echo "  --trial   Use test credentials (clearly marked non-production)"
      echo "  --force   Overwrite existing env file"
      exit 0
      ;;
    *) err "Unknown argument: $arg"; exit 1 ;;
  esac
done

if [[ -z "$ENV_MODE" ]]; then
  err "Usage: $0 <dev|prod> [--trial] [--force]"
  exit 1
fi

# --- Determine output file ---
if [[ "$ENV_MODE" == "dev" ]]; then
  ENV_FILE=".env.dev"
else
  ENV_FILE=".env.prod"
fi

# --- Check if file exists ---
if [[ -f "$ENV_FILE" && "$FORCE" == false ]]; then
  err "$ENV_FILE already exists. Use --force to overwrite."
  exit 1
fi

# --- Generate secrets ---
gen_secret()  { openssl rand -base64 "$1" 2>/dev/null | tr -d '\n'; }
gen_hex()     { openssl rand -hex "$1" 2>/dev/null | tr -d '\n'; }
gen_alnum()   { openssl rand -base64 48 2>/dev/null | tr -dc 'a-zA-Z0-9' | head -c "$1"; }

if [[ "$TRIAL" == true ]]; then
  info "Generating TRIAL (test) credentials — NOT for production use"
  JWT_SECRET="trial-jwt-secret-$(gen_alnum 32)"
  POSTGRES_PASSWORD="trial-pg-$(gen_alnum 24)"
  MINIO_ROOT_PASSWORD="trial-minio-$(gen_alnum 24)"
  DASHBOARD_PASSWORD="trial-dash-$(gen_alnum 16)"
  BLOOMMCP_API_KEY="trial-mcp-$(gen_alnum 24)"
  VAULT_ENC_KEY="trial-vault-$(gen_alnum 32)"
  SUPAVISOR_ENC_KEY="$(gen_hex 32)"
  SECRET_KEY_BASE="$(gen_hex 64)"
  DB_ENC_KEY="trial-dbenc-$(gen_alnum 32)"
  LOGFLARE_PUBLIC_TOKEN="trial-logflare-pub-$(gen_alnum 16)"
  LOGFLARE_PRIVATE_TOKEN="trial-logflare-priv-$(gen_alnum 16)"
else
  info "Generating cryptographically secure credentials"
  JWT_SECRET="$(gen_secret 48)"
  POSTGRES_PASSWORD="$(gen_alnum 32)"
  MINIO_ROOT_PASSWORD="$(gen_alnum 32)"
  DASHBOARD_PASSWORD="$(gen_alnum 24)"
  BLOOMMCP_API_KEY="$(gen_alnum 32)"
  VAULT_ENC_KEY="$(gen_secret 48)"
  SUPAVISOR_ENC_KEY="$(gen_hex 32)"
  SECRET_KEY_BASE="$(gen_hex 64)"
  DB_ENC_KEY="$(gen_secret 32)"
  LOGFLARE_PUBLIC_TOKEN="$(gen_alnum 24)"
  LOGFLARE_PRIVATE_TOKEN="$(gen_alnum 24)"
fi

# --- Set env-specific values ---
if [[ "$ENV_MODE" == "dev" ]]; then
  DOMAIN_MAIN="localhost"
  DOMAIN_STUDIO="studio.localhost"
  DOMAIN_MINIO="minio.localhost"
  DOMAIN_FLASK="flask.localhost"
  SITE_URL="http://localhost"
  NEXT_PUBLIC_SUPABASE_URL="http://localhost/api"
  NEXT_PUBLIC_APP_URL="http://localhost"
  API_EXTERNAL_URL="http://localhost/api"
  SUPABASE_URL="http://kong:8000"
  STUDIO_SUPABASE_PUBLIC_URL="http://localhost/api"
  SUPABASE_COOKIE_NAME="sb-localhost-auth-token"
  POSTGRES_HOST="db-dev"
  MINIO_DATA_PATH="./minio/data"
  BLOOM_PLOTS_URL="http://localhost/plots"
  IMGPROXY_URL="http://imgproxy:5001"
else
  DOMAIN_MAIN="bloom.salk.edu"
  DOMAIN_STUDIO="studio.bloom.salk.edu"
  DOMAIN_MINIO="minio.bloom.salk.edu"
  DOMAIN_FLASK="flask.bloom.salk.edu"
  SITE_URL="https://bloom.salk.edu"
  NEXT_PUBLIC_SUPABASE_URL="https://bloom.salk.edu/api"
  NEXT_PUBLIC_APP_URL="https://bloom.salk.edu"
  API_EXTERNAL_URL="https://bloom.salk.edu/api"
  SUPABASE_URL="http://kong:8000"
  STUDIO_SUPABASE_PUBLIC_URL="https://bloom.salk.edu/api"
  SUPABASE_COOKIE_NAME="sb-bloom-salk-edu-auth-token"
  POSTGRES_HOST="db-prod"
  MINIO_DATA_PATH="/data/bloom/minio"
  BLOOM_PLOTS_URL="https://bloom.salk.edu/plots"
  IMGPROXY_URL="http://imgproxy:5001"
fi

# --- Write env file ---
TRIAL_BANNER=""
if [[ "$TRIAL" == true ]]; then
  TRIAL_BANNER="# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
# !! TRIAL/TEST CREDENTIALS — DO NOT USE IN PRODUCTION         !!
# !! Generated by: scripts/setup-env.sh $ENV_MODE --trial      !!
# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
"
fi

cat > "$ENV_FILE" <<EOF
${TRIAL_BANNER}# =============================================================================
# Bloom v2 Environment Configuration ($ENV_MODE)
# Generated: $(date -u '+%Y-%m-%d %H:%M:%S UTC')
# =============================================================================

# --- JWT & Authentication ---
JWT_SECRET=${JWT_SECRET}
JWT_EXPIRY=3600

# IMPORTANT: You must generate ANON_KEY and SERVICE_ROLE_KEY from your JWT_SECRET.
# Use: https://supabase.com/docs/guides/self-hosting#api-keys
# Or run: python3 scripts/generateJWT_key.py
ANON_KEY=GENERATE_FROM_JWT_SECRET
SERVICE_ROLE_KEY=GENERATE_FROM_JWT_SECRET

# --- Cookie ---
SUPABASE_COOKIE_NAME=${SUPABASE_COOKIE_NAME}

# --- Database ---
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
POSTGRES_DB=postgres
POSTGRES_PORT=5432
POSTGRES_HOST=${POSTGRES_HOST}
POSTGRES_USER=supabase_admin

# --- LangChain ---
LANGCHAIN_POSTGRES_URL=postgresql://supabase_admin:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:5432/postgres
LANGCHAIN_TRACING_V2=false
LANGCHAIN_API_KEY=
LANGCHAIN_PROJECT=bloom-langchain

# --- URLs ---
SITE_URL=${SITE_URL}
NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
NEXT_PUBLIC_APP_URL=${NEXT_PUBLIC_APP_URL}
API_EXTERNAL_URL=${API_EXTERNAL_URL}
SUPABASE_URL=${SUPABASE_URL}
STUDIO_SUPABASE_PUBLIC_URL=${STUDIO_SUPABASE_PUBLIC_URL}
BLOOM_PLOTS_URL=${BLOOM_PLOTS_URL}

# --- Domains ---
DOMAIN_MAIN=${DOMAIN_MAIN}
DOMAIN_STUDIO=${DOMAIN_STUDIO}
DOMAIN_MINIO=${DOMAIN_MINIO}
DOMAIN_FLASK=${DOMAIN_FLASK}

# --- MinIO ---
MINIO_ROOT_USER=admin
MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
MINIO_DATA_PATH=${MINIO_DATA_PATH}

# --- Dashboard ---
DASHBOARD_USERNAME=admin
DASHBOARD_PASSWORD=${DASHBOARD_PASSWORD}

# --- Encryption Keys ---
DB_ENC_KEY=${DB_ENC_KEY}
VAULT_ENC_KEY=${VAULT_ENC_KEY}
SUPAVISOR_ENC_KEY=${SUPAVISOR_ENC_KEY}
SECRET_KEY_BASE=${SECRET_KEY_BASE}

# --- Bloom MCP ---
BLOOMMCP_API_KEY=${BLOOMMCP_API_KEY}

# --- OpenAI (Studio only) ---
# OPENAI_API_KEY is only used by Supabase Studio's optional AI assistant

# --- Logflare/Analytics ---
LOGFLARE_PUBLIC_ACCESS_TOKEN=${LOGFLARE_PUBLIC_TOKEN}
LOGFLARE_PRIVATE_ACCESS_TOKEN=${LOGFLARE_PRIVATE_TOKEN}

# --- Supabase Services ---
ADDITIONAL_REDIRECT_URLS=
DISABLE_SIGNUP=false
ENABLE_EMAIL_SIGNUP=true
ENABLE_EMAIL_AUTOCONFIRM=true
ENABLE_ANONYMOUS_USERS=false
PGRST_DB_SCHEMAS=public,storage,graphql_public
IMGPROXY_ENABLE_WEBP_DETECTION=false
IMGPROXY_URL=${IMGPROXY_URL}

# --- Studio ---
STUDIO_DEFAULT_ORGANIZATION=Bloom
STUDIO_DEFAULT_PROJECT=Bloom

# --- Connection Pooler ---
POOLER_TENANT_ID=default
POOLER_DEFAULT_POOL_SIZE=20
POOLER_MAX_CLIENT_CONN=100
POOLER_DB_POOL_SIZE=10

# --- Plots Directory ---
BLOOM_PLOTS_DIR=/app/data/PLOTS_DIR
EOF

# --- Set permissions ---
chmod 600 "$ENV_FILE"
ok "$ENV_FILE generated with secure permissions (600)"

# --- Post-generation instructions ---
echo ""
echo "=============================================="
echo " NEXT STEPS"
echo "=============================================="
echo ""
echo "1. Generate ANON_KEY and SERVICE_ROLE_KEY:"
echo "   - Go to: https://supabase.com/docs/guides/self-hosting#api-keys"
echo "   - Use your JWT_SECRET to generate both keys"
echo "   - Update $ENV_FILE with the generated values"
echo ""
if [[ "$TRIAL" == false ]]; then
  echo "2. Add external API keys to $ENV_FILE (optional):"
  echo "   - LANGCHAIN_API_KEY (optional, for tracing)"
  echo ""
  echo "3. Verify domain configuration:"
  echo "   - DOMAIN_MAIN=${DOMAIN_MAIN}"
  echo "   - DOMAIN_STUDIO=${DOMAIN_STUDIO}"
  echo "   - DOMAIN_MINIO=${DOMAIN_MINIO}"
  echo ""
  echo "4. Verify MinIO data path exists:"
  echo "   - mkdir -p ${MINIO_DATA_PATH}"
  echo "   - chmod 755 ${MINIO_DATA_PATH}"
  echo ""
fi
echo "Run 'scripts/pre-deploy-check.sh' to validate before deployment."
echo ""
