-- SINGLE SOURCE OF TRUTH for bloom_* schema-level USAGE grants (issue #333).
--
-- Keep this file updated whenever a bloom_* role needs USAGE on a new schema, and
-- apply it as `supabase_admin` (the owner of schemas storage/auth, a superuser).
--
-- WHEN / HOW TO APPLY
--   * Local (fresh or ongoing): `make migrate-local` (and `make verify-dev`) run
--     this automatically after `supabase db push`.
--   * CI: the `compose-health-check` job applies it after migrations.
--   * Ongoing prod / staging: apply manually when grants change, e.g.
--       docker compose -f docker-compose.prod.yml exec -T db \
--         psql -v ON_ERROR_STOP=1 -U supabase_admin -d postgres \
--         < supabase/grants/schema_grants.sql
--   Run it AFTER migrations have created the bloom_* roles (it grants directly, so
--   a missing role raises rather than skipping).
--
-- WHY THIS IS A STANDALONE FILE, NOT A MIGRATION
-- `supabase db push` applies migrations after `SET SESSION ROLE postgres`, which is
-- neither a superuser nor the owner of storage/auth, so `GRANT USAGE ON SCHEMA ...`
-- inside a migration silently no-ops ("WARNING: no privileges were granted") and
-- bloom_agent ends up unable to resolve storage.objects. Applied as supabase_admin
-- (outside the db-push role downgrade) the grant sticks. A CI guard
-- (tests/unit/test_schema_usage_grants.py) blocks raw GRANT/REVOKE ... ON SCHEMA
-- (auth|storage) in supabase/migrations/ so this stays the one place they live.
--
-- MUST be run as supabase_admin: applied as postgres these grants silently no-op.
-- Idempotent (GRANT USAGE is idempotent; safe to re-run). scripts/check_health.py
-- parses this file and asserts every pair below is actually granted.
--
-- auth USAGE is granted to bloom_writer ONLY. The auth-schema gap for
-- bloom_user/admin/agent is #341's intentional read-only gap — do not add them here
-- without that review.

GRANT USAGE ON SCHEMA storage TO bloom_user, bloom_admin, bloom_agent, bloom_writer;
GRANT USAGE ON SCHEMA auth TO bloom_writer;
