CREATE TABLE species (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    common_name TEXT,
    genus TEXT,
    species TEXT
);

ALTER TABLE species ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Authenticated users can insert species" ON species;
CREATE POLICY "Authenticated users can insert species"
ON species AS permissive
FOR INSERT TO authenticated
WITH CHECK (true);

DROP POLICY IF EXISTS "Authenticated users can select species" ON species;
CREATE POLICY "Authenticated users can select species"
ON species AS permissive
FOR SELECT TO authenticated
USING (true);

DROP POLICY IF EXISTS "Authenticated users can update species" ON species;
CREATE POLICY "Authenticated users can update species"
ON species AS permissive
FOR UPDATE TO authenticated
USING (true);

DROP POLICY IF EXISTS "Authenticated users can delete species" ON species;
CREATE POLICY "Authenticated users can delete species"
ON species AS permissive
FOR DELETE TO authenticated
USING (true);