CREATE TABLE translation_projects (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT UNIQUE NOT NULL,
    spreadsheet_url TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE translation_projects ENABLE ROW LEVEL SECURITY;

-- DROP POLICY IF EXISTS "Authenticated users can insert translation_projects" ON translation_projects;
-- CREATE POLICY "Authenticated users can insert translation_projects"
-- ON translation_projects AS permissive
-- FOR INSERT TO authenticated
-- WITH CHECK (true);

-- DROP POLICY IF EXISTS "Authenticated users can select translation_projects" ON translation_projects;
-- CREATE POLICY "Authenticated users can select translation_projects"
-- ON translation_projects AS permissive
-- FOR SELECT TO authenticated
-- USING (true);

-- DROP POLICY IF EXISTS "Authenticated users can update translation_projects" ON translation_projects;
-- CREATE POLICY "Authenticated users can update translation_projects"
-- ON translation_projects AS permissive
-- FOR UPDATE TO authenticated
-- USING (true);

-- DROP POLICY IF EXISTS "Authenticated users can delete translation_projects" ON translation_projects;
-- CREATE POLICY "Authenticated users can delete translation_projects"
-- ON translation_projects AS permissive
-- FOR DELETE TO authenticated
-- USING (true);
