CREATE TABLE phenotypers (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    first_name TEXT,
    last_name TEXT,
    email TEXT,
    user_id UUID REFERENCES auth.users(id)
);

ALTER TABLE phenotypers ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Authenticated users can insert phenotypers" ON phenotypers;
CREATE POLICY "Authenticated users can insert phenotypers"
ON phenotypers AS permissive
FOR INSERT TO authenticated
WITH CHECK (true);

DROP POLICY IF EXISTS "Authenticated users can select phenotypers" ON phenotypers;
CREATE POLICY "Authenticated users can select phenotypers"
ON phenotypers AS permissive
FOR SELECT TO authenticated
USING (true);

DROP POLICY IF EXISTS "Authenticated users can update phenotypers" ON phenotypers;
CREATE POLICY "Authenticated users can update phenotypers"
ON phenotypers AS permissive
FOR UPDATE TO authenticated
USING (true);

DROP POLICY IF EXISTS "Authenticated users can delete phenotypers" ON phenotypers;
CREATE POLICY "Authenticated users can delete phenotypers"
ON phenotypers AS permissive
FOR DELETE TO authenticated
USING (true);
