CREATE TABLE cyl_scans (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    plant_id BIGINT REFERENCES cyl_plants(id),
    date_scanned TIMESTAMPTZ,
    scanner_id BIGINT REFERENCES cyl_scanners(id),
    phenotyper_id BIGINT REFERENCES phenotypers(id),
    plant_age_days INT
);

ALTER TABLE cyl_scans ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Authenticated users can insert cyl_scans" ON cyl_scans;
CREATE POLICY "Authenticated users can insert cyl_scans"
ON cyl_scans AS permissive
FOR INSERT TO authenticated
WITH CHECK (true);

DROP POLICY IF EXISTS "Authenticated users can select cyl_scans" ON cyl_scans;
CREATE POLICY "Authenticated users can select cyl_scans"
ON cyl_scans AS permissive
FOR SELECT TO authenticated
USING (true);

DROP POLICY IF EXISTS "Authenticated users can update cyl_scans" ON cyl_scans;
CREATE POLICY "Authenticated users can update cyl_scans"
ON cyl_scans AS permissive
FOR UPDATE TO authenticated
USING (true);

DROP POLICY IF EXISTS "Authenticated users can delete cyl_scans" ON cyl_scans;
CREATE POLICY "Authenticated users can delete cyl_scans"
ON cyl_scans AS permissive
FOR DELETE TO authenticated
USING (true);