CREATE TABLE cyl_plants (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    qr_code TEXT,
    wave_id BIGINT REFERENCES cyl_waves(id),
    germ_day INT,
    germ_day_color TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE cyl_plants ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Authenticated users can insert cyl_plants" ON cyl_plants;
CREATE POLICY "Authenticated users can insert cyl_plants"
ON cyl_plants AS permissive
FOR INSERT TO authenticated
WITH CHECK (true);

DROP POLICY IF EXISTS "Authenticated users can select cyl_plants" ON cyl_plants;
CREATE POLICY "Authenticated users can select cyl_plants"
ON cyl_plants AS permissive
FOR SELECT TO authenticated
USING (true);

DROP POLICY IF EXISTS "Authenticated users can update cyl_plants" ON cyl_plants;
CREATE POLICY "Authenticated users can update cyl_plants"
ON cyl_plants AS permissive
FOR UPDATE TO authenticated
USING (true);

DROP POLICY IF EXISTS "Authenticated users can delete cyl_plants" ON cyl_plants;
CREATE POLICY "Authenticated users can delete cyl_plants"
ON cyl_plants AS permissive
FOR DELETE TO authenticated
USING (true);