CREATE TABLE accessions (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Consider adding: pi_number, variety_name / cultivar_name

ALTER TABLE accessions ADD CONSTRAINT name_uniqueness UNIQUE (name);

ALTER TABLE accessions ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Authenticated users can insert accessions" ON accessions;
CREATE POLICY "Authenticated users can insert accessions"
ON accessions AS permissive
FOR INSERT TO authenticated
WITH CHECK (true);

DROP POLICY IF EXISTS "Authenticated users can select accessions" ON accessions;
CREATE POLICY "Authenticated users can select accessions"
ON accessions AS permissive
FOR SELECT TO authenticated
USING (true);

DROP POLICY IF EXISTS "Authenticated users can update accessions" ON accessions;
CREATE POLICY "Authenticated users can update accessions"
ON accessions AS permissive
FOR UPDATE TO authenticated
USING (true);

DROP POLICY IF EXISTS "Authenticated users can delete accessions" ON accessions;
CREATE POLICY "Authenticated users can delete accessions"
ON accessions AS permissive
FOR DELETE TO authenticated
USING (true);
