CREATE TABLE cyl_scanners (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT
);

ALTER TABLE cyl_scanners ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Authenticated users can insert cyl_scanners" ON cyl_scanners;
CREATE POLICY "Authenticated users can insert cyl_scanners"
ON cyl_scanners AS permissive
FOR INSERT TO authenticated
WITH CHECK (true);

DROP POLICY IF EXISTS "Authenticated users can select cyl_scanners" ON cyl_scanners;
CREATE POLICY "Authenticated users can select cyl_scanners"
ON cyl_scanners AS permissive
FOR SELECT TO authenticated
USING (true);

DROP POLICY IF EXISTS "Authenticated users can update cyl_scanners" ON cyl_scanners;
CREATE POLICY "Authenticated users can update cyl_scanners"
ON cyl_scanners AS permissive
FOR UPDATE TO authenticated
USING (true);

DROP POLICY IF EXISTS "Authenticated users can delete cyl_scanners" ON cyl_scanners;
CREATE POLICY "Authenticated users can delete cyl_scanners"
ON cyl_scanners AS permissive
FOR DELETE TO authenticated
USING (true);
