CREATE TABLE cyl_waves (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    experiment_id BIGINT REFERENCES cyl_experiments(id),
    number INT,
    name TEXT
);

ALTER TABLE cyl_waves ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Authenticated users can insert cyl_waves" ON cyl_waves;
CREATE POLICY "Authenticated users can insert cyl_waves"
ON cyl_waves AS permissive
FOR INSERT TO authenticated
WITH CHECK (true);

DROP POLICY IF EXISTS "Authenticated users can select cyl_waves" ON cyl_waves;
CREATE POLICY "Authenticated users can select cyl_waves"
ON cyl_waves AS permissive
FOR SELECT TO authenticated
USING (true);

DROP POLICY IF EXISTS "Authenticated users can update cyl_waves" ON cyl_waves;
CREATE POLICY "Authenticated users can update cyl_waves"
ON cyl_waves AS permissive
FOR UPDATE TO authenticated
USING (true);

DROP POLICY IF EXISTS "Authenticated users can delete cyl_waves" ON cyl_waves;
CREATE POLICY "Authenticated users can delete cyl_waves"
ON cyl_waves AS permissive
FOR DELETE TO authenticated
USING (true);