CREATE TABLE cyl_images (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    scan_id BIGINT REFERENCES cyl_scans(id),
    -- object_id UUID REFERENCES storage.objects(id),
    object_path TEXT,
    frame_number INT,
    date_scanned TIMESTAMPTZ
);

-- It might be better to have an object_id column that references storage.objects(id)
-- However, that will probably require more work to get the object_id from the storage API

ALTER TABLE cyl_images ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Authenticated users can insert cyl_images" ON cyl_images;
CREATE POLICY "Authenticated users can insert cyl_images"
ON cyl_images AS permissive
FOR INSERT TO authenticated
WITH CHECK (true);

DROP POLICY IF EXISTS "Authenticated users can select cyl_images" ON cyl_images;
CREATE POLICY "Authenticated users can select cyl_images"
ON cyl_images AS permissive
FOR SELECT TO authenticated
USING (true);

DROP POLICY IF EXISTS "Authenticated users can update cyl_images" ON cyl_images;
CREATE POLICY "Authenticated users can update cyl_images"
ON cyl_images AS permissive
FOR UPDATE TO authenticated
USING (true);

DROP POLICY IF EXISTS "Authenticated users can delete cyl_images" ON cyl_images;
CREATE POLICY "Authenticated users can delete cyl_images"
ON cyl_images AS permissive
FOR DELETE TO authenticated
USING (true);