CREATE TABLE cyl_scan_traits (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    scan_id BIGINT NOT NULL REFERENCES cyl_scans(id),
    name TEXT NOT NULL,
    value REAL
);

ALTER TABLE cyl_scan_traits ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Authenticated users can select cyl_scan_traits" ON cyl_scan_traits;
CREATE POLICY "Authenticated users can select cyl_scan_traits"
ON cyl_scan_traits AS permissive
FOR SELECT TO authenticated
USING (true);
