CREATE TABLE translation_project_users (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    translation_project_id BIGINT REFERENCES translation_projects (id) ON DELETE CASCADE
);

ALTER TABLE translation_project_users ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Authenticated users can select translation_project_users" ON translation_project_users;
CREATE POLICY "Authenticated users can select translation_project_users"
ON translation_project_users AS permissive
FOR SELECT TO authenticated
USING ( auth.uid() = user_id );

DROP POLICY IF EXISTS "Permitted users can select translation_projects" ON translation_projects;
CREATE POLICY "Permitted users can select translation_projects"
ON translation_projects AS permissive
FOR SELECT TO authenticated
USING (
  id IN (
    SELECT translation_project_id
    FROM translation_project_users
    WHERE user_id = auth.uid()
  )    
);


-- DROP POLICY IF EXISTS "Authenticated users can insert translation_project_users" ON translation_project_users;
-- CREATE POLICY "Authenticated users can insert translation_project_users"
-- ON translation_project_users AS permissive
-- FOR INSERT TO authenticated
-- WITH CHECK (true);

-- DROP POLICY IF EXISTS "Authenticated users can update translation_project_users" ON translation_project_users;
-- CREATE POLICY "Authenticated users can update translation_project_users"
-- ON translation_project_users AS permissive
-- FOR UPDATE TO authenticated
-- USING (true);

-- DROP POLICY IF EXISTS "Authenticated users can delete translation_project_users" ON translation_project_users;
-- CREATE POLICY "Authenticated users can delete translation_project_users"
-- ON translation_project_users AS permissive
-- FOR DELETE TO authenticated
-- USING (true);