CREATE TABLE cyl_image_traits (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    image_id BIGINT NOT NULL REFERENCES cyl_images(id),
    name TEXT NOT NULL,
    value REAL
);

ALTER TABLE cyl_image_traits ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Authenticated users can select cyl_image_traits" ON cyl_image_traits;
CREATE POLICY "Authenticated users can select cyl_image_traits"
ON cyl_image_traits AS permissive
FOR SELECT TO authenticated
USING (true);
