-- create the scrna_genes table
CREATE TABLE scrna_genes (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    dataset_id BIGINT REFERENCES scrna_datasets(id) NOT NULL,
    gene_number INT NOT NULL,
    gene_name TEXT NOT NULL
);

-- set up RLS
ALTER TABLE scrna_genes ENABLE ROW LEVEL SECURITY;

-- grant permissions
DROP POLICY IF EXISTS "Authenticated users can select scrna_genes" ON scrna_genes;
CREATE POLICY "Authenticated users can select scrna_genes"
ON scrna_genes AS permissive
FOR SELECT TO authenticated
USING (true);
