-- Creating table 'translation_candidates'
CREATE TABLE translation_candidates (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    gene_candidate TEXT REFERENCES gene_candidates(gene),
    translation_candidate TEXT REFERENCES genes(gene_id)
);

ALTER TABLE translation_candidates ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Authenticated users can select translation_candidates" ON translation_candidates;
CREATE POLICY "Authenticated users can select translation_candidates"
ON translation_candidates AS permissive
FOR SELECT TO authenticated
USING (true);
