CREATE TABLE cyl_qc_sets (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL
);

ALTER TABLE cyl_qc_sets ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Authenticated users can select cyl_qc_sets" ON cyl_qc_sets;

CREATE POLICY "Authenticated users can select cyl_qc_sets"
ON cyl_qc_sets AS permissive
FOR SELECT TO authenticated
USING (true);

DROP POLICY IF EXISTS "Authenticated users can insert cyl_qc_sets" ON cyl_qc_sets;

CREATE POLICY "Authenticated users can insert cyl_qc_sets"
ON cyl_qc_sets AS permissive
FOR INSERT TO authenticated
WITH CHECK (true);
