-- create the gene_candidate_scientists.id column
ALTER TABLE gene_candidate_scientists ADD COLUMN id BIGINT GENERATED BY DEFAULT AS IDENTITY;

-- change the primary key to all three columns
ALTER TABLE gene_candidate_scientists DROP CONSTRAINT gene_candidate_scientists_pkey;
ALTER TABLE gene_candidate_scientists ADD PRIMARY KEY (id, gene_candidate_id, scientist_id);
