-- create scrna_cells table
CREATE TABLE scrna_cells (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    dataset_id BIGINT REFERENCES scrna_datasets(id) NOT NULL,
    cell_number INT NOT NULL,
    barcode TEXT,
    x FLOAT,
    y FLOAT,
    cluster_id INT
);

-- set up RLS
ALTER TABLE scrna_cells ENABLE ROW LEVEL SECURITY;

-- grant permissions
DROP POLICY IF EXISTS "Authenticated users can select scrna_cells" ON scrna_cells;
CREATE POLICY "Authenticated users can select scrna_cells"
ON scrna_cells AS permissive
FOR SELECT TO authenticated
USING (true);
