-- Creating table 'assemblies'
CREATE TABLE assemblies (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    version INT,
    species_id BIGINT REFERENCES species(id),
    origin TEXT,
    external_version TEXT NULL,
    external_link TEXT NULL,
    accession_name TEXT,
    archive_link TEXT NOT NULL
);
