CREATE TABLE cyl_trait_sources (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL
);

ALTER TABLE cyl_trait_sources ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Authenticated users can select cyl_trait_sources" ON cyl_trait_sources;

CREATE POLICY "Authenticated users can select cyl_trait_sources"
ON cyl_trait_sources AS permissive
FOR SELECT TO authenticated
USING (true);

DROP POLICY IF EXISTS "Authenticated users can insert cyl_trait_sources" ON cyl_trait_sources;

CREATE POLICY "Authenticated users can insert cyl_trait_sources"
ON cyl_trait_sources AS permissive
FOR INSERT TO authenticated
WITH CHECK (true);
