-- Creating table 'gene_progress_notes'
CREATE TABLE gene_progress_notes (
    primary_key BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    gene TEXT REFERENCES genes(gene_id),
    description TEXT,
    date DATE DEFAULT now()
);

ALTER TABLE gene_progress_notes ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Authenticated users can select gene_progress_notes" ON gene_progress_notes;
CREATE POLICY "Authenticated users can select gene_progress_notes"
ON gene_progress_notes AS permissive
FOR SELECT TO authenticated
USING (true);
