-- create the scrna_counts table
CREATE TABLE scrna_counts (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    dataset_id BIGINT REFERENCES scrna_datasets(id) NOT NULL,
    gene_id BIGINT REFERENCES scrna_genes(id) NOT NULL,
    -- Supabase storage scrna/counts/{dataset_name}/{gene_name}.json
    counts_object_path TEXT
);

-- set up RLS
ALTER TABLE scrna_counts ENABLE ROW LEVEL SECURITY;

-- grant permissions
DROP POLICY IF EXISTS "Authenticated users can select scrna_counts" ON scrna_counts;
CREATE POLICY "Authenticated users can select scrna_counts"
ON scrna_counts AS permissive
FOR SELECT TO authenticated
USING (true);
