-- Creating table 'gene_candidate_support'
CREATE TABLE gene_candidate_support (
    primary_key BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    gene TEXT REFERENCES gene_candidates(gene),
    source TEXT CHECK (source IN ('internal', 'literature')),
    description TEXT
);

ALTER TABLE gene_candidate_support ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Authenticated users can select gene_candidate_support" ON gene_candidate_support;
CREATE POLICY "Authenticated users can select gene_candidate_support"
ON gene_candidate_support AS permissive
FOR SELECT TO authenticated
USING (true);
