CREATE TABLE cyl_qc_set_codes (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    set_id BIGINT NOT NULL REFERENCES cyl_qc_sets(id),
    code_id BIGINT NOT NULL REFERENCES cyl_qc_codes(id)
);

ALTER TABLE cyl_qc_set_codes ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Authenticated users can select cyl_qc_set_codes" ON cyl_qc_set_codes;

CREATE POLICY "Authenticated users can select cyl_qc_set_codes"
ON cyl_qc_set_codes AS permissive
FOR SELECT TO authenticated
USING (true);

DROP POLICY IF EXISTS "Authenticated users can insert cyl_qc_set_codes" ON cyl_qc_set_codes;

CREATE POLICY "Authenticated users can insert cyl_qc_set_codes"
ON cyl_qc_set_codes AS permissive
FOR INSERT TO authenticated
WITH CHECK (true);
