-- Creating table 'translation_lines'
CREATE TABLE translation_lines (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    accession_id BIGINT REFERENCES accessions(id),
    gene_id TEXT REFERENCES genes(gene_id),
    name TEXT,
    modification_description TEXT
);

ALTER TABLE translation_lines ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Authenticated users can select translation_lines" ON translation_lines;
CREATE POLICY "Authenticated users can select translation_lines"
ON translation_lines AS permissive
FOR SELECT TO authenticated
USING (true);
