-- Creating table 'gene_patents'
CREATE TABLE gene_patents (
    primary_key BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    gene TEXT REFERENCES genes(gene_id),
    description TEXT,
    submission_date TIMESTAMP NULL,
    response_date TIMESTAMP NULL,
    status TEXT CHECK (status IN ('denied', 'issued', 'pending')),
    region TEXT, -- Further refinement may be needed (country, etc.)
    type TEXT CHECK (type IN ('provisional', 'patent')),
    govt_id TEXT
);

ALTER TABLE gene_patents ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Authenticated users can select gene_patents" ON gene_patents;
CREATE POLICY "Authenticated users can select gene_patents"
ON gene_patents AS permissive
FOR SELECT TO authenticated
USING (true);
