CREATE TABLE cyl_qc_codes (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    plant_id BIGINT NOT NULL REFERENCES cyl_plants(id),
    value TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL
);

ALTER TABLE cyl_qc_codes ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Authenticated users can select cyl_qc_codes" ON cyl_qc_codes;

CREATE POLICY "Authenticated users can select cyl_qc_codes"
ON cyl_qc_codes AS permissive
FOR SELECT TO authenticated
USING (true);

DROP POLICY IF EXISTS "Authenticated users can insert cyl_qc_codes" ON cyl_qc_codes;

CREATE POLICY "Authenticated users can insert cyl_qc_codes"
ON cyl_qc_codes AS permissive
FOR INSERT TO authenticated
WITH CHECK (true);
