CREATE TABLE plates_exp (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    plate_id TEXT,
    experiment_name TEXT,
    genotype TEXT,
    treatment TEXT,
    scan_filename TEXT,
    scan_date DATE,
    planting_date DATE,
    plant_age TEXT,
    file_path TEXT,
    pos_genotype_grid JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE plates_exp
ADD CONSTRAINT unique_plate_id UNIQUE (plate_id);

-- Enable RLS
ALTER TABLE plates_exp ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Authenticated users can insert plates_exp" ON plates_exp;
CREATE POLICY "Authenticated users can insert plates_exp"
  ON plates_exp AS permissive
  FOR INSERT TO authenticated
  WITH CHECK (true);

DROP POLICY IF EXISTS "Authenticated users can select plates_exp" ON plates_exp;
CREATE POLICY "Authenticated users can select plates_exp"
  ON plates_exp AS permissive
  FOR SELECT TO authenticated
  USING (true);

DROP POLICY IF EXISTS "Authenticated users can update plates_exp" ON plates_exp;
CREATE POLICY "Authenticated users can update plates_exp"
  ON plates_exp AS permissive
  FOR UPDATE TO authenticated
  USING (true);

-- DROP POLICY IF EXISTS "Authenticated users can delete plates_exp" ON plates_exp;
-- CREATE POLICY "Authenticated users can delete plates_exp"
--   ON plates_exp AS permissive
--   FOR DELETE TO authenticated
--   USING (true);
