-- create a table for ortho_group_id to gene_id mapping
-- add rsl to insert
-- add rsl to update

CREATE TABLE ortho_gene_id_map (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    ortho_group TEXT NOT NULL,
    gene_ids JSONB DEFAULT NULL
);

ALTER TABLE ortho_gene_id_map ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Authenticated users can insert ortho_gene_id_map" ON ortho_gene_id_map;
CREATE POLICY "Authenticated users can insert ortho_gene_id_map"
ON ortho_gene_id_map AS permissive
FOR INSERT TO authenticated
WITH CHECK (true);

DROP POLICY IF EXISTS "Authenticated users can select ortho_gene_id_map" ON ortho_gene_id_map;
CREATE POLICY "Authenticated users can select ortho_gene_id_map"
ON ortho_gene_id_map AS permissive
FOR SELECT TO authenticated
USING (true);
