CREATE TABLE plate_plant_traits_list (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    plant_trait TEXT, 
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE plate_plant_traits_list ENABLE ROW LEVEL SECURITY;

ALTER TABLE plate_plant_traits_list
ADD CONSTRAINT unique_trait UNIQUE (plant_trait);

DROP POLICY IF EXISTS "Authenticated users can insert plate_plant_traits_list" ON plate_plant_traits_list;
CREATE POLICY "Authenticated users can insert plate_plant_traits_list"
ON plate_plant_traits_list AS permissive
FOR INSERT TO authenticated
WITH CHECK (true);

DROP POLICY IF EXISTS "Authenticated users can select plate_plant_traits_list" ON plate_plant_traits_list;
CREATE POLICY "Authenticated users can select plate_plant_traits_list"
ON plate_plant_traits_list AS permissive
FOR SELECT TO authenticated
USING (true);

DROP POLICY IF EXISTS "Authenticated users can update plate_plant_traits_list" ON plate_plant_traits_list;
CREATE POLICY "Authenticated users can update plate_plant_traits_list"
ON plate_plant_traits_list AS permissive
FOR UPDATE TO authenticated
USING (true);
