-- create scrna_de table to store results of differential expression analysis
CREATE TABLE scrna_de (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    dataset_id BIGINT REFERENCES scrna_datasets(id) NOT NULL,
    file_path TEXT NOT NULL,
    cluster_id TEXT
);

ALTER TABLE scrna_de ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Authenticated users can insert scrna_de" ON scrna_de;
CREATE POLICY "Authenticated users can insert scrna_de"
ON scrna_de AS permissive
FOR INSERT TO authenticated
WITH CHECK (true);

DROP POLICY IF EXISTS "Authenticated users can update scrna_de" ON scrna_de;
CREATE POLICY "Authenticated users can update scrna_de"
ON scrna_de AS permissive
FOR UPDATE TO authenticated
USING (true);

DROP POLICY IF EXISTS "Authenticated users can read scrna_de" ON scrna_de;

CREATE POLICY "Authenticated users can read scrna_de"
ON scrna_de AS permissive
FOR SELECT TO authenticated
USING (true);