CREATE TABLE plates_trait_source (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    source TEXT
);

ALTER TABLE plates_trait_source
ADD CONSTRAINT unique_source UNIQUE (source);

ALTER TABLE plates_trait_source ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Authenticated users can insert plates_trait_source" ON plates_trait_source;
CREATE POLICY "Authenticated users can insert plates_trait_source"
ON plates_trait_source AS permissive
FOR INSERT TO authenticated
WITH CHECK (true);

DROP POLICY IF EXISTS "Authenticated users can select plates_trait_source" ON plates_trait_source;
CREATE POLICY "Authenticated users can select plates_trait_source"
ON plates_trait_source AS permissive
FOR SELECT TO authenticated
USING (true);

DROP POLICY IF EXISTS "Authenticated users can update plates_trait_source" ON plates_trait_source;
CREATE POLICY "Authenticated users can update plates_trait_source"
ON plates_trait_source AS permissive
FOR UPDATE TO authenticated
USING (true);