CREATE TABLE plates_scan_trait (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    plate_id BIGINT REFERENCES plates_exp(id),
    plant_id TEXT,
    value FLOAT,
    source_id BIGINT REFERENCES plates_trait_source(id),
    trait_id BIGINT REFERENCES plate_plant_traits_list(id)
);

ALTER TABLE plates_scan_trait
ADD CONSTRAINT unique_plate_trait_source
UNIQUE (plate_id, trait_id, source_id,plant_id);

ALTER TABLE plates_scan_trait ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Authenticated users can insert plates_scan_trait" ON plates_scan_trait;
CREATE POLICY "Authenticated users can insert plates_scan_trait"
ON plates_scan_trait AS permissive
FOR INSERT TO authenticated
WITH CHECK (true);

DROP POLICY IF EXISTS "Authenticated users can select plates_scan_trait" ON plates_scan_trait;
CREATE POLICY "Authenticated users can select plates_scan_trait"
ON plates_scan_trait AS permissive
FOR SELECT TO authenticated
USING (true);

DROP POLICY IF EXISTS "Authenticated users can update plates_scan_trait" ON plates_scan_trait;
CREATE POLICY "Authenticated users can update plates_scan_trait"
ON plates_scan_trait AS permissive
FOR UPDATE TO authenticated
USING (true);
