CREATE TABLE cyl_scientists (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    scientist_name TEXT,
    email TEXT
);

ALTER TABLE cyl_scientists ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Authenticated users can insert cyl_scientists" ON cyl_scientists;
CREATE POLICY "Authenticated users can insert cyl_scientists"
ON cyl_scientists AS permissive
FOR INSERT TO authenticated
WITH CHECK (true);

DROP POLICY IF EXISTS "Authenticated users can select cyl_scientists" ON cyl_scientists;
CREATE POLICY "Authenticated users can select cyl_scientists"
ON cyl_scientists AS permissive
FOR SELECT TO authenticated
USING (true);

DROP POLICY IF EXISTS "Authenticated users can update cyl_scientists" ON cyl_scientists;
CREATE POLICY "Authenticated users can update cyl_scientists"
ON cyl_scientists AS permissive
FOR UPDATE TO authenticated
USING (true);

DROP POLICY IF EXISTS "Authenticated users can delete cyl_scientists" ON cyl_scientists;
CREATE POLICY "Authenticated users can delete cyl_scientists"
ON cyl_scientists AS permissive
FOR DELETE TO authenticated
USING (true);
