-- Migration: create_scrna_clusters
-- Phase 1 of Expression Explorer (add-scrna-expression-schema).
-- Creates scrna_clusters — the authoritative per-dataset cluster catalog
-- with a contiguous ordinal (0..K-1) for Uint8Array packing, plus human-
-- readable name and hex color.
--
-- RLS mirrors the established scrna_* pattern:
--   authenticated SELECT / INSERT / UPDATE
--   anon          SELECT
--   bloom_user    SELECT (shared scientific data)
--   bloom_admin   ALL
--   bloom_agent   SELECT (read-only agent)

BEGIN;

CREATE TABLE IF NOT EXISTS public.scrna_clusters (
  id         BIGINT   PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  dataset_id BIGINT   NOT NULL REFERENCES public.scrna_datasets(id) ON DELETE CASCADE,
  cluster_id TEXT     NOT NULL,
  ordinal    SMALLINT NOT NULL,
  name       TEXT,
  color      TEXT,
  UNIQUE (dataset_id, cluster_id),
  UNIQUE (dataset_id, ordinal)
);

CREATE INDEX IF NOT EXISTS idx_scrna_clusters_dataset_id
  ON public.scrna_clusters (dataset_id);

ALTER TABLE public.scrna_clusters ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Authenticated users can select scrna_clusters" ON public.scrna_clusters;
CREATE POLICY "Authenticated users can select scrna_clusters"
  ON public.scrna_clusters AS permissive
  FOR SELECT TO authenticated
  USING (true);

DROP POLICY IF EXISTS "Authenticated users can insert scrna_clusters" ON public.scrna_clusters;
CREATE POLICY "Authenticated users can insert scrna_clusters"
  ON public.scrna_clusters AS permissive
  FOR INSERT TO authenticated
  WITH CHECK (true);

DROP POLICY IF EXISTS "Authenticated users can update scrna_clusters" ON public.scrna_clusters;
CREATE POLICY "Authenticated users can update scrna_clusters"
  ON public.scrna_clusters AS permissive
  FOR UPDATE TO authenticated
  USING (true);

DROP POLICY IF EXISTS "Anon users can select scrna_clusters" ON public.scrna_clusters;
CREATE POLICY "Anon users can select scrna_clusters"
  ON public.scrna_clusters AS permissive
  FOR SELECT TO anon
  USING (true);

DROP POLICY IF EXISTS user_read_scrna_clusters ON public.scrna_clusters;
CREATE POLICY user_read_scrna_clusters
  ON public.scrna_clusters FOR SELECT TO bloom_user USING (true);

DROP POLICY IF EXISTS admin_all_scrna_clusters ON public.scrna_clusters;
CREATE POLICY admin_all_scrna_clusters
  ON public.scrna_clusters FOR ALL TO bloom_admin USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS agent_read_scrna_clusters ON public.scrna_clusters;
CREATE POLICY agent_read_scrna_clusters
  ON public.scrna_clusters FOR SELECT TO bloom_agent USING (true);

COMMIT;
