-- Port of bloom V1's gravi_scan_sessions table. Tracks a single GraviScan
-- recording session (one or more cycles of multi-plate captures).

-- scan_mode is constrained to known values; actual_duration_seconds lets the
-- desktop record the real elapsed time (start → complete) separately from the
-- planned duration_seconds, since cancellation or capture-rate variation can
-- diverge from the plan.

CREATE TABLE gravi_scan_sessions (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    experiment_id BIGINT NOT NULL REFERENCES gravi_experiments(id) ON DELETE CASCADE,
    phenotyper_id BIGINT REFERENCES phenotypers(id),
    scan_mode TEXT NOT NULL DEFAULT 'single',
    interval_seconds INT,
    duration_seconds INT,
    total_cycles INT,
    actual_duration_seconds INT,
    started_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    completed_at TIMESTAMPTZ,
    cancelled BOOLEAN NOT NULL DEFAULT false,
    CONSTRAINT chk_scan_mode CHECK (scan_mode IN ('single', 'continuous'))
);

ALTER TABLE gravi_scan_sessions ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS admin_all_gravi_scan_sessions ON public.gravi_scan_sessions;
CREATE POLICY admin_all_gravi_scan_sessions ON public.gravi_scan_sessions
    FOR ALL TO bloom_admin USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS agent_read_gravi_scan_sessions ON public.gravi_scan_sessions;
CREATE POLICY agent_read_gravi_scan_sessions ON public.gravi_scan_sessions
    FOR SELECT TO bloom_agent USING (true);

DROP POLICY IF EXISTS user_read_gravi_scan_sessions ON public.gravi_scan_sessions;
CREATE POLICY user_read_gravi_scan_sessions ON public.gravi_scan_sessions
    FOR SELECT TO bloom_user USING (true);

DROP POLICY IF EXISTS user_insert_gravi_scan_sessions ON public.gravi_scan_sessions;
CREATE POLICY user_insert_gravi_scan_sessions ON public.gravi_scan_sessions
    FOR INSERT TO bloom_user WITH CHECK (true);

DROP POLICY IF EXISTS user_update_gravi_scan_sessions ON public.gravi_scan_sessions;
CREATE POLICY user_update_gravi_scan_sessions ON public.gravi_scan_sessions
    FOR UPDATE TO bloom_user USING (true);
