-- RLS uses V2's bloom_role pattern (admin/agent/user). bloom_writer writes
-- via bloom_user role inheritance (see 20260519130000_add_bloom_writer_role.sql).

CREATE TABLE gravi_scanners (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL,
    vendor_id TEXT DEFAULT '04b8',
    product_id TEXT DEFAULT '013a',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE(name)
);

ALTER TABLE gravi_scanners ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS admin_all_gravi_scanners ON public.gravi_scanners;
CREATE POLICY admin_all_gravi_scanners ON public.gravi_scanners
    FOR ALL TO bloom_admin USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS agent_read_gravi_scanners ON public.gravi_scanners;
CREATE POLICY agent_read_gravi_scanners ON public.gravi_scanners
    FOR SELECT TO bloom_agent USING (true);

DROP POLICY IF EXISTS user_read_gravi_scanners ON public.gravi_scanners;
CREATE POLICY user_read_gravi_scanners ON public.gravi_scanners
    FOR SELECT TO bloom_user USING (true);

DROP POLICY IF EXISTS user_insert_gravi_scanners ON public.gravi_scanners;
CREATE POLICY user_insert_gravi_scanners ON public.gravi_scanners
    FOR INSERT TO bloom_user WITH CHECK (true);

DROP POLICY IF EXISTS user_update_gravi_scanners ON public.gravi_scanners;
CREATE POLICY user_update_gravi_scanners ON public.gravi_scanners
    FOR UPDATE TO bloom_user USING (true);
