-- gravi_scan_metadata_section_plants: maps plant QR codes to plate sections.
-- One row per (section, plant_qr) pair. ON DELETE CASCADE so deleting a section
-- removes its plant mappings.

CREATE TABLE gravi_scan_metadata_section_plants (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    section_id BIGINT NOT NULL REFERENCES gravi_scan_metadata_sections(id) ON DELETE CASCADE,
    plant_qr TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (section_id, plant_qr)
);

ALTER TABLE gravi_scan_metadata_section_plants ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS admin_all_gravi_scan_metadata_section_plants ON public.gravi_scan_metadata_section_plants;
CREATE POLICY admin_all_gravi_scan_metadata_section_plants ON public.gravi_scan_metadata_section_plants
    FOR ALL TO bloom_admin USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS agent_read_gravi_scan_metadata_section_plants ON public.gravi_scan_metadata_section_plants;
CREATE POLICY agent_read_gravi_scan_metadata_section_plants ON public.gravi_scan_metadata_section_plants
    FOR SELECT TO bloom_agent USING (true);

DROP POLICY IF EXISTS user_read_gravi_scan_metadata_section_plants ON public.gravi_scan_metadata_section_plants;
CREATE POLICY user_read_gravi_scan_metadata_section_plants ON public.gravi_scan_metadata_section_plants
    FOR SELECT TO bloom_user USING (true);

DROP POLICY IF EXISTS user_insert_gravi_scan_metadata_section_plants ON public.gravi_scan_metadata_section_plants;
CREATE POLICY user_insert_gravi_scan_metadata_section_plants ON public.gravi_scan_metadata_section_plants
    FOR INSERT TO bloom_user WITH CHECK (true);

DROP POLICY IF EXISTS user_update_gravi_scan_metadata_section_plants ON public.gravi_scan_metadata_section_plants;
CREATE POLICY user_update_gravi_scan_metadata_section_plants ON public.gravi_scan_metadata_section_plants
    FOR UPDATE TO bloom_user USING (true);
