-- gravi_scans: one row per image capture event. plate_id is the V1-prod column
-- name (renamed from plant_barcode in V1's original migration file). The
-- desktop's bloom-js wrapper still uses the parameter name `plate_barcode_`
-- when calling the insert_gravi_image RPC; the RPC body maps that to plate_id.
--
-- Denormalised plate-metadata fields (wave_number, transplant_date, custom_note)
-- mirror gravi_scan_metadata_accession so per-scan queries don't need to join
-- through metadata_id. metadata_id is a soft pointer for traceability.
--
-- idx_gravi_scans_natural_key prevents duplicate uploads — the RPC's pre-insert
-- check looks up by (experiment_id, plate_id, capture_date) before inserting.

CREATE TABLE gravi_scans (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    experiment_id BIGINT NOT NULL REFERENCES gravi_experiments(id),
    phenotyper_id BIGINT REFERENCES phenotypers(id),
    scanner_id BIGINT REFERENCES gravi_scanners(id),
    session_id BIGINT REFERENCES gravi_scan_sessions(id) ON DELETE SET NULL,
    metadata_id BIGINT REFERENCES gravi_scan_metadata_accession(id),
    cycle_number INT,
    plate_id TEXT,
    capture_date TIMESTAMPTZ NOT NULL DEFAULT now(),
    grid_mode TEXT NOT NULL,
    plate_index TEXT NOT NULL,
    resolution INT NOT NULL,
    format TEXT NOT NULL DEFAULT 'jpeg',
    wave_number INT,
    transplant_date TIMESTAMPTZ,
    custom_note TEXT,
    uploaded_at TIMESTAMPTZ DEFAULT now(),
    CONSTRAINT chk_cycle_number CHECK (cycle_number IS NULL OR cycle_number >= 0)
);

CREATE UNIQUE INDEX idx_gravi_scans_natural_key
    ON gravi_scans (experiment_id, plate_id, capture_date);

ALTER TABLE gravi_scans ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS admin_all_gravi_scans ON public.gravi_scans;
CREATE POLICY admin_all_gravi_scans ON public.gravi_scans
    FOR ALL TO bloom_admin USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS agent_read_gravi_scans ON public.gravi_scans;
CREATE POLICY agent_read_gravi_scans ON public.gravi_scans
    FOR SELECT TO bloom_agent USING (true);

DROP POLICY IF EXISTS user_read_gravi_scans ON public.gravi_scans;
CREATE POLICY user_read_gravi_scans ON public.gravi_scans
    FOR SELECT TO bloom_user USING (true);

DROP POLICY IF EXISTS user_insert_gravi_scans ON public.gravi_scans;
CREATE POLICY user_insert_gravi_scans ON public.gravi_scans
    FOR INSERT TO bloom_user WITH CHECK (true);

DROP POLICY IF EXISTS user_update_gravi_scans ON public.gravi_scans;
CREATE POLICY user_update_gravi_scans ON public.gravi_scans
    FOR UPDATE TO bloom_user USING (true);
