-- 20260625120000_create_cyl_scan_intermediates.sql
--
-- Change C (#296): per-scan blob/intermediates table for the sleap-roots cylinder
-- pipeline. One row per artifact file (today: one SLEAP `.slp` prediction file per
-- root type per scan). Dual pointer: `s3_location` is the canonical Bloom MinIO copy
-- (Bloom serves + RLS-controls it); `box_link` is a human-shareable Box link.
-- `checksum` + `file_size` tie the two copies together and detect partial uploads.
-- The pipeline that produced a row is recoverable from provenance
-- (`cyl_trait_sources.metadata` via `source_id`), so it is not a column here.
--
-- Grain: one row per (source_id, scan_id, kind, root_type) — UNIQUE preserves history
-- across re-runs (distinct source_id) and is the write-back path's (change D) upsert key.
--
-- RLS (modern role model, matching gravi_images / embedtree): bloom_admin FOR ALL;
-- bloom_agent + bloom_user SELECT; bloom_writer SELECT/INSERT/UPDATE (the ingest /
-- write-back role). No write policy for bloom_user/bloom_agent — their read-only
-- posture is enforced by the absence of write policies. Table-level GRANTs gate
-- PostgREST exposure (independent of, and required alongside, the RLS policies).
--
-- Forward-only + additive; companion manual rollback under supabase/rollbacks/.
-- Idempotent for a re-runnable `supabase db push`: CREATE TABLE IF NOT EXISTS,
-- DROP POLICY IF EXISTS before each CREATE POLICY.

BEGIN;

CREATE TABLE IF NOT EXISTS cyl_scan_intermediates (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    source_id BIGINT NOT NULL REFERENCES cyl_trait_sources(id),
    scan_id BIGINT NOT NULL REFERENCES cyl_scans(id),
    kind TEXT NOT NULL CHECK (kind IN ('predictions_slp')),
    root_type TEXT NOT NULL CHECK (root_type IN ('primary', 'lateral', 'crown')),
    s3_location TEXT,
    box_link TEXT,
    checksum TEXT,
    file_size BIGINT,
    CONSTRAINT cyl_scan_intermediates_at_least_one_location
        CHECK (s3_location IS NOT NULL OR box_link IS NOT NULL),
    CONSTRAINT cyl_scan_intermediates_run_scan_kind_root_type_key
        UNIQUE (source_id, scan_id, kind, root_type)
);

ALTER TABLE cyl_scan_intermediates ENABLE ROW LEVEL SECURITY;

-- bloom_admin: full access
DROP POLICY IF EXISTS admin_all_cyl_scan_intermediates ON cyl_scan_intermediates;
CREATE POLICY admin_all_cyl_scan_intermediates ON cyl_scan_intermediates
    FOR ALL TO bloom_admin USING (true) WITH CHECK (true);

-- bloom_agent + bloom_user: read-only
DROP POLICY IF EXISTS agent_read_cyl_scan_intermediates ON cyl_scan_intermediates;
CREATE POLICY agent_read_cyl_scan_intermediates ON cyl_scan_intermediates
    FOR SELECT TO bloom_agent USING (true);

DROP POLICY IF EXISTS user_read_cyl_scan_intermediates ON cyl_scan_intermediates;
CREATE POLICY user_read_cyl_scan_intermediates ON cyl_scan_intermediates
    FOR SELECT TO bloom_user USING (true);

-- bloom_writer: the ingest / write-back role (change D writes here)
DROP POLICY IF EXISTS writer_read_cyl_scan_intermediates ON cyl_scan_intermediates;
CREATE POLICY writer_read_cyl_scan_intermediates ON cyl_scan_intermediates
    FOR SELECT TO bloom_writer USING (true);

DROP POLICY IF EXISTS writer_insert_cyl_scan_intermediates ON cyl_scan_intermediates;
CREATE POLICY writer_insert_cyl_scan_intermediates ON cyl_scan_intermediates
    FOR INSERT TO bloom_writer WITH CHECK (true);

DROP POLICY IF EXISTS writer_update_cyl_scan_intermediates ON cyl_scan_intermediates;
CREATE POLICY writer_update_cyl_scan_intermediates ON cyl_scan_intermediates
    FOR UPDATE TO bloom_writer USING (true) WITH CHECK (true);

-- Table-level GRANTs (RLS policy + GRANT are independent; both are required for
-- PostgREST to expose the table to a role).
GRANT SELECT ON cyl_scan_intermediates TO bloom_user, bloom_agent;
GRANT SELECT, INSERT, UPDATE ON cyl_scan_intermediates TO bloom_writer;
GRANT SELECT, INSERT, UPDATE, DELETE ON cyl_scan_intermediates TO bloom_admin;

COMMIT;
