-- 20260928185707_create_scrna_cellranger_runs.sql
--
-- Cell Ranger runs started from Bloom, one sample per run: the run table, its
-- dispatch queue, and the function that creates a run and queues it.
-- Forward-only; rollback in supabase/rollbacks/.

BEGIN;

-- 1. scrna_cellranger_runs ----------------------------------------------------

CREATE TABLE IF NOT EXISTS scrna_cellranger_runs (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    -- Names may not contain '__', the run_key separator.
    sample TEXT NOT NULL
        CHECK (sample ~ '^[A-Za-z0-9][A-Za-z0-9._-]{0,99}$' AND sample !~ '__'),
    reference TEXT NOT NULL
        CHECK (reference ~ '^[A-Za-z0-9][A-Za-z0-9._-]{0,99}$' AND reference !~ '__'),
    -- Output folder under runs_output/, one per sample, reference and requester.
    run_key TEXT NOT NULL,
    requested_by UUID NOT NULL,
    status TEXT NOT NULL DEFAULT 'queued'
        CHECK (status IN ('queued', 'submitted', 'running', 'succeeded', 'skipped', 'failed')),
    current_step TEXT
        CHECK (current_step IS NULL OR current_step IN ('stage', 'qc', 'count', 'cleanup')),
    exit_code INTEGER,
    message TEXT,
    -- Step name -> pod name, for reading a step's log.
    step_pods JSONB,
    argo_workflow_name TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    submitted_at TIMESTAMPTZ,
    completed_at TIMESTAMPTZ,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT scrna_cellranger_runs_run_key_check CHECK (run_key = sample || '__' || reference || '__' || requested_by::text)
);

ALTER TABLE public.scrna_cellranger_runs ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS admin_all_scrna_cellranger_runs ON public.scrna_cellranger_runs;
CREATE POLICY admin_all_scrna_cellranger_runs ON public.scrna_cellranger_runs
    FOR ALL TO bloom_admin USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS agent_read_scrna_cellranger_runs ON public.scrna_cellranger_runs;
CREATE POLICY agent_read_scrna_cellranger_runs ON public.scrna_cellranger_runs
    FOR SELECT TO bloom_agent USING (true);

DROP POLICY IF EXISTS user_read_scrna_cellranger_runs ON public.scrna_cellranger_runs;
CREATE POLICY user_read_scrna_cellranger_runs ON public.scrna_cellranger_runs
    FOR SELECT TO bloom_user USING (true);

DROP POLICY IF EXISTS workflows_read_scrna_cellranger_runs ON public.scrna_cellranger_runs;
CREATE POLICY workflows_read_scrna_cellranger_runs ON public.scrna_cellranger_runs
    FOR SELECT TO bloom_workflows USING (true);

-- Replace the default grants with explicit ones: read for bloom_user, bloom_agent
-- and bloom_workflows; full access for bloom_admin.
REVOKE ALL ON public.scrna_cellranger_runs
    FROM anon, authenticated, bloom_user, bloom_agent, bloom_writer, bloom_workflows;
REVOKE UPDATE, DELETE, TRUNCATE ON public.scrna_cellranger_runs FROM service_role;
GRANT SELECT ON public.scrna_cellranger_runs TO bloom_user, bloom_agent, bloom_workflows;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.scrna_cellranger_runs TO bloom_admin;

-- 2. Realtime publication -----------------------------------------------------

DO $$
BEGIN
  ALTER PUBLICATION supabase_realtime ADD TABLE public.scrna_cellranger_runs;
EXCEPTION WHEN duplicate_object THEN
  NULL;
END$$;

-- 3. Dispatch queue + request function ----------------------------------------

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pgmq.list_queues() WHERE queue_name = 'scrna_cellranger_dispatch') THEN
    PERFORM pgmq.create('scrna_cellranger_dispatch');
  END IF;
END
$$;

-- Creates a queued run and its dispatch message in one transaction; returns the run id.
CREATE OR REPLACE FUNCTION public.request_scrna_cellranger_run(
    p_sample TEXT,
    p_reference TEXT,
    p_requested_by UUID
) RETURNS BIGINT
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public, pgmq
AS $$
DECLARE
    v_name_rule CONSTANT TEXT := '^[A-Za-z0-9][A-Za-z0-9._-]{0,99}$';
    v_run_id BIGINT;
BEGIN
    IF p_sample IS NULL OR p_sample !~ v_name_rule OR p_sample ~ '__' THEN
        RAISE EXCEPTION 'invalid sample name: %', p_sample USING ERRCODE = '22023';
    END IF;
    IF p_reference IS NULL OR p_reference !~ v_name_rule OR p_reference ~ '__' THEN
        RAISE EXCEPTION 'invalid reference name: %', p_reference USING ERRCODE = '22023';
    END IF;
    IF p_requested_by IS NULL THEN
        RAISE EXCEPTION 'requested_by is required' USING ERRCODE = '22023';
    END IF;

    INSERT INTO scrna_cellranger_runs (sample, reference, run_key, requested_by)
    VALUES (p_sample, p_reference, p_sample || '__' || p_reference || '__' || p_requested_by::text, p_requested_by)
    RETURNING id INTO v_run_id;

    PERFORM pgmq.send('scrna_cellranger_dispatch', jsonb_build_object('run_id', v_run_id));

    RETURN v_run_id;
END;
$$;

-- Only bloom_workflows may create runs.
REVOKE EXECUTE ON FUNCTION public.request_scrna_cellranger_run(TEXT, TEXT, UUID)
    FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.request_scrna_cellranger_run(TEXT, TEXT, UUID)
    TO bloom_workflows;

COMMIT;
