-- Migration: scrna_cells_genotype_and_labels
--
-- Adds one table and three columns so the map can filter cells by more than
-- cell type:
--
--   scrna_genotypes            one row per genotype in a dataset
--   scrna_cells.genotype_id    which genotype a cell belongs to
--   scrna_cells.facets         any other per-cell label, for filtering
--   scrna_clusters.source      where a cell type's label came from
--
-- `scrna_cell_arrays` is redefined to return the new columns alongside the
-- position it already returned. One query, one order: everything the explorer
-- fetches is paired to cells by position, so a second query could attach a
-- genotype to the wrong cell and look normal doing it.
--
-- Nothing is rewritten. `scrna_cells.replicate` keeps whatever it holds until
-- that dataset's ingest is re-run.

BEGIN;

-- ─── 1. Genotypes ────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS public.scrna_genotypes (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  dataset_id   BIGINT  NOT NULL REFERENCES public.scrna_datasets (id),
  name         TEXT    NOT NULL,
  -- The accession this genotype is, when the platform has one. NULL for a
  -- construct that is not an accession in its own right.
  accession_id BIGINT  REFERENCES public.arabidopsis_accessions (id),
  -- Whether this is the dataset's wild type. Set by whoever runs the ingest,
  -- never guessed from the name.
  is_control   BOOLEAN NOT NULL DEFAULT false,
  -- The construct a transgenic line carries. A property of the line, so no
  -- cell column repeats it.
  construct    TEXT,
  notes        TEXT,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
  -- One row per genotype per dataset, so a re-ingest lands on the same row.
  CONSTRAINT scrna_genotypes_one_per_dataset UNIQUE (dataset_id, name),
  -- Lets a cell reference (dataset_id, id) rather than id alone, so it cannot
  -- point at a genotype belonging to another experiment.
  CONSTRAINT scrna_genotypes_id_per_dataset UNIQUE (dataset_id, id),
  -- A name has to be a name. The characters are spelled out because btrim()
  -- with one argument strips ordinary spaces alone -- not a non-breaking space,
  -- which a name pasted from a document can be made entirely of. Vertical tab
  -- is \u000b and not \v, which Postgres reads as the letter v.
  CONSTRAINT scrna_genotypes_name_not_blank
    CHECK (btrim(name, E' \t\n\r\f\u000b\u00a0') <> ''),
  CONSTRAINT scrna_genotypes_construct_not_blank
    CHECK (construct IS NULL OR btrim(construct, E' \t\n\r\f\u000b\u00a0') <> ''),
  -- name is in the index below, where an oversized value fails with a btree
  -- row-size error rather than anything a reader could act on. notes is capped
  -- because it is served to every viewer of the dataset.
  CONSTRAINT scrna_genotypes_lengths CHECK (
    length(name)      <= 100 AND
    length(construct) <= 200 AND
    length(notes)     <= 2000
  )
);

-- Which genotype each cell belongs to. Keyed on the dataset as well as the
-- genotype, like the cluster reference on this table, so a cell cannot be given
-- a genotype from another experiment -- Col-0 exists in most of them. RESTRICT,
-- so deleting a genotype that still has cells is refused rather than taking the
-- cells with it.
ALTER TABLE public.scrna_cells
  ADD COLUMN IF NOT EXISTS genotype_id BIGINT;
ALTER TABLE public.scrna_cells
  DROP CONSTRAINT IF EXISTS scrna_cells_genotype_fkey;
ALTER TABLE public.scrna_cells
  ADD CONSTRAINT scrna_cells_genotype_fkey
  FOREIGN KEY (dataset_id, genotype_id)
  REFERENCES public.scrna_genotypes (dataset_id, id)
  ON DELETE RESTRICT;

CREATE INDEX IF NOT EXISTS idx_scrna_cells_genotype
  ON public.scrna_cells (genotype_id);

-- ─── 2. Cell type label source ───────────────────────────────────────────────

-- Where a cell type's label came from -- usually the reference atlas it was
-- transferred from. On the cell type rather than the dataset, because that is
-- where it varies. Free text: a person reads it, nothing filters on it.
ALTER TABLE public.scrna_clusters
  ADD COLUMN IF NOT EXISTS source TEXT;

COMMENT ON TABLE public.scrna_genotypes IS
  'The genotypes a dataset compares. Readable by anyone who can see the '
  'dataset, including anonymous visitors -- do not put anything unpublished '
  'in notes.';

COMMENT ON COLUMN public.scrna_clusters.source IS
  'Where this cell type''s label came from -- a reference atlas, a paper, or a '
  'method. NULL when the ingest was not told. Shown in the cluster sidebar.';

-- ─── 3. Per-cell labels ──────────────────────────────────────────────────────

-- Any label the ingest was told to load, as an object of short strings, so the
-- map can show or hide cells by it. Transgene status is the first.
ALTER TABLE public.scrna_cells
  ADD COLUMN IF NOT EXISTS facets JSONB DEFAULT NULL;

-- True when facets is an object of non-empty strings, which is the only shape
-- the explorer can draw as toggles. A function rather than a plain CHECK
-- because walking the object needs a subquery, which a CHECK cannot hold.
CREATE OR REPLACE FUNCTION public.scrna_facets_are_flat_text(facets JSONB)
RETURNS BOOLEAN
LANGUAGE sql
IMMUTABLE
PARALLEL SAFE
AS $fn$
  SELECT facets IS NULL
     OR (
       jsonb_typeof(facets) = 'object'
       -- A sidebar of toggles, not a payload. Every cell of the dataset
       -- carries this to every viewer, so the whole object is capped in bytes
       -- as well as its parts in characters -- 32 labels of 64 characters with
       -- 200-character values is 8.7 kB of ASCII and four times that in
       -- multibyte, which per-field limits cannot see. A cell carries about 48
       -- bytes today; all ten of the first dataset's annotation columns would
       -- be 401.
       AND octet_length(facets::text) <= 1024
       AND (SELECT count(*) FROM jsonb_object_keys(facets)) <= 32
       AND NOT EXISTS (
         SELECT 1 FROM jsonb_each(facets) AS f(key, value)
         WHERE jsonb_typeof(f.value) <> 'string'
            OR btrim(f.key, E' \t\n\r\f\u000b\u00a0') = ''
            OR btrim(f.value #>> '{}', E' \t\n\r\f\u000b\u00a0') = ''
            OR length(f.key) > 64
            OR length(f.value #>> '{}') > 200
       )
     );
$fn$;

-- Granted explicitly rather than left to the PUBLIC default: a CHECK runs with
-- the writer's privileges, so a later blanket REVOKE ... FROM PUBLIC would turn
-- every write to scrna_cells into a permission error naming a function.
REVOKE EXECUTE ON FUNCTION public.scrna_facets_are_flat_text(JSONB) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.scrna_facets_are_flat_text(JSONB)
  TO authenticated, bloom_writer, bloom_admin, service_role, postgres;

ALTER TABLE public.scrna_cells
  DROP CONSTRAINT IF EXISTS scrna_cells_facets_are_flat_text;
ALTER TABLE public.scrna_cells
  ADD CONSTRAINT scrna_cells_facets_are_flat_text
  CHECK (public.scrna_facets_are_flat_text(facets)) NOT VALID;

-- ─── 4. The cell query ───────────────────────────────────────────────────────

-- Dropped first: the return type changes, and CREATE OR REPLACE cannot.
DROP FUNCTION IF EXISTS public.scrna_cell_arrays(BIGINT);

CREATE FUNCTION public.scrna_cell_arrays(
  ds_id BIGINT
)
RETURNS TABLE (
  x               REAL,
  y               REAL,
  cluster_ordinal SMALLINT,
  genotype        TEXT,
  replicate       TEXT,
  facets          JSONB
)
LANGUAGE sql
STABLE
SECURITY INVOKER
AS $$
  SELECT
    c.x::REAL,
    c.y::REAL,
    COALESCE(cl.ordinal, 255::SMALLINT) AS cluster_ordinal,
    g.name AS genotype,
    c.replicate,
    c.facets
  FROM public.scrna_cells c
  LEFT JOIN public.scrna_clusters cl
    ON cl.dataset_id = c.dataset_id
   AND cl.cluster_id = c.cluster_id
  LEFT JOIN public.scrna_genotypes g
    ON g.id = c.genotype_id
   AND g.dataset_id = c.dataset_id
  WHERE c.dataset_id = ds_id
  ORDER BY c.cell_number ASC;
$$;

GRANT EXECUTE ON FUNCTION public.scrna_cell_arrays(BIGINT)
  TO anon, authenticated, bloom_user, bloom_admin, bloom_agent;

-- ─── 5. Read access ──────────────────────────────────────────────────────────

ALTER TABLE public.scrna_genotypes ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Anon users can select scrna_genotypes" ON public.scrna_genotypes;
CREATE POLICY "Anon users can select scrna_genotypes"
  ON public.scrna_genotypes AS permissive FOR SELECT TO anon USING (true);

DROP POLICY IF EXISTS "Authenticated users can select scrna_genotypes" ON public.scrna_genotypes;
CREATE POLICY "Authenticated users can select scrna_genotypes"
  ON public.scrna_genotypes AS permissive FOR SELECT TO authenticated USING (true);

DROP POLICY IF EXISTS "admin_all_scrna_genotypes" ON public.scrna_genotypes;
CREATE POLICY "admin_all_scrna_genotypes"
  ON public.scrna_genotypes AS permissive FOR ALL TO bloom_admin
  USING (true) WITH CHECK (true);

-- bloom_writer is the ingest role, and every other scrna_* table lets it write.
-- Without these the loader could point cells at genotypes it cannot create.
DROP POLICY IF EXISTS writer_select_scrna_genotypes ON public.scrna_genotypes;
CREATE POLICY writer_select_scrna_genotypes
  ON public.scrna_genotypes FOR SELECT TO bloom_writer USING (true);

DROP POLICY IF EXISTS writer_insert_scrna_genotypes ON public.scrna_genotypes;
CREATE POLICY writer_insert_scrna_genotypes
  ON public.scrna_genotypes FOR INSERT TO bloom_writer WITH CHECK (true);

DROP POLICY IF EXISTS writer_update_scrna_genotypes ON public.scrna_genotypes;
CREATE POLICY writer_update_scrna_genotypes
  ON public.scrna_genotypes FOR UPDATE TO bloom_writer
  USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "user_read_scrna_genotypes" ON public.scrna_genotypes;
CREATE POLICY "user_read_scrna_genotypes"
  ON public.scrna_genotypes AS permissive FOR SELECT TO bloom_user USING (true);

DROP POLICY IF EXISTS "agent_read_scrna_genotypes" ON public.scrna_genotypes;
CREATE POLICY "agent_read_scrna_genotypes"
  ON public.scrna_genotypes AS permissive FOR SELECT TO bloom_agent USING (true);

COMMIT;
