-- gravi_images: one row per uploaded image binary. UNIQUE(scan_id) enforces
-- one image per scan. file_hash + file_size_bytes capture upload integrity
-- metadata reported by the desktop after the storage upload completes.
--
-- The desktop's flow:
--   1. insert_gravi_image RPC returns scan_id (or NULL if duplicate)
--   2. Desktop uploads the binary to graviscan-images bucket
--   3. Desktop directly INSERTs into gravi_images with scan_id, object_path,
--      file_hash, file_size_bytes (no RPC needed; uses standard PostgREST INSERT).

CREATE TABLE gravi_images (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    scan_id BIGINT NOT NULL REFERENCES gravi_scans(id),
    object_path TEXT NOT NULL,
    file_hash TEXT,
    file_size_bytes BIGINT,
    uploaded_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (scan_id)
);

ALTER TABLE gravi_images ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS admin_all_gravi_images ON public.gravi_images;
CREATE POLICY admin_all_gravi_images ON public.gravi_images
    FOR ALL TO bloom_admin USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS agent_read_gravi_images ON public.gravi_images;
CREATE POLICY agent_read_gravi_images ON public.gravi_images
    FOR SELECT TO bloom_agent USING (true);

DROP POLICY IF EXISTS user_read_gravi_images ON public.gravi_images;
CREATE POLICY user_read_gravi_images ON public.gravi_images
    FOR SELECT TO bloom_user USING (true);

DROP POLICY IF EXISTS user_insert_gravi_images ON public.gravi_images;
CREATE POLICY user_insert_gravi_images ON public.gravi_images
    FOR INSERT TO bloom_user WITH CHECK (true);

DROP POLICY IF EXISTS user_update_gravi_images ON public.gravi_images;
CREATE POLICY user_update_gravi_images ON public.gravi_images
    FOR UPDATE TO bloom_user USING (true);
