-- 20261008182500_add_genome_references.sql
--
-- Reference genomes for the Cell Ranger workflow, with numbered versions. A genome belongs to
-- a species; each version is one gzipped FASTA and one gzipped GTF in the genome-references
-- bucket (added by 20261008182600), with their SHA-256 and size. A version is uploading, then
-- ready or abandoned; an admin can withdraw a ready one, with a reason. Version numbers are
-- never reused, and a finished version's files and checksums never change.
-- Forward-only; rollback in supabase/rollbacks/.

BEGIN;

-- 1. Tables --------------------------------------------------------------------------------

-- Lowercase letters, digits, '.', '_' or '-', at most 64, with no '__' and no '.v<N>' ending,
-- which is how a version of a genome is written.
CREATE OR REPLACE FUNCTION public.genome_name_ok(p_name TEXT)
RETURNS BOOLEAN
LANGUAGE sql
IMMUTABLE
SET search_path = pg_catalog
AS $$
    SELECT p_name ~ '^[a-z0-9][a-z0-9._-]{0,63}$' AND p_name !~ '__' AND p_name !~ '\.v[0-9]+$';
$$;

CREATE TABLE IF NOT EXISTS public.genome_references (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    -- The storage folder name.
    name TEXT NOT NULL,
    species_id BIGINT NOT NULL,
    description TEXT,
    -- The number the next version gets; only ever goes up.
    next_version INTEGER NOT NULL DEFAULT 1,
    created_by UUID NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.genome_reference_versions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    genome_id BIGINT NOT NULL,
    version INTEGER NOT NULL,
    status TEXT NOT NULL DEFAULT 'uploading',
    -- Object names in the genome-references bucket, set from the genome and version.
    fasta_path TEXT NOT NULL,
    gtf_path TEXT NOT NULL,
    -- Of the gzipped bytes stored; set when the upload is finished.
    fasta_sha256 TEXT,
    fasta_bytes BIGINT,
    gtf_sha256 TEXT,
    gtf_bytes BIGINT,
    -- Where the files came from, e.g. TAIR10 / Araport11 and the download page.
    assembly TEXT,
    annotation TEXT,
    source_url TEXT,
    notes TEXT,
    created_by UUID NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    ready_at TIMESTAMPTZ,
    withdrawn_reason TEXT,
    withdrawn_at TIMESTAMPTZ
);

-- 2. Keys ----------------------------------------------------------------------------------

DO $$
DECLARE
  existing TEXT;
BEGIN
  SELECT pg_get_constraintdef(oid) INTO existing
    FROM pg_constraint
   WHERE conname = 'genome_references_pkey' AND conrelid = 'public.genome_references'::regclass;
  IF existing IS NULL THEN
    ALTER TABLE public.genome_references ADD CONSTRAINT genome_references_pkey PRIMARY KEY (id);
  ELSIF existing <> 'PRIMARY KEY (id)' THEN
    RAISE EXCEPTION 'genome_references_pkey is %, expected PRIMARY KEY (id)', existing;
  END IF;
END $$;

DO $$
DECLARE
  existing TEXT;
BEGIN
  SELECT pg_get_constraintdef(oid) INTO existing
    FROM pg_constraint
   WHERE conname = 'genome_references_name_key' AND conrelid = 'public.genome_references'::regclass;
  IF existing IS NULL THEN
    ALTER TABLE public.genome_references ADD CONSTRAINT genome_references_name_key UNIQUE (name);
  ELSIF existing <> 'UNIQUE (name)' THEN
    RAISE EXCEPTION 'genome_references_name_key is %, expected UNIQUE (name)', existing;
  END IF;
END $$;

DO $$
DECLARE
  existing TEXT;
BEGIN
  SELECT pg_get_constraintdef(oid) INTO existing
    FROM pg_constraint
   WHERE conname = 'genome_reference_versions_pkey' AND conrelid = 'public.genome_reference_versions'::regclass;
  IF existing IS NULL THEN
    ALTER TABLE public.genome_reference_versions ADD CONSTRAINT genome_reference_versions_pkey PRIMARY KEY (id);
  ELSIF existing <> 'PRIMARY KEY (id)' THEN
    RAISE EXCEPTION 'genome_reference_versions_pkey is %, expected PRIMARY KEY (id)', existing;
  END IF;
END $$;

DO $$
DECLARE
  existing TEXT;
BEGIN
  SELECT pg_get_constraintdef(oid) INTO existing
    FROM pg_constraint
   WHERE conname = 'genome_reference_versions_genome_version_key' AND conrelid = 'public.genome_reference_versions'::regclass;
  IF existing IS NULL THEN
    ALTER TABLE public.genome_reference_versions ADD CONSTRAINT genome_reference_versions_genome_version_key UNIQUE (genome_id, version);
  ELSIF existing <> 'UNIQUE (genome_id, version)' THEN
    RAISE EXCEPTION 'genome_reference_versions_genome_version_key is %, expected UNIQUE (genome_id, version)', existing;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'genome_references_species_id_fkey' AND conrelid = 'public.genome_references'::regclass
  ) THEN
    ALTER TABLE public.genome_references ADD CONSTRAINT genome_references_species_id_fkey
      FOREIGN KEY (species_id) REFERENCES public.species(id);
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'genome_reference_versions_genome_id_fkey' AND conrelid = 'public.genome_reference_versions'::regclass
  ) THEN
    ALTER TABLE public.genome_reference_versions ADD CONSTRAINT genome_reference_versions_genome_id_fkey
      FOREIGN KEY (genome_id) REFERENCES public.genome_references(id);
  END IF;
END $$;

-- 3. Checks --------------------------------------------------------------------------------

ALTER TABLE public.genome_references
  DROP CONSTRAINT IF EXISTS genome_references_name_check,
  ADD CONSTRAINT genome_references_name_check CHECK (public.genome_name_ok(name)),
  DROP CONSTRAINT IF EXISTS genome_references_description_check,
  ADD CONSTRAINT genome_references_description_check CHECK (length(description) <= 500),
  DROP CONSTRAINT IF EXISTS genome_references_next_version_check,
  ADD CONSTRAINT genome_references_next_version_check CHECK (next_version >= 1);

ALTER TABLE public.genome_reference_versions
  DROP CONSTRAINT IF EXISTS genome_reference_versions_version_check,
  ADD CONSTRAINT genome_reference_versions_version_check CHECK (version >= 1),
  DROP CONSTRAINT IF EXISTS genome_reference_versions_status_check,
  ADD CONSTRAINT genome_reference_versions_status_check
    CHECK (status IN ('uploading', 'ready', 'abandoned', 'withdrawn')),
  DROP CONSTRAINT IF EXISTS genome_reference_versions_fasta_sha256_check,
  ADD CONSTRAINT genome_reference_versions_fasta_sha256_check
    CHECK (fasta_sha256 ~ '^[0-9a-f]{64}$'),
  DROP CONSTRAINT IF EXISTS genome_reference_versions_gtf_sha256_check,
  ADD CONSTRAINT genome_reference_versions_gtf_sha256_check CHECK (gtf_sha256 ~ '^[0-9a-f]{64}$'),
  DROP CONSTRAINT IF EXISTS genome_reference_versions_fasta_bytes_check,
  ADD CONSTRAINT genome_reference_versions_fasta_bytes_check CHECK (fasta_bytes > 0),
  DROP CONSTRAINT IF EXISTS genome_reference_versions_gtf_bytes_check,
  ADD CONSTRAINT genome_reference_versions_gtf_bytes_check CHECK (gtf_bytes > 0),
  DROP CONSTRAINT IF EXISTS genome_reference_versions_assembly_check,
  ADD CONSTRAINT genome_reference_versions_assembly_check CHECK (length(assembly) <= 200),
  DROP CONSTRAINT IF EXISTS genome_reference_versions_annotation_check,
  ADD CONSTRAINT genome_reference_versions_annotation_check CHECK (length(annotation) <= 200),
  DROP CONSTRAINT IF EXISTS genome_reference_versions_source_url_check,
  ADD CONSTRAINT genome_reference_versions_source_url_check CHECK (length(source_url) <= 2048),
  DROP CONSTRAINT IF EXISTS genome_reference_versions_notes_check,
  ADD CONSTRAINT genome_reference_versions_notes_check CHECK (length(notes) <= 4000),
  -- A ready or withdrawn version has both checksums and sizes and ready_at; any other has none.
  DROP CONSTRAINT IF EXISTS genome_reference_versions_finished_check,
  ADD CONSTRAINT genome_reference_versions_finished_check CHECK (
    CASE WHEN status IN ('ready', 'withdrawn') THEN
      num_nulls(fasta_sha256, fasta_bytes, gtf_sha256, gtf_bytes, ready_at) = 0
    ELSE
      num_nonnulls(fasta_sha256, fasta_bytes, gtf_sha256, gtf_bytes, ready_at) = 0
    END
  ),
  -- Only a withdrawn version has a reason and a time, and the reason is not blank.
  DROP CONSTRAINT IF EXISTS genome_reference_versions_withdrawn_check,
  ADD CONSTRAINT genome_reference_versions_withdrawn_check CHECK (
    CASE WHEN status = 'withdrawn' THEN
      num_nulls(withdrawn_reason, withdrawn_at) = 0 AND btrim(withdrawn_reason) <> ''
    ELSE
      num_nonnulls(withdrawn_reason, withdrawn_at) = 0
    END
  );

-- 4. What may change -----------------------------------------------------------------------

-- A genome's name, species and creator are fixed; its next version number only goes up.
CREATE OR REPLACE FUNCTION public.genome_references_keep_identity()
RETURNS TRIGGER
LANGUAGE plpgsql
SET search_path = pg_catalog, public
AS $$
BEGIN
    IF NEW.id IS DISTINCT FROM OLD.id
       OR NEW.name IS DISTINCT FROM OLD.name
       OR NEW.species_id IS DISTINCT FROM OLD.species_id
       OR NEW.created_by IS DISTINCT FROM OLD.created_by
       OR NEW.created_at IS DISTINCT FROM OLD.created_at THEN
        RAISE EXCEPTION 'a genome''s name, species and creator cannot change'
            USING ERRCODE = '55000';
    END IF;
    IF NEW.next_version < OLD.next_version THEN
        RAISE EXCEPTION 'a genome''s version numbers are never reused' USING ERRCODE = '55000';
    END IF;
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS genome_references_keep_identity ON public.genome_references;
CREATE TRIGGER genome_references_keep_identity
    BEFORE UPDATE ON public.genome_references
    FOR EACH ROW EXECUTE FUNCTION public.genome_references_keep_identity();

-- A new version gets its genome's next number and the paths built from it, and starts as
-- uploading, whoever inserts it.
CREATE OR REPLACE FUNCTION public.genome_reference_versions_number()
RETURNS TRIGGER
LANGUAGE plpgsql
SET search_path = pg_catalog, public
AS $$
DECLARE
    v_genome public.genome_references%ROWTYPE;
BEGIN
    IF NEW.status IS DISTINCT FROM 'uploading' THEN
        RAISE EXCEPTION 'a genome version starts as uploading' USING ERRCODE = '55000';
    END IF;
    SELECT * INTO v_genome FROM public.genome_references g WHERE g.id = NEW.genome_id FOR UPDATE;
    IF NOT FOUND THEN
        RAISE EXCEPTION 'no genome with id %', NEW.genome_id USING ERRCODE = '23503';
    END IF;
    NEW.version := v_genome.next_version;
    NEW.fasta_path := v_genome.name || '/v' || NEW.version || '/genome.fa.gz';
    NEW.gtf_path := v_genome.name || '/v' || NEW.version || '/genes.gtf.gz';
    UPDATE public.genome_references SET next_version = NEW.version + 1 WHERE id = v_genome.id;
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS genome_reference_versions_number ON public.genome_reference_versions;
CREATE TRIGGER genome_reference_versions_number
    BEFORE INSERT ON public.genome_reference_versions
    FOR EACH ROW EXECUTE FUNCTION public.genome_reference_versions_number();

-- A version's identity and sources never change. Its checksums, sizes and ready_at are set
-- once, when the upload is finished. Status moves only uploading -> ready | abandoned and
-- ready -> withdrawn. A ready or withdrawn version cannot be deleted.
CREATE OR REPLACE FUNCTION public.genome_reference_versions_guard()
RETURNS TRIGGER
LANGUAGE plpgsql
SET search_path = pg_catalog, public
AS $$
BEGIN
    IF TG_OP = 'DELETE' THEN
        IF OLD.status IN ('ready', 'withdrawn') THEN
            RAISE EXCEPTION 'genome version % is %; withdraw it instead of deleting it',
                OLD.id, OLD.status USING ERRCODE = '55000';
        END IF;
        RETURN OLD;
    END IF;

    IF NEW.id IS DISTINCT FROM OLD.id
       OR NEW.genome_id IS DISTINCT FROM OLD.genome_id
       OR NEW.version IS DISTINCT FROM OLD.version
       OR NEW.fasta_path IS DISTINCT FROM OLD.fasta_path
       OR NEW.gtf_path IS DISTINCT FROM OLD.gtf_path
       OR NEW.assembly IS DISTINCT FROM OLD.assembly
       OR NEW.annotation IS DISTINCT FROM OLD.annotation
       OR NEW.source_url IS DISTINCT FROM OLD.source_url
       OR NEW.notes IS DISTINCT FROM OLD.notes
       OR NEW.created_by IS DISTINCT FROM OLD.created_by
       OR NEW.created_at IS DISTINCT FROM OLD.created_at THEN
        RAISE EXCEPTION 'a genome version''s identity and sources cannot change'
            USING ERRCODE = '55000';
    END IF;

    IF OLD.status <> 'uploading' AND (
        NEW.fasta_sha256 IS DISTINCT FROM OLD.fasta_sha256
        OR NEW.fasta_bytes IS DISTINCT FROM OLD.fasta_bytes
        OR NEW.gtf_sha256 IS DISTINCT FROM OLD.gtf_sha256
        OR NEW.gtf_bytes IS DISTINCT FROM OLD.gtf_bytes
        OR NEW.ready_at IS DISTINCT FROM OLD.ready_at
    ) THEN
        RAISE EXCEPTION 'genome version % is %; its files cannot change', OLD.id, OLD.status
            USING ERRCODE = '55000';
    END IF;

    IF NEW.status IS DISTINCT FROM OLD.status AND (OLD.status, NEW.status) NOT IN (
        ('uploading', 'ready'), ('uploading', 'abandoned'), ('ready', 'withdrawn')
    ) THEN
        RAISE EXCEPTION 'genome version % cannot go from % to %', OLD.id, OLD.status, NEW.status
            USING ERRCODE = '55000';
    END IF;

    IF NEW.status = 'withdrawn' AND OLD.status = 'ready' THEN
        NEW.withdrawn_at := now();
    ELSIF NEW.withdrawn_reason IS DISTINCT FROM OLD.withdrawn_reason
          OR NEW.withdrawn_at IS DISTINCT FROM OLD.withdrawn_at THEN
        RAISE EXCEPTION 'a withdrawal is recorded only when a ready version is withdrawn'
            USING ERRCODE = '55000';
    END IF;

    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS genome_reference_versions_guard ON public.genome_reference_versions;
CREATE TRIGGER genome_reference_versions_guard
    BEFORE UPDATE OR DELETE ON public.genome_reference_versions
    FOR EACH ROW EXECUTE FUNCTION public.genome_reference_versions_guard();

-- 5. Access --------------------------------------------------------------------------------

ALTER TABLE public.genome_references ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.genome_reference_versions ENABLE ROW LEVEL SECURITY;

DO $$
DECLARE
  v_table TEXT;
BEGIN
  FOREACH v_table IN ARRAY ARRAY['genome_references', 'genome_reference_versions'] LOOP
    EXECUTE format('DROP POLICY IF EXISTS admin_all_%1$s ON public.%1$I', v_table);
    EXECUTE format(
      'CREATE POLICY admin_all_%1$s ON public.%1$I FOR ALL TO bloom_admin USING (true) WITH CHECK (true)',
      v_table
    );
    EXECUTE format('DROP POLICY IF EXISTS user_read_%1$s ON public.%1$I', v_table);
    EXECUTE format(
      'CREATE POLICY user_read_%1$s ON public.%1$I FOR SELECT TO bloom_user USING (true)', v_table
    );
    EXECUTE format('DROP POLICY IF EXISTS agent_read_%1$s ON public.%1$I', v_table);
    EXECUTE format(
      'CREATE POLICY agent_read_%1$s ON public.%1$I FOR SELECT TO bloom_agent USING (true)', v_table
    );
    EXECUTE format('DROP POLICY IF EXISTS workflows_read_%1$s ON public.%1$I', v_table);
    EXECUTE format(
      'CREATE POLICY workflows_read_%1$s ON public.%1$I FOR SELECT TO bloom_workflows USING (true)',
      v_table
    );

    -- Read for bloom_user (and so bloom_writer), bloom_agent and bloom_workflows; full access for
    -- bloom_admin. Writers change rows only through the upload functions.
    EXECUTE format(
      'REVOKE ALL ON public.%I FROM anon, authenticated, bloom_user, bloom_agent, bloom_writer, bloom_workflows',
      v_table
    );
    EXECUTE format('REVOKE UPDATE, DELETE, TRUNCATE ON public.%I FROM service_role', v_table);
    EXECUTE format('GRANT SELECT ON public.%I TO bloom_user, bloom_agent, bloom_workflows', v_table);
    EXECUTE format('GRANT SELECT, INSERT, UPDATE, DELETE ON public.%I TO bloom_admin', v_table);
  END LOOP;
END
$$;

REVOKE EXECUTE ON FUNCTION public.genome_references_keep_identity() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.genome_reference_versions_number() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.genome_reference_versions_guard() FROM PUBLIC, anon, authenticated;

COMMIT;
