-- 20261007041700_add_genome_references_and_run_genome_version.sql
--
-- Reference genomes for the Cell Ranger workflow, stored in Bloom with numbered versions.
-- A genome belongs to a species; each version holds one gzipped FASTA and one gzipped GTF in
-- the genome-references bucket, with their SHA-256 and size. A writer starts a version,
-- uploads both files, and finishes it, which makes the version ready for Cell Ranger runs.
-- A version's files and checksums never change once it is finished. A run records the genome
-- version it used in rnaseq_runs.genome_version_id.
-- Forward-only; rollback in supabase/rollbacks/.

BEGIN;

-- 1. genome_references -----------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.genome_references (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    -- The storage and cache folder name; a run names a version as <name>.v<N>.
    name TEXT NOT NULL
        CONSTRAINT genome_references_name_check
        CHECK (name ~ '^[A-Za-z0-9][A-Za-z0-9._-]{0,63}$' AND name !~ '__'),
    species_id BIGINT NOT NULL
        CONSTRAINT genome_references_species_id_fkey REFERENCES public.species (id),
    description TEXT
        CONSTRAINT genome_references_description_check CHECK (length(description) <= 500),
    created_by UUID NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT genome_references_name_key UNIQUE (name)
);

-- 2. genome_reference_versions ---------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.genome_reference_versions (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    genome_id BIGINT NOT NULL
        CONSTRAINT genome_reference_versions_genome_id_fkey
        REFERENCES public.genome_references (id),
    version INTEGER NOT NULL
        CONSTRAINT genome_reference_versions_version_check CHECK (version >= 1),
    status TEXT NOT NULL DEFAULT 'uploading'
        CONSTRAINT genome_reference_versions_status_check
        CHECK (status IN ('uploading', 'ready', 'abandoned')),
    -- Object names in the genome-references bucket.
    fasta_path TEXT NOT NULL,
    gtf_path TEXT NOT NULL,
    -- Of the gzipped bytes stored; set when the upload is finished.
    fasta_sha256 TEXT
        CONSTRAINT genome_reference_versions_fasta_sha256_check
        CHECK (fasta_sha256 ~ '^[0-9a-f]{64}$'),
    fasta_bytes BIGINT
        CONSTRAINT genome_reference_versions_fasta_bytes_check CHECK (fasta_bytes > 0),
    gtf_sha256 TEXT
        CONSTRAINT genome_reference_versions_gtf_sha256_check
        CHECK (gtf_sha256 ~ '^[0-9a-f]{64}$'),
    gtf_bytes BIGINT
        CONSTRAINT genome_reference_versions_gtf_bytes_check CHECK (gtf_bytes > 0),
    -- Where the files came from, e.g. TAIR10 / Araport11 and the download page.
    assembly TEXT
        CONSTRAINT genome_reference_versions_assembly_check CHECK (length(assembly) <= 200),
    annotation TEXT
        CONSTRAINT genome_reference_versions_annotation_check CHECK (length(annotation) <= 200),
    source_url TEXT
        CONSTRAINT genome_reference_versions_source_url_check CHECK (length(source_url) <= 2048),
    notes TEXT
        CONSTRAINT genome_reference_versions_notes_check CHECK (length(notes) <= 4000),
    created_by UUID NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    ready_at TIMESTAMPTZ,
    CONSTRAINT genome_reference_versions_genome_version_key UNIQUE (genome_id, version),
    -- A ready version has both checksums and sizes; an unfinished one has none.
    CONSTRAINT genome_reference_versions_finished_check CHECK (
        CASE WHEN status = 'ready' THEN
            num_nulls(fasta_sha256, fasta_bytes, gtf_sha256, gtf_bytes, ready_at) = 0
        ELSE
            num_nonnulls(fasta_sha256, fasta_bytes, gtf_sha256, gtf_bytes, ready_at) = 0
        END
    )
);

-- 3. The genome version a run used ---------------------------------------------------------

-- Empty for runs started before genome versions; a version used by a run cannot be deleted.
ALTER TABLE public.rnaseq_runs ADD COLUMN IF NOT EXISTS genome_version_id BIGINT;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conrelid = 'public.rnaseq_runs'::regclass
      AND conname = 'rnaseq_runs_genome_version_id_fkey'
  ) THEN
    ALTER TABLE public.rnaseq_runs
      ADD CONSTRAINT rnaseq_runs_genome_version_id_fkey
      FOREIGN KEY (genome_version_id) REFERENCES public.genome_reference_versions (id);
  END IF;
END
$$;

CREATE INDEX IF NOT EXISTS rnaseq_runs_genome_version_id_idx
    ON public.rnaseq_runs (genome_version_id);

-- 4. What may change ------------------------------------------------------------------------

-- A genome's name and species are fixed: its versions' paths are built from the name.
CREATE OR REPLACE FUNCTION public.genome_references_keep_identity()
RETURNS TRIGGER
LANGUAGE plpgsql
SET search_path = pg_catalog, public
AS $$
BEGIN
    IF NEW.id IS DISTINCT FROM OLD.id
       OR NEW.name IS DISTINCT FROM OLD.name
       OR NEW.species_id IS DISTINCT FROM OLD.species_id
       OR NEW.created_by IS DISTINCT FROM OLD.created_by
       OR NEW.created_at IS DISTINCT FROM OLD.created_at THEN
        RAISE EXCEPTION 'a genome''s name, species and creator cannot change'
            USING ERRCODE = '55000';
    END IF;
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS genome_references_keep_identity ON public.genome_references;
CREATE TRIGGER genome_references_keep_identity
    BEFORE UPDATE ON public.genome_references
    FOR EACH ROW EXECUTE FUNCTION public.genome_references_keep_identity();

-- A version's identity and source fields never change. Its checksums and sizes are set once,
-- when the upload is finished. Status only moves forward: uploading -> ready | abandoned.
CREATE OR REPLACE FUNCTION public.genome_reference_versions_guard()
RETURNS TRIGGER
LANGUAGE plpgsql
SET search_path = pg_catalog, public
AS $$
BEGIN
    IF NEW.id IS DISTINCT FROM OLD.id
       OR NEW.genome_id IS DISTINCT FROM OLD.genome_id
       OR NEW.version IS DISTINCT FROM OLD.version
       OR NEW.fasta_path IS DISTINCT FROM OLD.fasta_path
       OR NEW.gtf_path IS DISTINCT FROM OLD.gtf_path
       OR NEW.assembly IS DISTINCT FROM OLD.assembly
       OR NEW.annotation IS DISTINCT FROM OLD.annotation
       OR NEW.source_url IS DISTINCT FROM OLD.source_url
       OR NEW.notes IS DISTINCT FROM OLD.notes
       OR NEW.created_by IS DISTINCT FROM OLD.created_by
       OR NEW.created_at IS DISTINCT FROM OLD.created_at THEN
        RAISE EXCEPTION 'a genome version''s identity and sources cannot change'
            USING ERRCODE = '55000';
    END IF;

    IF OLD.status <> 'uploading' AND (
        NEW.fasta_sha256 IS DISTINCT FROM OLD.fasta_sha256
        OR NEW.fasta_bytes IS DISTINCT FROM OLD.fasta_bytes
        OR NEW.gtf_sha256 IS DISTINCT FROM OLD.gtf_sha256
        OR NEW.gtf_bytes IS DISTINCT FROM OLD.gtf_bytes
        OR NEW.ready_at IS DISTINCT FROM OLD.ready_at
    ) THEN
        RAISE EXCEPTION 'genome version % is %; its files cannot change', OLD.id, OLD.status
            USING ERRCODE = '55000';
    END IF;

    IF NEW.status IS DISTINCT FROM OLD.status AND (OLD.status, NEW.status) NOT IN (
        ('uploading', 'ready'), ('uploading', 'abandoned')
    ) THEN
        RAISE EXCEPTION 'genome version % cannot go from % to %', OLD.id, OLD.status, NEW.status
            USING ERRCODE = '55000';
    END IF;

    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS genome_reference_versions_guard ON public.genome_reference_versions;
CREATE TRIGGER genome_reference_versions_guard
    BEFORE UPDATE ON public.genome_reference_versions
    FOR EACH ROW EXECUTE FUNCTION public.genome_reference_versions_guard();

-- 5. Upload functions ------------------------------------------------------------------------

-- Starts the next version of a genome for the signed-in user, creating the genome when it is
-- new (p_species_id is then required). For an existing genome, a species or description given
-- must match the stored one. Returns the version and the two object names to upload to.
CREATE OR REPLACE FUNCTION public.start_genome_version(
    p_genome TEXT,
    p_species_id BIGINT DEFAULT NULL,
    p_description TEXT DEFAULT NULL,
    p_assembly TEXT DEFAULT NULL,
    p_annotation TEXT DEFAULT NULL,
    p_source_url TEXT DEFAULT NULL,
    p_notes TEXT DEFAULT NULL
) RETURNS TABLE(version_id BIGINT, version INTEGER, fasta_path TEXT, gtf_path TEXT)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
#variable_conflict use_column
DECLARE
    v_user UUID := auth.uid();
    v_genome public.genome_references%ROWTYPE;
    v_version INTEGER;
    v_row public.genome_reference_versions%ROWTYPE;
BEGIN
    IF v_user IS NULL THEN
        RAISE EXCEPTION 'sign in to upload a genome' USING ERRCODE = '42501';
    END IF;
    IF p_genome IS NULL OR p_genome !~ '^[A-Za-z0-9][A-Za-z0-9._-]{0,63}$' OR p_genome ~ '__' THEN
        RAISE EXCEPTION 'invalid genome name: %', p_genome USING ERRCODE = '22023';
    END IF;

    SELECT * INTO v_genome FROM public.genome_references g WHERE g.name = p_genome;
    IF NOT FOUND THEN
        IF p_species_id IS NULL THEN
            RAISE EXCEPTION 'genome % is new; give its species', p_genome USING ERRCODE = '22023';
        END IF;
        IF NOT EXISTS (
            SELECT 1 FROM public.species s WHERE s.id = p_species_id AND s.deleted_at IS NULL
        ) THEN
            RAISE EXCEPTION 'no species with id %', p_species_id USING ERRCODE = '22023';
        END IF;
        -- Another upload may create the same genome first; then this one uses it.
        INSERT INTO public.genome_references (name, species_id, description, created_by)
        VALUES (p_genome, p_species_id, p_description, v_user)
        ON CONFLICT (name) DO NOTHING;
    END IF;

    -- The row lock numbers concurrent uploads of one genome one after another.
    SELECT * INTO v_genome FROM public.genome_references g WHERE g.name = p_genome FOR UPDATE;
    IF p_species_id IS NOT NULL AND p_species_id <> v_genome.species_id THEN
        RAISE EXCEPTION 'genome % belongs to species %, not %',
            p_genome, v_genome.species_id, p_species_id USING ERRCODE = '22023';
    END IF;
    IF p_description IS NOT NULL AND p_description IS DISTINCT FROM v_genome.description THEN
        RAISE EXCEPTION 'genome % already has a different description', p_genome
            USING ERRCODE = '22023';
    END IF;

    SELECT coalesce(max(v.version), 0) + 1 INTO v_version
    FROM public.genome_reference_versions v WHERE v.genome_id = v_genome.id;

    INSERT INTO public.genome_reference_versions (
        genome_id, version, fasta_path, gtf_path,
        assembly, annotation, source_url, notes, created_by
    ) VALUES (
        v_genome.id, v_version,
        p_genome || '/v' || v_version || '/genome.fa.gz',
        p_genome || '/v' || v_version || '/genes.gtf.gz',
        p_assembly, p_annotation, p_source_url, p_notes, v_user
    )
    RETURNING * INTO v_row;

    RETURN QUERY SELECT v_row.id, v_row.version, v_row.fasta_path, v_row.gtf_path;
END;
$$;

-- Size of one stored object in the genome-references bucket, or NULL when it is not there.
CREATE OR REPLACE FUNCTION public._genome_object_bytes(p_name TEXT)
RETURNS BIGINT
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
    SELECT (o.metadata ->> 'size')::BIGINT
    FROM storage.objects o
    WHERE o.bucket_id = 'genome-references' AND o.name = p_name;
$$;

-- Finishes the signed-in user's upload: both objects must be stored with exactly the stated
-- sizes. Records the checksums and makes the version ready; returns its version number.
CREATE OR REPLACE FUNCTION public.finish_genome_version(
    p_version_id BIGINT,
    p_fasta_sha256 TEXT,
    p_fasta_bytes BIGINT,
    p_gtf_sha256 TEXT,
    p_gtf_bytes BIGINT
) RETURNS INTEGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
DECLARE
    v_user UUID := auth.uid();
    v_row public.genome_reference_versions%ROWTYPE;
    v_stored BIGINT;
BEGIN
    IF v_user IS NULL THEN
        RAISE EXCEPTION 'sign in to upload a genome' USING ERRCODE = '42501';
    END IF;

    SELECT * INTO v_row FROM public.genome_reference_versions v
    WHERE v.id = p_version_id FOR UPDATE;
    IF NOT FOUND THEN
        RAISE EXCEPTION 'no genome version %', p_version_id USING ERRCODE = '22023';
    END IF;
    IF v_row.created_by <> v_user THEN
        RAISE EXCEPTION 'genome version % was started by someone else', p_version_id
            USING ERRCODE = '42501';
    END IF;
    IF v_row.status <> 'uploading' THEN
        RAISE EXCEPTION 'genome version % is %, not uploading', p_version_id, v_row.status
            USING ERRCODE = '55000';
    END IF;

    IF p_fasta_sha256 IS NULL OR p_fasta_sha256 !~ '^[0-9a-f]{64}$'
       OR p_gtf_sha256 IS NULL OR p_gtf_sha256 !~ '^[0-9a-f]{64}$' THEN
        RAISE EXCEPTION 'checksums must be 64 lowercase hex characters' USING ERRCODE = '22023';
    END IF;
    IF p_fasta_bytes IS NULL OR p_fasta_bytes < 1 OR p_gtf_bytes IS NULL OR p_gtf_bytes < 1 THEN
        RAISE EXCEPTION 'sizes must be positive' USING ERRCODE = '22023';
    END IF;

    v_stored := public._genome_object_bytes(v_row.fasta_path);
    IF v_stored IS NULL THEN
        RAISE EXCEPTION '% has not been uploaded', v_row.fasta_path USING ERRCODE = '22023';
    ELSIF v_stored <> p_fasta_bytes THEN
        RAISE EXCEPTION '% is % bytes in storage, not %', v_row.fasta_path, v_stored, p_fasta_bytes
            USING ERRCODE = '22023';
    END IF;
    v_stored := public._genome_object_bytes(v_row.gtf_path);
    IF v_stored IS NULL THEN
        RAISE EXCEPTION '% has not been uploaded', v_row.gtf_path USING ERRCODE = '22023';
    ELSIF v_stored <> p_gtf_bytes THEN
        RAISE EXCEPTION '% is % bytes in storage, not %', v_row.gtf_path, v_stored, p_gtf_bytes
            USING ERRCODE = '22023';
    END IF;

    UPDATE public.genome_reference_versions
    SET status = 'ready',
        fasta_sha256 = p_fasta_sha256,
        fasta_bytes = p_fasta_bytes,
        gtf_sha256 = p_gtf_sha256,
        gtf_bytes = p_gtf_bytes,
        ready_at = now()
    WHERE id = v_row.id;

    RETURN v_row.version;
END;
$$;

-- Marks the signed-in user's unfinished upload abandoned; returns whether it changed.
CREATE OR REPLACE FUNCTION public.abandon_genome_version(p_version_id BIGINT)
RETURNS BOOLEAN
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
DECLARE
    v_user UUID := auth.uid();
    v_row public.genome_reference_versions%ROWTYPE;
BEGIN
    IF v_user IS NULL THEN
        RAISE EXCEPTION 'sign in to upload a genome' USING ERRCODE = '42501';
    END IF;

    SELECT * INTO v_row FROM public.genome_reference_versions v
    WHERE v.id = p_version_id FOR UPDATE;
    IF NOT FOUND THEN
        RAISE EXCEPTION 'no genome version %', p_version_id USING ERRCODE = '22023';
    END IF;
    IF v_row.created_by <> v_user THEN
        RAISE EXCEPTION 'genome version % was started by someone else', p_version_id
            USING ERRCODE = '42501';
    END IF;
    IF v_row.status = 'abandoned' THEN
        RETURN false;
    END IF;
    IF v_row.status <> 'uploading' THEN
        RAISE EXCEPTION 'genome version % is %, not uploading', p_version_id, v_row.status
            USING ERRCODE = '55000';
    END IF;

    UPDATE public.genome_reference_versions SET status = 'abandoned' WHERE id = v_row.id;
    RETURN true;
END;
$$;

-- 6. Access to the tables and functions ------------------------------------------------------

ALTER TABLE public.genome_references ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.genome_reference_versions ENABLE ROW LEVEL SECURITY;

DO $$
DECLARE
  v_table TEXT;
BEGIN
  FOREACH v_table IN ARRAY ARRAY['genome_references', 'genome_reference_versions'] LOOP
    EXECUTE format('DROP POLICY IF EXISTS admin_all_%1$s ON public.%1$I', v_table);
    EXECUTE format(
      'CREATE POLICY admin_all_%1$s ON public.%1$I FOR ALL TO bloom_admin USING (true) WITH CHECK (true)',
      v_table
    );
    EXECUTE format('DROP POLICY IF EXISTS user_read_%1$s ON public.%1$I', v_table);
    EXECUTE format(
      'CREATE POLICY user_read_%1$s ON public.%1$I FOR SELECT TO bloom_user USING (true)', v_table
    );
    EXECUTE format('DROP POLICY IF EXISTS agent_read_%1$s ON public.%1$I', v_table);
    EXECUTE format(
      'CREATE POLICY agent_read_%1$s ON public.%1$I FOR SELECT TO bloom_agent USING (true)', v_table
    );
    EXECUTE format('DROP POLICY IF EXISTS workflows_read_%1$s ON public.%1$I', v_table);
    EXECUTE format(
      'CREATE POLICY workflows_read_%1$s ON public.%1$I FOR SELECT TO bloom_workflows USING (true)',
      v_table
    );

    -- Read for bloom_user (and so bloom_writer), bloom_agent and bloom_workflows; full access for
    -- bloom_admin. Everyone else writes only through the functions above.
    EXECUTE format(
      'REVOKE ALL ON public.%I FROM anon, authenticated, bloom_user, bloom_agent, bloom_writer, bloom_workflows',
      v_table
    );
    EXECUTE format('REVOKE UPDATE, DELETE, TRUNCATE ON public.%I FROM service_role', v_table);
    EXECUTE format('GRANT SELECT ON public.%I TO bloom_user, bloom_agent, bloom_workflows', v_table);
    EXECUTE format('GRANT SELECT, INSERT, UPDATE, DELETE ON public.%I TO bloom_admin', v_table);
  END LOOP;
END
$$;

REVOKE EXECUTE ON FUNCTION public.genome_references_keep_identity() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.genome_reference_versions_guard() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public._genome_object_bytes(TEXT) FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.start_genome_version(TEXT, BIGINT, TEXT, TEXT, TEXT, TEXT, TEXT)
    FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.finish_genome_version(BIGINT, TEXT, BIGINT, TEXT, BIGINT)
    FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.abandon_genome_version(BIGINT)
    FROM PUBLIC, anon, authenticated;

-- bloomctl signs in as bloom_writer.
GRANT EXECUTE ON FUNCTION public.start_genome_version(TEXT, BIGINT, TEXT, TEXT, TEXT, TEXT, TEXT)
    TO bloom_writer;
GRANT EXECUTE ON FUNCTION public.finish_genome_version(BIGINT, TEXT, BIGINT, TEXT, BIGINT)
    TO bloom_writer;
GRANT EXECUTE ON FUNCTION public.abandon_genome_version(BIGINT) TO bloom_writer;

-- 7. The genome-references bucket ------------------------------------------------------------

-- Gzipped FASTA and GTF files of at most 500 MB, Storage's own per-object limit.
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
  VALUES ('genome-references', 'genome-references', false, 524288000,
          ARRAY['application/gzip'])
    ON CONFLICT (id) DO UPDATE
      SET public = false,
          file_size_limit = EXCLUDED.file_size_limit,
          allowed_mime_types = EXCLUDED.allowed_mime_types;

-- bloom_admin: full access (also through its blanket policy)
DROP POLICY IF EXISTS admin_all_genome_references ON storage.objects;
CREATE POLICY admin_all_genome_references ON storage.objects
    FOR ALL TO bloom_admin
    USING (bucket_id = 'genome-references')
    WITH CHECK (bucket_id = 'genome-references');

-- bloom_agent, bloom_user and bloom_workflows: read-only; the pipeline downloads with it
DROP POLICY IF EXISTS agent_read_genome_references ON storage.objects;
CREATE POLICY agent_read_genome_references ON storage.objects
    FOR SELECT TO bloom_agent
    USING (bucket_id = 'genome-references');

DROP POLICY IF EXISTS user_read_genome_references ON storage.objects;
CREATE POLICY user_read_genome_references ON storage.objects
    FOR SELECT TO bloom_user
    USING (bucket_id = 'genome-references');

DROP POLICY IF EXISTS workflows_read_genome_references ON storage.objects;
CREATE POLICY workflows_read_genome_references ON storage.objects
    FOR SELECT TO bloom_workflows
    USING (bucket_id = 'genome-references');

-- bloom_writer's blanket INSERT and UPDATE would let it write anywhere in this bucket. These
-- restrictive policies narrow it here only: it may add the two files of a version it started
-- that is still uploading, and may never overwrite or rename a file in this bucket.
DROP POLICY IF EXISTS writer_insert_own_genome_upload ON storage.objects;
CREATE POLICY writer_insert_own_genome_upload ON storage.objects
    AS RESTRICTIVE
    FOR INSERT TO bloom_writer
    WITH CHECK (
        bucket_id <> 'genome-references'
        OR EXISTS (
            SELECT 1 FROM public.genome_reference_versions v
            WHERE v.status = 'uploading'
              AND v.created_by = auth.uid()
              AND objects.name IN (v.fasta_path, v.gtf_path)
        )
    );

DROP POLICY IF EXISTS writer_no_genome_update ON storage.objects;
CREATE POLICY writer_no_genome_update ON storage.objects
    AS RESTRICTIVE
    FOR UPDATE TO bloom_writer
    USING (bucket_id <> 'genome-references')
    WITH CHECK (bucket_id <> 'genome-references');

COMMIT;
