-- Migration: scrna_joint_embedding
--
-- A joint embedding places the cells of several single-cell datasets in one
-- space, as SATURN does when it transfers labels from reference atlases to a
-- new dataset. This stores such a map: the embedding, its member datasets, the
-- labels it carries and one row per point. A dataset can be registered as a
-- reference, with no cells of its own, so an embedding can name it.
--
-- Additive: one column with a default on scrna_datasets, one constraint and one
-- trigger on scrna_cells, four new tables and two read functions.

BEGIN;

-- 1. Reference datasets ------------------------------------------------------------

ALTER TABLE public.scrna_datasets
  ADD COLUMN IF NOT EXISTS kind TEXT NOT NULL DEFAULT 'full';

ALTER TABLE public.scrna_datasets
  DROP CONSTRAINT IF EXISTS scrna_datasets_kind_valid;
ALTER TABLE public.scrna_datasets
  ADD CONSTRAINT scrna_datasets_kind_valid CHECK (kind IN ('full', 'reference'));

COMMENT ON COLUMN public.scrna_datasets.kind IS
  'full: a dataset the explorer opens, with its own cells and map. reference: '
  'registered so a joint embedding can name it (species, name, url, cell count); '
  'it holds no cells, and n_cells is the atlas''s own size.';

-- A point keys its cell on (dataset_id, cell_id), so it can only link to a cell
-- of its own dataset. id is already unique, so no existing row can violate this.
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
     WHERE conrelid = 'public.scrna_cells'::regclass
       AND conname = 'scrna_cells_id_per_dataset'
       AND pg_get_constraintdef(oid) = 'UNIQUE (dataset_id, id)'
  ) THEN
    ALTER TABLE public.scrna_cells DROP CONSTRAINT IF EXISTS scrna_cells_id_per_dataset;
    ALTER TABLE public.scrna_cells
      ADD CONSTRAINT scrna_cells_id_per_dataset UNIQUE (dataset_id, id);
  END IF;
END $$;

-- A reference dataset holds no cells. SECURITY DEFINER so the check also sees a
-- dataset the inserting role's policies would hide.
CREATE OR REPLACE FUNCTION public.scrna_cells_refuse_reference_dataset()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  dataset_name TEXT;
BEGIN
  SELECT d.name INTO dataset_name
    FROM public.scrna_datasets d
   WHERE d.id = NEW.dataset_id AND d.kind = 'reference';
  IF FOUND THEN
    RAISE EXCEPTION 'dataset % (%) is a reference and holds no cells',
      NEW.dataset_id, dataset_name
      USING ERRCODE = 'check_violation';
  END IF;
  RETURN NEW;
END $$;

REVOKE EXECUTE ON FUNCTION public.scrna_cells_refuse_reference_dataset()
  FROM PUBLIC, anon, authenticated;

DROP TRIGGER IF EXISTS scrna_cells_refuse_reference_dataset ON public.scrna_cells;
CREATE TRIGGER scrna_cells_refuse_reference_dataset
  BEFORE INSERT OR UPDATE OF dataset_id ON public.scrna_cells
  FOR EACH ROW EXECUTE FUNCTION public.scrna_cells_refuse_reference_dataset();


-- 2. The embedding ------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.scrna_embeddings (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name            TEXT NOT NULL,
  title           TEXT NOT NULL,
  description     TEXT,
  method          TEXT NOT NULL,
  run_name        TEXT,
  params          JSONB NOT NULL DEFAULT '{}'::jsonb,
  source_checksum TEXT NOT NULL,
  n_points        INTEGER NOT NULL,
  created_by      UUID DEFAULT auth.uid(),
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  ingested_at     TIMESTAMPTZ,
  CONSTRAINT scrna_embeddings_name_unique UNIQUE (name),
  CONSTRAINT scrna_embeddings_text_not_blank CHECK (
    btrim(name, E' \t\n\r\f ') <> '' AND
    btrim(title, E' \t\n\r\f ') <> '' AND
    btrim(method, E' \t\n\r\f ') <> ''
  ),
  CONSTRAINT scrna_embeddings_lengths CHECK (
    length(name) <= 200 AND length(title) <= 200 AND length(description) <= 2000 AND
    length(method) <= 100 AND length(run_name) <= 200
  ),
  CONSTRAINT scrna_embeddings_checksum_is_sha256 CHECK (source_checksum ~ '^[0-9a-f]{64}$'),
  CONSTRAINT scrna_embeddings_points_positive CHECK (n_points > 0),
  CONSTRAINT scrna_embeddings_params_is_object CHECK (jsonb_typeof(params) = 'object')
);

ALTER TABLE public.scrna_embeddings ENABLE ROW LEVEL SECURITY;

COMMENT ON TABLE public.scrna_embeddings IS
  'One joint embedding of several single-cell datasets, such as a SATURN '
  'integration. Belongs to no dataset; its datasets are its members.';
COMMENT ON COLUMN public.scrna_embeddings.name IS
  'Unique key the loader finds the embedding by. title is what readers see.';
COMMENT ON COLUMN public.scrna_embeddings.params IS
  'Provenance: the run''s notes and source files, and the loader''s options.';
COMMENT ON COLUMN public.scrna_embeddings.source_checksum IS
  'SHA-256 of the file the points were loaded from; a stopped load resumes '
  'only from the same file.';
COMMENT ON COLUMN public.scrna_embeddings.ingested_at IS
  'Set once every point is stored. Until then readers see no map.';


-- 3. Its member datasets ------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.scrna_embedding_members (
  embedding_id BIGINT NOT NULL,
  dataset_id   BIGINT NOT NULL,
  role         TEXT NOT NULL,
  ordinal      SMALLINT NOT NULL,
  n_points     INTEGER NOT NULL,
  CONSTRAINT scrna_embedding_members_pkey PRIMARY KEY (embedding_id, dataset_id),
  CONSTRAINT scrna_embedding_members_ordinal_unique UNIQUE (embedding_id, ordinal),
  CONSTRAINT scrna_embedding_members_embedding_fkey FOREIGN KEY (embedding_id)
    REFERENCES public.scrna_embeddings (id) ON DELETE CASCADE,
  CONSTRAINT scrna_embedding_members_dataset_fkey FOREIGN KEY (dataset_id)
    REFERENCES public.scrna_datasets (id) ON DELETE RESTRICT,
  CONSTRAINT scrna_embedding_members_role_valid CHECK (role IN ('reference', 'query')),
  CONSTRAINT scrna_embedding_members_ordinal_range CHECK (ordinal >= 0),
  CONSTRAINT scrna_embedding_members_points_positive CHECK (n_points > 0)
);

-- The dataset delete check and the soft-delete guard look members up by dataset.
CREATE INDEX IF NOT EXISTS scrna_embedding_members_dataset_idx
  ON public.scrna_embedding_members (dataset_id);

ALTER TABLE public.scrna_embedding_members ENABLE ROW LEVEL SECURITY;

COMMENT ON COLUMN public.scrna_embedding_members.role IS
  'reference: an atlas whose own labels anchor the space. query: a dataset whose '
  'labels were transferred from the references.';
COMMENT ON COLUMN public.scrna_embedding_members.ordinal IS
  'The member''s order in the embedding; the read function reports each point''s '
  'member by it.';


-- 4. The labels it carries ------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.scrna_embedding_labels (
  embedding_id      BIGINT NOT NULL,
  key               TEXT NOT NULL,
  source_column     TEXT NOT NULL,
  description       TEXT,
  native_dataset_id BIGINT,
  CONSTRAINT scrna_embedding_labels_pkey PRIMARY KEY (embedding_id, key),
  CONSTRAINT scrna_embedding_labels_embedding_fkey FOREIGN KEY (embedding_id)
    REFERENCES public.scrna_embeddings (id) ON DELETE CASCADE,
  CONSTRAINT scrna_embedding_labels_native_member_fkey
    FOREIGN KEY (embedding_id, native_dataset_id)
    REFERENCES public.scrna_embedding_members (embedding_id, dataset_id) ON DELETE CASCADE,
  CONSTRAINT scrna_embedding_labels_key_shape
    CHECK (key ~ '^[a-z][a-z0-9_]{0,63}$' AND key <> 'genotype'),
  CONSTRAINT scrna_embedding_labels_lengths
    CHECK (length(source_column) BETWEEN 1 AND 200 AND length(description) <= 1000)
);

ALTER TABLE public.scrna_embedding_labels ENABLE ROW LEVEL SECURITY;

COMMENT ON TABLE public.scrna_embedding_labels IS
  'The labels an embedding''s points carry. A label is native to one member: on '
  'that member''s points it is the atlas''s own, on any other member''s it was '
  'transferred. No native member means a label derived for the embedding itself.';
COMMENT ON COLUMN public.scrna_embedding_labels.key IS
  'Named by the scheme it comes from (shahan_cell_type, nuclei_cell_type), so a '
  'label never reads as universal. genotype is reserved: it is read from a '
  'linked cell''s genotype.';


-- 5. Its points ----------------------------------------------------------------------

-- A point's labels: the cells' rule, and never genotype, which comes from a linked
-- cell. Its own function, so the CHECK does not pin scrna_facets_are_flat_text.
CREATE OR REPLACE FUNCTION public.scrna_embedding_point_labels_ok(facets JSONB)
RETURNS BOOLEAN
LANGUAGE sql
IMMUTABLE
PARALLEL SAFE
AS $fn$
  SELECT public.scrna_facets_are_flat_text(facets)
     AND NOT coalesce(facets ? 'genotype', false);
$fn$;

-- A CHECK runs with the inserting role's privileges.
REVOKE EXECUTE ON FUNCTION public.scrna_embedding_point_labels_ok(JSONB) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.scrna_embedding_point_labels_ok(JSONB)
  TO authenticated, bloom_writer, bloom_admin, service_role, postgres;

CREATE TABLE IF NOT EXISTS public.scrna_embedding_points (
  embedding_id BIGINT NOT NULL,
  ordinal      INTEGER NOT NULL,
  dataset_id   BIGINT NOT NULL,
  barcode      TEXT NOT NULL,
  cell_id      BIGINT,
  x            REAL NOT NULL,
  y            REAL NOT NULL,
  facets       JSONB,
  CONSTRAINT scrna_embedding_points_pkey PRIMARY KEY (embedding_id, ordinal),
  CONSTRAINT scrna_embedding_points_barcode_unique UNIQUE (embedding_id, dataset_id, barcode),
  -- cell_id first, so this also serves the check when a cell is deleted.
  CONSTRAINT scrna_embedding_points_cell_unique UNIQUE (cell_id, embedding_id),
  CONSTRAINT scrna_embedding_points_member_fkey FOREIGN KEY (embedding_id, dataset_id)
    REFERENCES public.scrna_embedding_members (embedding_id, dataset_id) ON DELETE CASCADE,
  CONSTRAINT scrna_embedding_points_cell_fkey FOREIGN KEY (dataset_id, cell_id)
    REFERENCES public.scrna_cells (dataset_id, id) ON DELETE RESTRICT,
  CONSTRAINT scrna_embedding_points_ordinal_range CHECK (ordinal >= 0),
  CONSTRAINT scrna_embedding_points_barcode_length CHECK (length(barcode) BETWEEN 1 AND 200),
  -- Postgres treats NaN as equal to itself, so NOT IN catches it.
  CONSTRAINT scrna_embedding_points_position_finite CHECK (
    x NOT IN ('NaN'::real, 'Infinity'::real, '-Infinity'::real) AND
    y NOT IN ('NaN'::real, 'Infinity'::real, '-Infinity'::real)
  ),
  CONSTRAINT scrna_embedding_points_facets_are_flat_text CHECK (
    public.scrna_embedding_point_labels_ok(facets)
  )
);

ALTER TABLE public.scrna_embedding_points ENABLE ROW LEVEL SECURITY;

COMMENT ON TABLE public.scrna_embedding_points IS
  'One row per point of a joint map, in the embedding''s own order.';
COMMENT ON COLUMN public.scrna_embedding_points.cell_id IS
  'The point''s cell, for a member whose cells Bloom holds. Its genotype and any '
  'label the point does not carry are read from the cell.';
COMMENT ON CONSTRAINT scrna_embedding_points_cell_fkey ON public.scrna_embedding_points IS
  'A cell in a joint map cannot be deleted: reloading a dataset''s cells means '
  'removing its joint maps first, deliberately.';


-- 6. Guards across tables ------------------------------------------------------------

-- A dataset with cells cannot become a reference, and a dataset in a joint map
-- cannot be soft-deleted while the map still draws it.
CREATE OR REPLACE FUNCTION public.scrna_datasets_guard_embedding_rules()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
BEGIN
  IF NEW.kind = 'reference' AND OLD.kind IS DISTINCT FROM 'reference'
     AND EXISTS (SELECT 1 FROM public.scrna_cells c WHERE c.dataset_id = NEW.id) THEN
    RAISE EXCEPTION 'dataset % holds cells, so it cannot be a reference', NEW.id
      USING ERRCODE = 'check_violation';
  END IF;
  IF NEW.deleted_at IS NOT NULL AND OLD.deleted_at IS NULL
     AND EXISTS (SELECT 1 FROM public.scrna_embedding_members m WHERE m.dataset_id = NEW.id) THEN
    RAISE EXCEPTION 'dataset % is in a joint embedding; remove the embedding first', NEW.id
      USING ERRCODE = 'check_violation';
  END IF;
  RETURN NEW;
END $$;

REVOKE EXECUTE ON FUNCTION public.scrna_datasets_guard_embedding_rules()
  FROM PUBLIC, anon, authenticated;

DROP TRIGGER IF EXISTS scrna_datasets_guard_embedding_rules ON public.scrna_datasets;
CREATE TRIGGER scrna_datasets_guard_embedding_rules
  BEFORE UPDATE OF kind, deleted_at ON public.scrna_datasets
  FOR EACH ROW EXECUTE FUNCTION public.scrna_datasets_guard_embedding_rules();

-- An embedding is finished only when every point it counts, and every point each
-- member counts, is stored.
CREATE OR REPLACE FUNCTION public.scrna_embeddings_check_finished()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = ''
AS $$
DECLARE
  stored BIGINT;
  short_member BIGINT;
BEGIN
  IF NEW.ingested_at IS NULL THEN
    RETURN NEW;
  END IF;
  SELECT count(*) INTO stored
    FROM public.scrna_embedding_points p WHERE p.embedding_id = NEW.id;
  IF stored <> NEW.n_points THEN
    RAISE EXCEPTION 'embedding % counts % points but holds %', NEW.id, NEW.n_points, stored
      USING ERRCODE = 'check_violation';
  END IF;
  SELECT m.dataset_id INTO short_member
    FROM public.scrna_embedding_members m
   WHERE m.embedding_id = NEW.id
     AND m.n_points <> (SELECT count(*) FROM public.scrna_embedding_points p
                         WHERE p.embedding_id = m.embedding_id
                           AND p.dataset_id = m.dataset_id)
   LIMIT 1;
  IF FOUND THEN
    RAISE EXCEPTION 'embedding %: dataset % does not hold the points its member row counts',
      NEW.id, short_member
      USING ERRCODE = 'check_violation';
  END IF;
  RETURN NEW;
END $$;

REVOKE EXECUTE ON FUNCTION public.scrna_embeddings_check_finished()
  FROM PUBLIC, anon, authenticated;

DROP TRIGGER IF EXISTS scrna_embeddings_check_finished ON public.scrna_embeddings;
CREATE TRIGGER scrna_embeddings_check_finished
  BEFORE INSERT OR UPDATE OF ingested_at, n_points ON public.scrna_embeddings
  FOR EACH ROW EXECUTE FUNCTION public.scrna_embeddings_check_finished();


-- 7. Reading a map ----------------------------------------------------------------------

-- Every point of a finished embedding, as one row of arrays in point order: one
-- request for the whole map, each field named once rather than once per point.
-- An unfinished or unknown embedding gives no row.
CREATE OR REPLACE FUNCTION public.scrna_embedding_arrays(emb_id BIGINT)
RETURNS TABLE (
  x              REAL[],
  y              REAL[],
  member_ordinal SMALLINT[],
  cell_id        BIGINT[]
)
LANGUAGE sql
STABLE
SECURITY INVOKER
SET search_path = ''
AS $$
  SELECT
    array_agg(p.x ORDER BY p.ordinal),
    array_agg(p.y ORDER BY p.ordinal),
    array_agg(m.ordinal ORDER BY p.ordinal),
    array_agg(p.cell_id ORDER BY p.ordinal)
  FROM public.scrna_embedding_points p
  JOIN public.scrna_embeddings e
    ON e.id = p.embedding_id AND e.ingested_at IS NOT NULL
  JOIN public.scrna_embedding_members m
    ON m.embedding_id = p.embedding_id AND m.dataset_id = p.dataset_id
  WHERE p.embedding_id = emb_id
  HAVING count(*) > 0;
$$;

-- One label for every point, in point order: its distinct values, sorted, and each
-- point's index into them (-1 for none). A point's own label comes first, then its
-- linked cell's; genotype is the linked cell's genotype.
CREATE OR REPLACE FUNCTION public.scrna_embedding_label_codes(emb_id BIGINT, label_key TEXT)
RETURNS TABLE (
  levels TEXT[],
  codes  SMALLINT[]
)
LANGUAGE plpgsql
STABLE
SECURITY INVOKER
SET search_path = ''
AS $$
DECLARE
  found_levels TEXT[];
  found_codes  INTEGER[];
BEGIN
  WITH vals AS (
    SELECT p.ordinal,
           CASE WHEN label_key = 'genotype' THEN g.name
                ELSE COALESCE(p.facets ->> label_key, c.facets ->> label_key)
           END AS value
      FROM public.scrna_embedding_points p
      JOIN public.scrna_embeddings e
        ON e.id = p.embedding_id AND e.ingested_at IS NOT NULL
      LEFT JOIN public.scrna_cells c
        ON c.dataset_id = p.dataset_id AND c.id = p.cell_id
      LEFT JOIN public.scrna_genotypes g
        ON g.dataset_id = c.dataset_id AND g.id = c.genotype_id
     WHERE p.embedding_id = emb_id
  ), coded AS (
    SELECT ordinal, value,
           CASE WHEN value IS NULL THEN -1
                ELSE (dense_rank() OVER (PARTITION BY value IS NULL
                                         ORDER BY value COLLATE "C") - 1)::INTEGER
           END AS code
      FROM vals
  )
  SELECT array_agg(DISTINCT value COLLATE "C" ORDER BY value COLLATE "C")
           FILTER (WHERE value IS NOT NULL),
         array_agg(code ORDER BY ordinal)
    INTO found_levels, found_codes
    FROM coded;

  IF found_codes IS NULL THEN
    RETURN;
  END IF;
  IF coalesce(array_length(found_levels, 1), 0) > 32767 THEN
    RAISE EXCEPTION 'label % has % values, more than a map can colour',
      label_key, array_length(found_levels, 1)
      USING ERRCODE = 'program_limit_exceeded';
  END IF;
  levels := coalesce(found_levels, '{}'::TEXT[]);
  codes := found_codes::SMALLINT[];
  RETURN NEXT;
END $$;


-- 8. Access -----------------------------------------------------------------------------
-- Signed-in readers read, as on the differential expression results: no anon
-- policy, and the embedding's provenance (file paths) stays off the public API.
-- The writer loads an embedding and marks it finished, and cannot change it after.

DO $$
DECLARE
  t TEXT;
BEGIN
  FOREACH t IN ARRAY ARRAY['scrna_embeddings', 'scrna_embedding_members',
                           'scrna_embedding_labels', 'scrna_embedding_points'] LOOP
    EXECUTE format('DROP POLICY IF EXISTS admin_all_%1$s ON public.%1$I', t);
    EXECUTE format('CREATE POLICY admin_all_%1$s ON public.%1$I FOR ALL TO bloom_admin '
                   'USING (true) WITH CHECK (true)', t);
    EXECUTE format('DROP POLICY IF EXISTS user_read_%1$s ON public.%1$I', t);
    EXECUTE format('CREATE POLICY user_read_%1$s ON public.%1$I FOR SELECT TO bloom_user '
                   'USING (true)', t);
    EXECUTE format('DROP POLICY IF EXISTS agent_read_%1$s ON public.%1$I', t);
    EXECUTE format('CREATE POLICY agent_read_%1$s ON public.%1$I FOR SELECT TO bloom_agent '
                   'USING (true)', t);
  END LOOP;

  -- Members, labels and points go only into an embedding still being loaded.
  FOREACH t IN ARRAY ARRAY['scrna_embedding_members', 'scrna_embedding_labels',
                           'scrna_embedding_points'] LOOP
    EXECUTE format('DROP POLICY IF EXISTS writer_insert_%1$s ON public.%1$I', t);
    EXECUTE format('CREATE POLICY writer_insert_%1$s ON public.%1$I FOR INSERT TO bloom_writer '
                   'WITH CHECK (EXISTS (SELECT 1 FROM public.scrna_embeddings e '
                   'WHERE e.id = embedding_id AND e.ingested_at IS NULL))', t);
  END LOOP;
END $$;

DROP POLICY IF EXISTS writer_insert_scrna_embeddings ON public.scrna_embeddings;
CREATE POLICY writer_insert_scrna_embeddings
  ON public.scrna_embeddings FOR INSERT TO bloom_writer
  WITH CHECK (ingested_at IS NULL);

-- Only ingested_at is granted, and only on an unfinished embedding.
DROP POLICY IF EXISTS writer_finish_scrna_embeddings ON public.scrna_embeddings;
CREATE POLICY writer_finish_scrna_embeddings
  ON public.scrna_embeddings FOR UPDATE TO bloom_writer
  USING (ingested_at IS NULL) WITH CHECK (true);

-- New tables start with Supabase's default grants (everything to anon,
-- authenticated and service_role) and the role migrations' defaults. Those come
-- away, and what each role needs is granted explicitly.
REVOKE ALL ON public.scrna_embeddings, public.scrna_embedding_members,
              public.scrna_embedding_labels, public.scrna_embedding_points
  FROM anon, authenticated, bloom_user, bloom_agent, bloom_writer;
REVOKE UPDATE, DELETE, TRUNCATE ON public.scrna_embeddings, public.scrna_embedding_members,
              public.scrna_embedding_labels, public.scrna_embedding_points
  FROM service_role;

GRANT SELECT ON public.scrna_embeddings, public.scrna_embedding_members,
                public.scrna_embedding_labels, public.scrna_embedding_points
  TO bloom_user, bloom_agent;
GRANT SELECT, INSERT ON public.scrna_embeddings, public.scrna_embedding_members,
                        public.scrna_embedding_labels, public.scrna_embedding_points
  TO bloom_writer;
GRANT UPDATE (ingested_at) ON public.scrna_embeddings TO bloom_writer;
GRANT SELECT, INSERT, UPDATE, DELETE
  ON public.scrna_embeddings, public.scrna_embedding_members,
     public.scrna_embedding_labels, public.scrna_embedding_points
  TO bloom_admin;

REVOKE EXECUTE ON FUNCTION public.scrna_embedding_arrays(BIGINT),
                           public.scrna_embedding_label_codes(BIGINT, TEXT)
  FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.scrna_embedding_arrays(BIGINT),
                          public.scrna_embedding_label_codes(BIGINT, TEXT)
  TO bloom_user, bloom_agent, bloom_admin;

COMMIT;
