-- Maps a (experiment, plate, optional session) to a time-lapse video stored
-- in the graviscan-videos bucket.
--
--
-- Uniqueness: one canonical video per (experiment, plate, session). The
-- COALESCE indexing pattern mirrors gravi_scan_metadata_accession.

CREATE TABLE gravi_plate_videos (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    experiment_id BIGINT NOT NULL REFERENCES gravi_experiments(id) ON DELETE CASCADE,
    plate_id TEXT NOT NULL,
    session_id BIGINT REFERENCES gravi_scan_sessions(id) ON DELETE SET NULL,
    object_path TEXT NOT NULL,
    duration_seconds INT,
    frame_count INT,
    file_size_bytes BIGINT,
    file_hash TEXT,
    generated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX idx_gravi_plate_videos_unique
    ON gravi_plate_videos (experiment_id, plate_id, COALESCE(session_id, -1));

CREATE INDEX idx_gravi_plate_videos_experiment
    ON gravi_plate_videos (experiment_id);

ALTER TABLE gravi_plate_videos ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS admin_all_gravi_plate_videos ON public.gravi_plate_videos;
CREATE POLICY admin_all_gravi_plate_videos ON public.gravi_plate_videos
    FOR ALL TO bloom_admin USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS agent_read_gravi_plate_videos ON public.gravi_plate_videos;
CREATE POLICY agent_read_gravi_plate_videos ON public.gravi_plate_videos
    FOR SELECT TO bloom_agent USING (true);

DROP POLICY IF EXISTS user_read_gravi_plate_videos ON public.gravi_plate_videos;
CREATE POLICY user_read_gravi_plate_videos ON public.gravi_plate_videos
    FOR SELECT TO bloom_user USING (true);

DROP POLICY IF EXISTS user_insert_gravi_plate_videos ON public.gravi_plate_videos;
CREATE POLICY user_insert_gravi_plate_videos ON public.gravi_plate_videos
    FOR INSERT TO bloom_user WITH CHECK (true);

DROP POLICY IF EXISTS user_update_gravi_plate_videos ON public.gravi_plate_videos;
CREATE POLICY user_update_gravi_plate_videos ON public.gravi_plate_videos
    FOR UPDATE TO bloom_user USING (true);
