-- 20260825172704_create_scrna_de_runs.sql
--
-- Section 1 of the on-demand scRNA differential-expression change: `scrna_de_results`
-- (the cache catalog, one row per distinct question) and `scrna_de_runs` (one row per
-- triggered comparison), plus the `scrna_de_dispatch` pgmq queue and the six
-- SECURITY DEFINER functions that own every status transition.
--
-- `scrna_de_results` is created FIRST: `scrna_de_runs.result_id` references it. The
-- reference points run -> result (never the reverse) so a result outlives the run that
-- produced it, which is what makes the cache a cache.
--
-- `group_a`/`group_b` hold `scrna_clusters.cluster_id` — the stable key under that table's
-- UNIQUE (dataset_id, cluster_id) — and NOT `scrna_clusters.name`, its optional and freely
-- renameable display label. Both are text and look interchangeable, but they are not: these
-- two columns are part of the results cache key, so keying on `name` would silently orphan
-- every cached result for a dataset the moment someone tidied up a cluster name.
--
-- Derived artifacts go in their own `scrna-de` bucket, NOT in `scrna`. `scrna` holds the
-- per-gene count objects, which are the primary expression data and are not reproducible
-- from anything in this repo, the buckets, or the database. The DE container runs inside
-- the cluster; giving it write access to that bucket would put irreplaceable source data
-- one bug away from being overwritten. It reads `scrna` and writes `scrna-de`, and the two
-- also want different retention — everything in `scrna-de` is regenerable by re-running.
--
-- This migration also creates the `bloom_scrna_de` role. The DE container writes back from
-- INSIDE the cluster, where `bloom_workflows`'s credential does not and should not reach,
-- so it gets its own identity — and `complete_`/`fail_scrna_de_run` are granted to both.
-- The role must exist here because a GRANT to a non-existent role is a hard error; the
-- matching app user and K8s Secret are provisioned later, outside any migration.
--
-- No role but `bloom_admin` gets UPDATE on either table. Every transition goes through a
-- SECURITY DEFINER function, so the writable surface is those six signatures and nothing
-- else. The explicit REVOKE from PUBLIC, anon, AND authenticated (not just PUBLIC) is
-- load-bearing: Supabase's default privileges grant EXECUTE on every new public-schema
-- function to anon/authenticated directly.
--
-- Forward-only + additive; companion manual rollback under supabase/rollbacks/.
-- Idempotent for a re-runnable `supabase db push`: CREATE TABLE IF NOT EXISTS,
-- DROP POLICY IF EXISTS before each CREATE POLICY, existence-guarded pgmq.create and
-- ALTER PUBLICATION.

BEGIN;

-- 1. bloom_scrna_de role -------------------------------------------------------

DO $$
BEGIN
  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'bloom_scrna_de') THEN
    CREATE ROLE bloom_scrna_de NOLOGIN;
  END IF;
END
$$;

GRANT bloom_scrna_de TO authenticator;
GRANT USAGE ON SCHEMA public TO bloom_scrna_de;

-- 2. scrna_de_results ----------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.scrna_de_results (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    dataset_id BIGINT NOT NULL REFERENCES public.scrna_datasets(id),
    group_a TEXT NOT NULL,
    group_b TEXT NOT NULL,
    method TEXT NOT NULL,
    params_hash TEXT NOT NULL,
    -- Object key within the `scrna-de` bucket; the bucket is implied, not stored.
    file_path TEXT NOT NULL,
    n_genes_tested INTEGER,
    computed_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT scrna_de_results_question_key
        UNIQUE (dataset_id, group_a, group_b, method, params_hash)
);

ALTER TABLE public.scrna_de_results ENABLE ROW LEVEL SECURITY;

-- 3. scrna_de_runs -------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.scrna_de_runs (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    dataset_id BIGINT NOT NULL REFERENCES public.scrna_datasets(id),
    group_a TEXT NOT NULL,
    group_b TEXT NOT NULL,
    method TEXT NOT NULL,
    params JSONB NOT NULL DEFAULT '{}'::jsonb,
    params_hash TEXT NOT NULL,
    -- Attribution only. Deliberately NOT a visibility filter: scrna_* is shared
    -- scientific data and every reader role sees every run.
    requested_by UUID,
    status TEXT NOT NULL DEFAULT 'queued'
        CHECK (status IN ('queued', 'submitted', 'running', 'complete', 'failed')),
    argo_workflow_name TEXT,
    result_id BIGINT REFERENCES public.scrna_de_results(id),
    error_message TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    submitted_at TIMESTAMPTZ,
    completed_at TIMESTAMPTZ
);

ALTER TABLE public.scrna_de_runs ENABLE ROW LEVEL SECURITY;

-- The poller's sweep predicate: every run still in flight.
CREATE INDEX IF NOT EXISTS scrna_de_runs_active_idx
    ON public.scrna_de_runs (status)
    WHERE status IN ('submitted', 'running');

-- 4. RLS policies + grants -----------------------------------------------------
--
-- scrna_* is shared scientific data, so every reader role reads everything. The
-- asymmetry is on the write side: bloom_workflows may INSERT a run and nothing more,
-- and its INSERT is column-scoped to exactly what the trigger route populates — so a
-- future bug in that route cannot set `status = 'complete'` or forge an
-- `argo_workflow_name` by including extra columns.

DROP POLICY IF EXISTS admin_all_scrna_de_results ON public.scrna_de_results;
CREATE POLICY admin_all_scrna_de_results ON public.scrna_de_results
  FOR ALL TO bloom_admin USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS read_scrna_de_results ON public.scrna_de_results;
CREATE POLICY read_scrna_de_results ON public.scrna_de_results
  FOR SELECT TO anon, authenticated, bloom_user, bloom_agent, bloom_workflows
  USING (true);

DROP POLICY IF EXISTS admin_all_scrna_de_runs ON public.scrna_de_runs;
CREATE POLICY admin_all_scrna_de_runs ON public.scrna_de_runs
  FOR ALL TO bloom_admin USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS read_scrna_de_runs ON public.scrna_de_runs;
CREATE POLICY read_scrna_de_runs ON public.scrna_de_runs
  FOR SELECT TO anon, authenticated, bloom_user, bloom_agent, bloom_workflows
  USING (true);

DROP POLICY IF EXISTS workflows_insert_scrna_de_runs ON public.scrna_de_runs;
CREATE POLICY workflows_insert_scrna_de_runs ON public.scrna_de_runs
  FOR INSERT TO bloom_workflows WITH CHECK (true);

GRANT SELECT ON public.scrna_de_results TO anon, authenticated, bloom_user, bloom_agent, bloom_workflows;
GRANT SELECT ON public.scrna_de_runs    TO anon, authenticated, bloom_user, bloom_agent, bloom_workflows;
GRANT ALL    ON public.scrna_de_results TO bloom_admin;
GRANT ALL    ON public.scrna_de_runs    TO bloom_admin;

-- Column-scoped: every other column is the SECURITY DEFINER functions' to write.
GRANT INSERT (dataset_id, group_a, group_b, method, params, params_hash, requested_by, status)
  ON public.scrna_de_runs TO bloom_workflows;

GRANT USAGE, SELECT ON SEQUENCE public.scrna_de_runs_id_seq TO bloom_workflows;

-- 5. scrna-de bucket -----------------------------------------------------------
--
-- Readable by everyone who can read scrna_* data; writable ONLY by bloom_scrna_de and
-- bloom_admin. Deliberately narrower than the `scrna` bucket, whose 2024 policies let any
-- authenticated user INSERT — a new bucket is a chance not to inherit that.

INSERT INTO storage.buckets (id, name)
  VALUES ('scrna-de', 'scrna-de')
  ON CONFLICT DO NOTHING;

DROP POLICY IF EXISTS read_scrna_de_bucket ON storage.objects;
CREATE POLICY read_scrna_de_bucket ON storage.objects
  FOR SELECT TO anon, authenticated, bloom_user, bloom_agent, bloom_workflows, bloom_scrna_de
  USING (bucket_id = 'scrna-de');

DROP POLICY IF EXISTS scrna_de_write_bucket ON storage.objects;
CREATE POLICY scrna_de_write_bucket ON storage.objects
  FOR INSERT TO bloom_scrna_de
  WITH CHECK (bucket_id = 'scrna-de');

-- The matrix cache is rewritten in place on a re-run, so UPDATE is needed alongside INSERT.
DROP POLICY IF EXISTS scrna_de_update_bucket ON storage.objects;
CREATE POLICY scrna_de_update_bucket ON storage.objects
  FOR UPDATE TO bloom_scrna_de
  USING (bucket_id = 'scrna-de') WITH CHECK (bucket_id = 'scrna-de');

DROP POLICY IF EXISTS admin_all_scrna_de_bucket ON storage.objects;
CREATE POLICY admin_all_scrna_de_bucket ON storage.objects
  FOR ALL TO bloom_admin
  USING (bucket_id = 'scrna-de') WITH CHECK (bucket_id = 'scrna-de');

-- Read-only on the SOURCE bucket: the container needs the per-gene count objects, and
-- must never be able to write them. No INSERT/UPDATE policy on 'scrna' for this role.
DROP POLICY IF EXISTS scrna_de_read_source_bucket ON storage.objects;
CREATE POLICY scrna_de_read_source_bucket ON storage.objects
  FOR SELECT TO bloom_scrna_de
  USING (bucket_id = 'scrna');

GRANT SELECT ON storage.buckets TO bloom_scrna_de;
GRANT SELECT, INSERT, UPDATE ON storage.objects TO bloom_scrna_de;

-- 6. Dispatch queue ------------------------------------------------------------

DO $$
BEGIN
  IF NOT EXISTS (SELECT FROM pgmq.list_queues() WHERE queue_name = 'scrna_de_dispatch') THEN
    PERFORM pgmq.create('scrna_de_dispatch');
  END IF;
END
$$;

-- 7. Status transitions --------------------------------------------------------
--
-- One message per run, not per batch: a DE comparison is a single indivisible
-- computation over one matrix, so there is nothing to fan out. The queue still earns
-- its place by keeping submission off the request path — a cluster blip leaves work
-- enqueued rather than failing the caller.

CREATE OR REPLACE FUNCTION public.enqueue_scrna_de_run(p_run_id BIGINT)
RETURNS BIGINT
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public, pgmq
AS $$
DECLARE
    v_msg_id BIGINT;
BEGIN
    IF NOT EXISTS (SELECT 1 FROM public.scrna_de_runs WHERE id = p_run_id) THEN
        RAISE EXCEPTION 'scrna_de_run % does not exist', p_run_id;
    END IF;

    SELECT pgmq.send('scrna_de_dispatch', jsonb_build_object('run_id', p_run_id))
      INTO v_msg_id;

    RETURN v_msg_id;
END;
$$;

REVOKE EXECUTE ON FUNCTION public.enqueue_scrna_de_run(BIGINT) FROM PUBLIC, anon, authenticated;
GRANT  EXECUTE ON FUNCTION public.enqueue_scrna_de_run(BIGINT) TO bloom_workflows;

-- fail: terminal, and idempotent. Defined before claim() because claim() delegates to
-- it for dead-lettering. p_msg_id is optional — the worker holds one, the DE container
-- (whose message was already deleted at submit time) does not.
CREATE OR REPLACE FUNCTION public.fail_scrna_de_run(
    p_run_id BIGINT,
    p_error TEXT,
    p_msg_id BIGINT DEFAULT NULL
) RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public, pgmq
AS $$
BEGIN
    UPDATE public.scrna_de_runs
    SET status = 'failed',
        error_message = p_error,
        completed_at = now()
    WHERE id = p_run_id
      -- Never re-fail a settled run: a late fail must not clobber the
      -- completed_at of a run that already succeeded.
      AND status NOT IN ('complete', 'failed');

    IF p_msg_id IS NOT NULL THEN
        PERFORM pgmq.archive('scrna_de_dispatch', p_msg_id);
    END IF;
END;
$$;

REVOKE EXECUTE ON FUNCTION public.fail_scrna_de_run(BIGINT, TEXT, BIGINT) FROM PUBLIC, anon, authenticated;
GRANT  EXECUTE ON FUNCTION public.fail_scrna_de_run(BIGINT, TEXT, BIGINT) TO bloom_workflows, bloom_scrna_de;

-- claim: read one message, hand the worker everything it needs to build the Workflow
-- body without a second query.
CREATE OR REPLACE FUNCTION public.claim_scrna_de_run(
    p_vt INTEGER DEFAULT 60,
    p_max_reads INTEGER DEFAULT 5
) RETURNS TABLE(
    run_id BIGINT,
    dataset_id BIGINT,
    group_a TEXT,
    group_b TEXT,
    method TEXT,
    params JSONB,
    params_hash TEXT,
    msg_id BIGINT
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public, pgmq
AS $$
DECLARE
    r pgmq.message_record;
    v_run_id BIGINT;
BEGIN
    SELECT * INTO r FROM pgmq.read('scrna_de_dispatch', p_vt, 1) LIMIT 1;
    IF NOT FOUND THEN
        RETURN;  -- empty queue
    END IF;

    v_run_id := (r.message->>'run_id')::BIGINT;

    -- Poison-message guard: every prior claimant crashed before calling submit or
    -- fail. Dead-letter via fail_scrna_de_run, which archives the message and settles
    -- the run — the same outcome an explicit fail produces.
    IF r.read_ct > p_max_reads THEN
        PERFORM public.fail_scrna_de_run(
            v_run_id,
            format('dead-lettered after %s deliveries (poison message)', r.read_ct),
            r.msg_id
        );
        RETURN;
    END IF;

    RETURN QUERY
    SELECT d.id, d.dataset_id, d.group_a, d.group_b, d.method, d.params, d.params_hash, r.msg_id
    FROM public.scrna_de_runs d
    WHERE d.id = v_run_id;
END;
$$;

REVOKE EXECUTE ON FUNCTION public.claim_scrna_de_run(INTEGER, INTEGER) FROM PUBLIC, anon, authenticated;
GRANT  EXECUTE ON FUNCTION public.claim_scrna_de_run(INTEGER, INTEGER) TO bloom_workflows;

-- submit: the worker's success path. Records the Workflow name and deletes the message,
-- so by the time the container reports back there is no message left to settle.
CREATE OR REPLACE FUNCTION public.submit_scrna_de_run(
    p_run_id BIGINT,
    p_msg_id BIGINT,
    p_argo_workflow_name TEXT
) RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public, pgmq
AS $$
BEGIN
    UPDATE public.scrna_de_runs
    SET argo_workflow_name = p_argo_workflow_name,
        status = 'submitted',
        submitted_at = now()
    WHERE id = p_run_id
      -- A delayed submit for a message another claimant already dead-lettered must
      -- not resurrect the run: recording a workflow name on a 'failed' row would
      -- produce a self-contradictory record.
      AND status = 'queued';

    PERFORM pgmq.delete('scrna_de_dispatch', p_msg_id);
END;
$$;

REVOKE EXECUTE ON FUNCTION public.submit_scrna_de_run(BIGINT, BIGINT, TEXT) FROM PUBLIC, anon, authenticated;
GRANT  EXECUTE ON FUNCTION public.submit_scrna_de_run(BIGINT, BIGINT, TEXT) TO bloom_workflows;

-- complete: the DE container's success path, called from inside the cluster.
--
-- The caller passes only the run id and what it produced; the cache key is read from
-- the run row rather than re-supplied. That is deliberate — it makes it impossible for
-- a container to file its result under a different question than the one it was asked.
CREATE OR REPLACE FUNCTION public.complete_scrna_de_run(
    p_run_id BIGINT,
    p_file_path TEXT,
    p_n_genes_tested INTEGER DEFAULT NULL
) RETURNS BIGINT
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public, pgmq
AS $$
DECLARE
    v_run public.scrna_de_runs%ROWTYPE;
    v_result_id BIGINT;
BEGIN
    SELECT * INTO v_run FROM public.scrna_de_runs WHERE id = p_run_id;
    IF NOT FOUND THEN
        RAISE EXCEPTION 'scrna_de_run % does not exist', p_run_id;
    END IF;

    -- The result is keyed by the question, not by the run, so it is written even when
    -- the run below turns out to have been dead-lettered: the computation really
    -- happened and the next caller should get it from cache. ON CONFLICT handles two
    -- runs racing on the same question.
    INSERT INTO public.scrna_de_results
        (dataset_id, group_a, group_b, method, params_hash, file_path, n_genes_tested)
    VALUES
        (v_run.dataset_id, v_run.group_a, v_run.group_b, v_run.method, v_run.params_hash,
         p_file_path, p_n_genes_tested)
    ON CONFLICT ON CONSTRAINT scrna_de_results_question_key
    DO UPDATE SET file_path = EXCLUDED.file_path,
                  n_genes_tested = EXCLUDED.n_genes_tested,
                  computed_at = now()
    RETURNING id INTO v_result_id;

    UPDATE public.scrna_de_runs
    SET result_id = v_result_id,
        status = 'complete',
        completed_at = now()
    WHERE id = p_run_id
      -- Same non-resurrection rule as submit(): a run already dead-lettered stays
      -- failed, even though its result is now cached above.
      AND status <> 'failed';

    RETURN v_result_id;
END;
$$;

REVOKE EXECUTE ON FUNCTION public.complete_scrna_de_run(BIGINT, TEXT, INTEGER) FROM PUBLIC, anon, authenticated;
GRANT  EXECUTE ON FUNCTION public.complete_scrna_de_run(BIGINT, TEXT, INTEGER) TO bloom_workflows, bloom_scrna_de;

-- update_status: the poller's only write.
--
-- The WHERE clause is what makes the poller safe to run at any cadence: it can only
-- move a run that is still in flight. The instant the container calls complete/fail,
-- the run leaves this predicate, so a slow sweep holding a stale Argo phase can never
-- overwrite a real result.
CREATE OR REPLACE FUNCTION public.update_scrna_de_run_status(
    p_run_id BIGINT,
    p_status TEXT,
    p_error TEXT DEFAULT NULL
) RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public, pgmq
AS $$
BEGIN
    IF p_status NOT IN ('running', 'failed') THEN
        RAISE EXCEPTION 'update_scrna_de_run_status may only set running or failed, got %', p_status;
    END IF;

    UPDATE public.scrna_de_runs
    SET status = p_status,
        error_message = COALESCE(p_error, error_message),
        completed_at = CASE WHEN p_status = 'failed' THEN now() ELSE completed_at END
    WHERE id = p_run_id
      AND status IN ('submitted', 'running');
END;
$$;

REVOKE EXECUTE ON FUNCTION public.update_scrna_de_run_status(BIGINT, TEXT, TEXT) FROM PUBLIC, anon, authenticated;
GRANT  EXECUTE ON FUNCTION public.update_scrna_de_run_status(BIGINT, TEXT, TEXT) TO bloom_workflows;

-- 8. Realtime ------------------------------------------------------------------
-- The UI subscribes to its own run's status transitions rather than polling.

DO $$
BEGIN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.scrna_de_runs;
EXCEPTION
    WHEN duplicate_object THEN NULL;
END
$$;

COMMIT;
