-- gravi_scan_metadata_sections: one row per section within a plate's metadata.
-- A "section" is a contiguous region of the plate (e.g. quadrant or strip) that
-- holds a different growth medium or genotype. ON DELETE CASCADE so deleting
-- the parent accession metadata removes its sections.

CREATE TABLE gravi_scan_metadata_sections (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    metadata_id BIGINT NOT NULL REFERENCES gravi_scan_metadata_accession(id) ON DELETE CASCADE,
    plate_section_id TEXT NOT NULL,
    medium TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (metadata_id, plate_section_id)
);

ALTER TABLE gravi_scan_metadata_sections ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS admin_all_gravi_scan_metadata_sections ON public.gravi_scan_metadata_sections;
CREATE POLICY admin_all_gravi_scan_metadata_sections ON public.gravi_scan_metadata_sections
    FOR ALL TO bloom_admin USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS agent_read_gravi_scan_metadata_sections ON public.gravi_scan_metadata_sections;
CREATE POLICY agent_read_gravi_scan_metadata_sections ON public.gravi_scan_metadata_sections
    FOR SELECT TO bloom_agent USING (true);

DROP POLICY IF EXISTS user_read_gravi_scan_metadata_sections ON public.gravi_scan_metadata_sections;
CREATE POLICY user_read_gravi_scan_metadata_sections ON public.gravi_scan_metadata_sections
    FOR SELECT TO bloom_user USING (true);

DROP POLICY IF EXISTS user_insert_gravi_scan_metadata_sections ON public.gravi_scan_metadata_sections;
CREATE POLICY user_insert_gravi_scan_metadata_sections ON public.gravi_scan_metadata_sections
    FOR INSERT TO bloom_user WITH CHECK (true);

DROP POLICY IF EXISTS user_update_gravi_scan_metadata_sections ON public.gravi_scan_metadata_sections;
CREATE POLICY user_update_gravi_scan_metadata_sections ON public.gravi_scan_metadata_sections
    FOR UPDATE TO bloom_user USING (true);
