-- 20260929192029_create_rnaseq_samples_and_references.sql
--
-- The samples and references an RNA-seq job can be started with, so the job form can
-- offer them as choices instead of reading the bucket. A sample is one folder of
-- FASTQs under raw_reads/, a reference one folder under reference_genome/. Rows are
-- added by an admin now, and by the SRA and IGC imports later.
-- Forward-only; rollback in supabase/rollbacks/.

BEGIN;

-- 1. rnaseq_samples ----------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.rnaseq_samples (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    -- The raw_reads/ folder name; also Cell Ranger's run id, so its rule applies.
    name TEXT NOT NULL
        CONSTRAINT rnaseq_samples_name_check
        CHECK (name ~ '^[A-Za-z0-9][A-Za-z0-9_-]{0,63}$' AND name !~ '__'),
    -- Where the FASTQs came from before they reached S3.
    source TEXT NOT NULL DEFAULT 's3'
        CONSTRAINT rnaseq_samples_source_check
        CHECK (source IN ('s3', 'igc', 'sra')),
    -- The IGC folder URL or SRA accession it was copied from; NULL for s3.
    source_ref TEXT,
    fastq_count INTEGER CONSTRAINT rnaseq_samples_fastq_count_check CHECK (fastq_count >= 0),
    total_bytes BIGINT CONSTRAINT rnaseq_samples_total_bytes_check CHECK (total_bytes >= 0),
    registered_by UUID,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT rnaseq_samples_name_key UNIQUE (name)
);

-- 2. rnaseq_references ---------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.rnaseq_references (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    -- The reference_genome/ folder name, which holds reference.json.
    name TEXT NOT NULL
        CONSTRAINT rnaseq_references_name_check
        CHECK (name ~ '^[A-Za-z0-9][A-Za-z0-9._-]{0,99}$' AND name !~ '__'),
    -- Shown next to the name in the job form, e.g. the genome and annotation versions.
    description TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT rnaseq_references_name_key UNIQUE (name)
);

-- 3. Access --------------------------------------------------------------------------

ALTER TABLE public.rnaseq_samples ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.rnaseq_references ENABLE ROW LEVEL SECURITY;

DO $$
DECLARE
  v_table TEXT;
BEGIN
  FOREACH v_table IN ARRAY ARRAY['rnaseq_samples', 'rnaseq_references'] LOOP
    EXECUTE format('DROP POLICY IF EXISTS admin_all_%1$s ON public.%1$I', v_table);
    EXECUTE format(
      'CREATE POLICY admin_all_%1$s ON public.%1$I FOR ALL TO bloom_admin USING (true) WITH CHECK (true)',
      v_table
    );
    EXECUTE format('DROP POLICY IF EXISTS user_read_%1$s ON public.%1$I', v_table);
    EXECUTE format(
      'CREATE POLICY user_read_%1$s ON public.%1$I FOR SELECT TO bloom_user USING (true)', v_table
    );
    EXECUTE format('DROP POLICY IF EXISTS agent_read_%1$s ON public.%1$I', v_table);
    EXECUTE format(
      'CREATE POLICY agent_read_%1$s ON public.%1$I FOR SELECT TO bloom_agent USING (true)', v_table
    );
    EXECUTE format('DROP POLICY IF EXISTS workflows_read_%1$s ON public.%1$I', v_table);
    EXECUTE format(
      'CREATE POLICY workflows_read_%1$s ON public.%1$I FOR SELECT TO bloom_workflows USING (true)',
      v_table
    );

    -- Read for bloom_user, bloom_agent and bloom_workflows; full access for bloom_admin.
    EXECUTE format(
      'REVOKE ALL ON public.%I FROM anon, authenticated, bloom_user, bloom_agent, bloom_writer, bloom_workflows',
      v_table
    );
    EXECUTE format('REVOKE UPDATE, DELETE, TRUNCATE ON public.%I FROM service_role', v_table);
    EXECUTE format('GRANT SELECT ON public.%I TO bloom_user, bloom_agent, bloom_workflows', v_table);
    EXECUTE format('GRANT SELECT, INSERT, UPDATE, DELETE ON public.%I TO bloom_admin', v_table);
  END LOOP;
END
$$;

COMMIT;
