-- Migration: scrna_cells_genotype_and_labels
--
-- Let the map show one genotype at a time, and show or hide cells by any label
-- the ingest was told to load.
--
-- Three things arrive together because they are one change to one query.
--
-- 1. A genotype is a record, not a string on every cell.
--
--    `scrna_cells.replicate` currently holds Col-0, pFACT and pHORST on the
--    first dataset to use it. Those are genotypes: Col-0 is the wild-type
--    accession, the other two are the MYB41 promoter constructs. Meanwhile
--    scripts/backfill_scrna_cluster_catalog.sql puts a genuine replicate token
--    in that same column for other datasets, so grouping by it already means
--    different things depending on which loader wrote the rows.
--
--    A record carries the metadata once instead of on 8,683 rows, points at the
--    accession the platform already models so Col-0 is the same Col-0 as
--    everywhere else, and gives a differential expression row two sides that can
--    be joined rather than matched by spelling.
--
--    `replicate` stays and its meaning narrows to what it says. Nothing is
--    rewritten here: a dataset whose `replicate` holds a genotype keeps it until
--    its ingest is re-run, and one whose `replicate` holds a real replicate is
--    unaffected either way.
--
-- 2. Cells carry labels the map can filter on -- transgene status first. JSONB
--    on the cell rather than a table of its own: these are per-dataset,
--    open-ended, and only ever displayed and filtered. A table would buy a join
--    and rows-per-cell-per-label for nothing, until a label needs metadata of its
--    own.
--
-- 3. The cell query returns both, alongside the position it already returned.
--    That is the point of doing this in one migration. Everything the explorer
--    fetches is paired with cells by position and carries no cell identifiers, so
--    a second query returning genotypes or labels in its own order could attach
--    every one of them to the wrong cell and look entirely normal. One row, one
--    query, one ORDER BY, nothing to get out of step.

BEGIN;

-- ─── 1. Genotypes ────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS public.scrna_genotypes (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  dataset_id   BIGINT  NOT NULL REFERENCES public.scrna_datasets (id),
  name         TEXT    NOT NULL,
  -- The accession this genotype is, where the platform has a record of it. Null
  -- is honest for a construct that is not an accession in its own right.
  accession_id BIGINT  REFERENCES public.arabidopsis_accessions (id),
  -- Named by whoever runs the ingest, never inferred: a dataset whose wild type
  -- is not called Col-0 would be guessed wrong.
  is_control   BOOLEAN NOT NULL DEFAULT false,
  -- The construct a transgenic line carries. A property of the line, which is
  -- why no cell column records it.
  construct    TEXT,
  notes        TEXT,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
  -- One row per genotype per dataset, so a cell's genotype cannot be ambiguous
  -- and a re-ingest lands on the row it made last time.
  CONSTRAINT scrna_genotypes_one_per_dataset UNIQUE (dataset_id, name),
  -- NULL is the only way to say nothing. The character set is spelled out rather
  -- than relying on btrim()'s default, which strips spaces alone.
  CONSTRAINT scrna_genotypes_name_not_blank
    CHECK (btrim(name, E' \t\n\r\f\v ') <> ''),
  CONSTRAINT scrna_genotypes_construct_not_blank
    CHECK (construct IS NULL OR btrim(construct, E' \t\n\r\f\v ') <> '')
);

CREATE INDEX IF NOT EXISTS idx_scrna_genotypes_dataset
  ON public.scrna_genotypes (dataset_id);

-- RESTRICT rather than CASCADE: removing a genotype that still has cells should
-- be refused, not take the cells with it.
ALTER TABLE public.scrna_cells
  ADD COLUMN IF NOT EXISTS genotype_id BIGINT;
ALTER TABLE public.scrna_cells
  DROP CONSTRAINT IF EXISTS scrna_cells_genotype_fkey;
ALTER TABLE public.scrna_cells
  ADD CONSTRAINT scrna_cells_genotype_fkey
  FOREIGN KEY (genotype_id) REFERENCES public.scrna_genotypes (id)
  ON DELETE RESTRICT;

CREATE INDEX IF NOT EXISTS idx_scrna_cells_genotype
  ON public.scrna_cells (genotype_id);

-- ─── 2. Labels ───────────────────────────────────────────────────────────────

ALTER TABLE public.scrna_cells
  ADD COLUMN IF NOT EXISTS facets JSONB DEFAULT NULL;

-- An object of short strings is the only shape the explorer can render as
-- toggles; anything else -- an array, a number, a nested object -- would arrive
-- in the browser as something it cannot draw. Through a function because a CHECK
-- cannot hold a subquery, and walking the object needs one.
CREATE OR REPLACE FUNCTION public.scrna_facets_are_flat_text(facets JSONB)
RETURNS BOOLEAN
LANGUAGE sql
IMMUTABLE
PARALLEL SAFE
AS $fn$
  SELECT facets IS NULL
     OR (
       jsonb_typeof(facets) = 'object'
       AND NOT EXISTS (
         SELECT 1 FROM jsonb_each(facets) AS f(key, value)
         WHERE jsonb_typeof(f.value) <> 'string'
            OR btrim(f.key, E' \t\n\r\f\v ') = ''
            OR btrim(f.value #>> '{}', E' \t\n\r\f\v ') = ''
       )
     );
$fn$;

ALTER TABLE public.scrna_cells
  DROP CONSTRAINT IF EXISTS scrna_cells_facets_are_flat_text;
ALTER TABLE public.scrna_cells
  ADD CONSTRAINT scrna_cells_facets_are_flat_text
  CHECK (public.scrna_facets_are_flat_text(facets)) NOT VALID;

-- ─── 3. The cell query ───────────────────────────────────────────────────────

-- The return type changes, and CREATE OR REPLACE cannot do that.
DROP FUNCTION IF EXISTS public.scrna_cell_arrays(BIGINT);

CREATE FUNCTION public.scrna_cell_arrays(
  ds_id BIGINT
)
RETURNS TABLE (
  x               REAL,
  y               REAL,
  cluster_ordinal SMALLINT,
  genotype        TEXT,
  replicate       TEXT,
  facets          JSONB
)
LANGUAGE sql
STABLE
SECURITY INVOKER
AS $$
  SELECT
    c.x::REAL,
    c.y::REAL,
    COALESCE(cl.ordinal, 255::SMALLINT) AS cluster_ordinal,
    g.name AS genotype,
    c.replicate,
    c.facets
  FROM public.scrna_cells c
  LEFT JOIN public.scrna_clusters cl
    ON cl.dataset_id = c.dataset_id
   AND cl.cluster_id = c.cluster_id
  LEFT JOIN public.scrna_genotypes g
    ON g.id = c.genotype_id
  WHERE c.dataset_id = ds_id
  ORDER BY c.cell_number ASC;
$$;

GRANT EXECUTE ON FUNCTION public.scrna_cell_arrays(BIGINT)
  TO anon, authenticated, bloom_user, bloom_admin, bloom_agent;

-- ─── 4. Who may read the genotypes ───────────────────────────────────────────

ALTER TABLE public.scrna_genotypes ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Anon users can select scrna_genotypes" ON public.scrna_genotypes;
CREATE POLICY "Anon users can select scrna_genotypes"
  ON public.scrna_genotypes AS permissive FOR SELECT TO anon USING (true);

DROP POLICY IF EXISTS "Authenticated users can select scrna_genotypes" ON public.scrna_genotypes;
CREATE POLICY "Authenticated users can select scrna_genotypes"
  ON public.scrna_genotypes AS permissive FOR SELECT TO authenticated USING (true);

DROP POLICY IF EXISTS "admin_all_scrna_genotypes" ON public.scrna_genotypes;
CREATE POLICY "admin_all_scrna_genotypes"
  ON public.scrna_genotypes AS permissive FOR ALL TO bloom_admin
  USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "user_read_scrna_genotypes" ON public.scrna_genotypes;
CREATE POLICY "user_read_scrna_genotypes"
  ON public.scrna_genotypes AS permissive FOR SELECT TO bloom_user USING (true);

DROP POLICY IF EXISTS "agent_read_scrna_genotypes" ON public.scrna_genotypes;
CREATE POLICY "agent_read_scrna_genotypes"
  ON public.scrna_genotypes AS permissive FOR SELECT TO bloom_agent USING (true);

COMMIT;
