-- 20260730120000_create_cyl_pipeline_runs.sql
--
-- Phase 1 of bloom #11/#404 (the A4 pipeline-trigger route): `cyl_pipeline_runs`
-- (one row per POST /workflows/pipeline request; the Realtime subscription target)
-- and `cyl_pipeline_run_scans` (one row per enumerated scan within a run). This
-- migration also adds a pgmq dispatch queue (`cyl_pipeline_dispatch`) + a
-- least-privilege `enqueue_cyl_pipeline_batch` wrapper function, and the new
-- `bloom_workflows` grants this phase's route needs.
--
-- `bloom_workflows` gets SELECT + INSERT on both new tables — NOT UPDATE. This
-- phase's route only ever inserts; granting UPDATE now would be pre-emptive and
-- contradicts this repo's own convention (20260716000000_create_workflows_role.sql:
-- "expand explicitly as new endpoints need it"). A later phase (the dispatch
-- worker's status writes) adds its own small grant migration when that code lands.
--
-- `bloom_workflows` also gets a NEW read policy + column-scoped grant on the
-- EXISTING `cyl_scan_traits`/`cyl_trait_sources` tables, needed for the dedup
-- preview's all-sources join (cyl_scan_traits.scan_id -> source_id ->
-- cyl_trait_sources.id). This deliberately checks ALL of a scan's sources, not
-- just the most recent one (cyl-trait-read's `is_latest` rule answers a different
-- question — see the cyl-pipeline-trigger capability's dedup requirement).
--
-- pgmq queue: modeled on bloom PR #469's (unmerged) enqueue/claim/complete/fail
-- pattern as a REFERENCE only, not a code dependency. Phase 1 implements only the
-- enqueue side. The explicit REVOKE from PUBLIC, anon, AND authenticated (not just
-- PUBLIC) matters: Supabase's default privileges grant new public-schema functions
-- EXECUTE to anon/authenticated directly (#469's commit 0b91cd0 found this the hard
-- way).
--
-- Forward-only + additive; companion manual rollback under supabase/rollbacks/.
-- Idempotent for a re-runnable `supabase db push`: CREATE TABLE IF NOT EXISTS,
-- DROP POLICY IF EXISTS before each CREATE POLICY, existence-guarded pgmq.create,
-- idempotent ALTER PUBLICATION blocks.

BEGIN;

-- 1. cyl_pipeline_runs ---------------------------------------------------------

CREATE TABLE IF NOT EXISTS cyl_pipeline_runs (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    target_level TEXT NOT NULL CHECK (target_level IN ('scan', 'wave', 'experiment', 'scan_ids')),
    target_id BIGINT,
    params JSONB NOT NULL DEFAULT '{}'::jsonb,
    requested_by UUID,
    status TEXT NOT NULL DEFAULT 'queued'
        CHECK (status IN ('queued', 'submitted', 'running', 'complete', 'partial', 'failed')),
    scan_count INTEGER NOT NULL DEFAULT 0,
    done_count INTEGER NOT NULL DEFAULT 0,
    reused_count INTEGER NOT NULL DEFAULT 0,
    failed_count INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    submitted_at TIMESTAMPTZ,
    completed_at TIMESTAMPTZ,
    error_message TEXT
);

ALTER TABLE public.cyl_pipeline_runs ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS admin_all_cyl_pipeline_runs ON public.cyl_pipeline_runs;
CREATE POLICY admin_all_cyl_pipeline_runs ON public.cyl_pipeline_runs
    FOR ALL TO bloom_admin USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS agent_read_cyl_pipeline_runs ON public.cyl_pipeline_runs;
CREATE POLICY agent_read_cyl_pipeline_runs ON public.cyl_pipeline_runs
    FOR SELECT TO bloom_agent USING (true);

DROP POLICY IF EXISTS user_read_cyl_pipeline_runs ON public.cyl_pipeline_runs;
CREATE POLICY user_read_cyl_pipeline_runs ON public.cyl_pipeline_runs
    FOR SELECT TO bloom_user USING (true);

DROP POLICY IF EXISTS workflows_read_cyl_pipeline_runs ON public.cyl_pipeline_runs;
CREATE POLICY workflows_read_cyl_pipeline_runs ON public.cyl_pipeline_runs
    FOR SELECT TO bloom_workflows USING (true);

DROP POLICY IF EXISTS workflows_insert_cyl_pipeline_runs ON public.cyl_pipeline_runs;
CREATE POLICY workflows_insert_cyl_pipeline_runs ON public.cyl_pipeline_runs
    FOR INSERT TO bloom_workflows WITH CHECK (true);

GRANT SELECT ON public.cyl_pipeline_runs TO bloom_user, bloom_agent;
-- Column-scoped, not whole-table: exactly the columns pipeline.py's _insert_run
-- populates. Matches this repo's own precedent for the same role
-- (20260716000000_create_workflows_role.sql: GRANT INSERT (scan_id, path, frames)
-- ON cyl_scan_videos). The explicit REVOKE first keeps this idempotent across a
-- re-apply that started from an earlier, broader whole-table grant.
REVOKE INSERT ON public.cyl_pipeline_runs FROM bloom_workflows;
GRANT SELECT ON public.cyl_pipeline_runs TO bloom_workflows;
GRANT INSERT (target_level, target_id, params, requested_by, status, scan_count, reused_count)
    ON public.cyl_pipeline_runs TO bloom_workflows;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.cyl_pipeline_runs TO bloom_admin;

-- 2. cyl_pipeline_run_scans -----------------------------------------------------

CREATE TABLE IF NOT EXISTS cyl_pipeline_run_scans (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    run_id BIGINT NOT NULL REFERENCES cyl_pipeline_runs(id),
    scan_id BIGINT NOT NULL REFERENCES cyl_scans(id),
    batch_index INTEGER,
    argo_workflow_name TEXT,
    status TEXT NOT NULL DEFAULT 'queued'
        CHECK (status IN ('queued', 'predicted', 'written', 'reused', 'failed')),
    attempts INTEGER NOT NULL DEFAULT 0,
    source_id BIGINT REFERENCES cyl_trait_sources(id),
    error_message TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT cyl_pipeline_run_scans_run_scan_key UNIQUE (run_id, scan_id)
);

ALTER TABLE public.cyl_pipeline_run_scans ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS admin_all_cyl_pipeline_run_scans ON public.cyl_pipeline_run_scans;
CREATE POLICY admin_all_cyl_pipeline_run_scans ON public.cyl_pipeline_run_scans
    FOR ALL TO bloom_admin USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS agent_read_cyl_pipeline_run_scans ON public.cyl_pipeline_run_scans;
CREATE POLICY agent_read_cyl_pipeline_run_scans ON public.cyl_pipeline_run_scans
    FOR SELECT TO bloom_agent USING (true);

DROP POLICY IF EXISTS user_read_cyl_pipeline_run_scans ON public.cyl_pipeline_run_scans;
CREATE POLICY user_read_cyl_pipeline_run_scans ON public.cyl_pipeline_run_scans
    FOR SELECT TO bloom_user USING (true);

DROP POLICY IF EXISTS workflows_read_cyl_pipeline_run_scans ON public.cyl_pipeline_run_scans;
CREATE POLICY workflows_read_cyl_pipeline_run_scans ON public.cyl_pipeline_run_scans
    FOR SELECT TO bloom_workflows USING (true);

DROP POLICY IF EXISTS workflows_insert_cyl_pipeline_run_scans ON public.cyl_pipeline_run_scans;
CREATE POLICY workflows_insert_cyl_pipeline_run_scans ON public.cyl_pipeline_run_scans
    FOR INSERT TO bloom_workflows WITH CHECK (true);

GRANT SELECT ON public.cyl_pipeline_run_scans TO bloom_user, bloom_agent;
-- Column-scoped, not whole-table — see the matching comment on cyl_pipeline_runs
-- above. Excludes argo_workflow_name/attempts/source_id/error_message, none of
-- which this phase's code writes.
REVOKE INSERT ON public.cyl_pipeline_run_scans FROM bloom_workflows;
GRANT SELECT ON public.cyl_pipeline_run_scans TO bloom_workflows;
GRANT INSERT (run_id, scan_id, batch_index, status)
    ON public.cyl_pipeline_run_scans TO bloom_workflows;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.cyl_pipeline_run_scans TO bloom_admin;

-- 3. Realtime publication --------------------------------------------------------

DO $$
BEGIN
  ALTER PUBLICATION supabase_realtime ADD TABLE public.cyl_pipeline_runs;
EXCEPTION WHEN duplicate_object THEN
  NULL;
END$$;

DO $$
BEGIN
  ALTER PUBLICATION supabase_realtime ADD TABLE public.cyl_pipeline_run_scans;
EXCEPTION WHEN duplicate_object THEN
  NULL;
END$$;

-- 4. bloom_workflows: dedup-preview read access on EXISTING tables --------------
-- Needed to check ALL of a scan's cyl_trait_sources rows (via cyl_scan_traits),
-- not just its most recent one. RLS is already enabled on both tables with no
-- existing policy naming bloom_workflows, so a GRANT alone would still be
-- default-denied — both a policy AND a column-scoped grant are required.

DROP POLICY IF EXISTS workflows_read_cyl_scan_traits ON public.cyl_scan_traits;
CREATE POLICY workflows_read_cyl_scan_traits ON public.cyl_scan_traits
    FOR SELECT TO bloom_workflows USING (true);

DROP POLICY IF EXISTS workflows_read_cyl_trait_sources ON public.cyl_trait_sources;
CREATE POLICY workflows_read_cyl_trait_sources ON public.cyl_trait_sources
    FOR SELECT TO bloom_workflows USING (true);

GRANT SELECT (scan_id, source_id) ON public.cyl_scan_traits TO bloom_workflows;
GRANT SELECT (id, metadata) ON public.cyl_trait_sources TO bloom_workflows;

-- 4b. bloom_workflows: wave/experiment EXISTENCE checks -------------------------
-- `cyl_scans_extended` (already granted, 20260716000000) inner-joins scan through
-- to wave/experiment, so a wave/experiment with zero scans produces zero rows
-- there — indistinguishable from a wave/experiment that does not exist at all.
-- The route needs to tell those two cases apart (200/scan_count=0 vs 404), which
-- requires an existence check directly against cyl_waves/cyl_experiments. `id`
-- only — this is purely an existence check, not a data read.

DROP POLICY IF EXISTS workflows_read_cyl_waves ON public.cyl_waves;
CREATE POLICY workflows_read_cyl_waves ON public.cyl_waves
    FOR SELECT TO bloom_workflows USING (true);

GRANT SELECT (id) ON public.cyl_waves TO bloom_workflows;

DROP POLICY IF EXISTS workflows_read_cyl_experiments ON public.cyl_experiments;
CREATE POLICY workflows_read_cyl_experiments ON public.cyl_experiments
    FOR SELECT TO bloom_workflows USING (deleted_at IS NULL);

GRANT SELECT (id) ON public.cyl_experiments TO bloom_workflows;

-- 5. pgmq dispatch queue + least-privilege enqueue function ---------------------

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pgmq.list_queues() WHERE queue_name = 'cyl_pipeline_dispatch') THEN
    PERFORM pgmq.create('cyl_pipeline_dispatch');
  END IF;
END
$$;

CREATE OR REPLACE FUNCTION public.enqueue_cyl_pipeline_batch(
    p_run_id BIGINT,
    p_batch_index INTEGER,
    p_scan_ids BIGINT[]
) RETURNS BIGINT
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public, pgmq
AS $$
DECLARE
    v_msg_id BIGINT;
BEGIN
    SELECT pgmq.send(
        'cyl_pipeline_dispatch',
        jsonb_build_object(
            'run_id', p_run_id,
            'batch_index', p_batch_index,
            'scan_ids', to_jsonb(p_scan_ids)
        )
    ) INTO v_msg_id;
    RETURN v_msg_id;
END;
$$;

REVOKE EXECUTE ON FUNCTION public.enqueue_cyl_pipeline_batch(BIGINT, INTEGER, BIGINT[])
    FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.enqueue_cyl_pipeline_batch(BIGINT, INTEGER, BIGINT[])
    TO bloom_workflows;

COMMIT;
