-- Migration: scrna_cells_genotype_and_labels
--
-- Adds one table and three columns so the map can filter cells by more than
-- cell type:
--
--   scrna_genotypes            one row per genotype in a dataset
--   scrna_cells.genotype_id    which genotype a cell belongs to
--   scrna_cells.facets         any other per-cell label, for filtering
--   scrna_clusters.source      where a cell type's label came from
--
-- `scrna_cell_arrays` returns the new columns alongside the position it
-- already returned. One query ordered by cell_number, because everything the
-- explorer fetches is paired to cells by position.

BEGIN;

-- ─── 1. Genotypes ────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS public.scrna_genotypes (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  dataset_id   BIGINT  NOT NULL REFERENCES public.scrna_datasets (id),
  name         TEXT    NOT NULL,
  -- The accession this genotype is, when it is one.
  accession_id BIGINT  REFERENCES public.arabidopsis_accessions (id),
  -- The dataset's wild type. Set by the ingest, never guessed from the name.
  is_control   BOOLEAN NOT NULL DEFAULT false,
  -- The construct a transgenic line carries.
  construct    TEXT,
  notes        TEXT,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
  -- One row per genotype per dataset, so a re-ingest lands on the same row.
  CONSTRAINT scrna_genotypes_one_per_dataset UNIQUE (dataset_id, name),
  -- Lets a cell key on (dataset_id, id) rather than id alone.
  CONSTRAINT scrna_genotypes_id_per_dataset UNIQUE (dataset_id, id),
  -- The trim set is spelled out: btrim(x) with one argument strips ordinary
  -- spaces only, and a backslash-v is the letter v to Postgres.
  CONSTRAINT scrna_genotypes_name_not_blank
    CHECK (btrim(name, E' \t\n\r\f\u000b\u00a0') <> ''),
  CONSTRAINT scrna_genotypes_construct_not_blank
    CHECK (construct IS NULL OR btrim(construct, E' \t\n\r\f\u000b\u00a0') <> ''),
  -- name is indexed, and notes is served to every viewer of the dataset.
  CONSTRAINT scrna_genotypes_lengths CHECK (
    length(name)      <= 100 AND
    length(construct) <= 200 AND
    length(notes)     <= 2000
  )
);

-- Which genotype each cell belongs to. Keyed on the dataset too, so a cell
-- cannot take a genotype from another experiment. RESTRICT: deleting a
-- genotype that still has cells is refused.
ALTER TABLE public.scrna_cells
  ADD COLUMN IF NOT EXISTS genotype_id BIGINT;
ALTER TABLE public.scrna_cells
  DROP CONSTRAINT IF EXISTS scrna_cells_genotype_fkey;
ALTER TABLE public.scrna_cells
  ADD CONSTRAINT scrna_cells_genotype_fkey
  FOREIGN KEY (dataset_id, genotype_id)
  REFERENCES public.scrna_genotypes (dataset_id, id)
  ON DELETE RESTRICT;

CREATE INDEX IF NOT EXISTS idx_scrna_cells_genotype
  ON public.scrna_cells (genotype_id);

-- ─── 2. Cell type label source ───────────────────────────────────────────────

-- Where a cell type's label came from, usually the atlas it was transferred
-- from. Free text: a person reads it, nothing filters on it.
ALTER TABLE public.scrna_clusters
  ADD COLUMN IF NOT EXISTS source TEXT;

COMMENT ON TABLE public.scrna_genotypes IS
  'The genotypes a dataset compares. Readable by anyone who can see the '
  'dataset, including anonymous visitors -- do not put anything unpublished '
  'in notes.';

COMMENT ON COLUMN public.scrna_clusters.source IS
  'Where this cell type''s label came from -- a reference atlas, a paper, or a '
  'method. Set by hand and carried across a reload; NULL until someone sets '
  'it. Shown in the cluster sidebar.';

-- ─── 3. Per-cell labels ──────────────────────────────────────────────────────

-- Any label the ingest was told to load, as an object of short strings, so
-- the map can show or hide cells by it.
ALTER TABLE public.scrna_cells
  ADD COLUMN IF NOT EXISTS facets JSONB DEFAULT NULL;

-- True when facets is an object of non-empty strings, the only shape the
-- explorer can draw as toggles. A function because walking the object needs a
-- subquery, which a CHECK cannot hold.
CREATE OR REPLACE FUNCTION public.scrna_facets_are_flat_text(facets JSONB)
RETURNS BOOLEAN
LANGUAGE sql
IMMUTABLE
PARALLEL SAFE
AS $fn$
  SELECT facets IS NULL
     OR (
       jsonb_typeof(facets) = 'object'
       -- The whole object, since per-field limits cannot see 32 of them
       -- added up. Ten annotation columns come to about 400 characters.
       AND length(facets::text) <= 1024
       AND (SELECT count(*) FROM jsonb_object_keys(facets)) <= 32
       AND NOT EXISTS (
         SELECT 1 FROM jsonb_each(facets) AS f(key, value)
         WHERE jsonb_typeof(f.value) <> 'string'
            OR btrim(f.key, E' \t\n\r\f\u000b\u00a0') = ''
            OR btrim(f.value #>> '{}', E' \t\n\r\f\u000b\u00a0') = ''
            OR length(f.key) > 64
            OR length(f.value #>> '{}') > 200
       )
     );
$fn$;

-- A CHECK runs with the writer's privileges, so this grant is load-bearing:
-- without it every write to scrna_cells fails on a permission error.
REVOKE EXECUTE ON FUNCTION public.scrna_facets_are_flat_text(JSONB) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.scrna_facets_are_flat_text(JSONB)
  TO authenticated, bloom_writer, bloom_admin, service_role, postgres;

ALTER TABLE public.scrna_cells
  DROP CONSTRAINT IF EXISTS scrna_cells_facets_are_flat_text;
ALTER TABLE public.scrna_cells
  ADD CONSTRAINT scrna_cells_facets_are_flat_text
  CHECK (public.scrna_facets_are_flat_text(facets)) NOT VALID;

-- The cell query returns this to anonymous visitors. Real values are sample
-- names of at most 6 characters.
ALTER TABLE public.scrna_cells
  DROP CONSTRAINT IF EXISTS scrna_cells_replicate_length;
ALTER TABLE public.scrna_cells
  ADD CONSTRAINT scrna_cells_replicate_length
  CHECK (length(replicate) <= 100) NOT VALID;

-- ─── 4. The cell query ───────────────────────────────────────────────────────

-- Dropped first: the return type changes, and CREATE OR REPLACE cannot.
DROP FUNCTION IF EXISTS public.scrna_cell_arrays(BIGINT);

CREATE FUNCTION public.scrna_cell_arrays(
  ds_id BIGINT
)
RETURNS TABLE (
  x               REAL,
  y               REAL,
  cluster_ordinal SMALLINT,
  genotype        TEXT,
  replicate       TEXT,
  facets          JSONB
)
LANGUAGE sql
STABLE
SECURITY INVOKER
AS $$
  SELECT
    c.x::REAL,
    c.y::REAL,
    COALESCE(cl.ordinal, 255::SMALLINT) AS cluster_ordinal,
    g.name AS genotype,
    c.replicate,
    c.facets
  FROM public.scrna_cells c
  LEFT JOIN public.scrna_clusters cl
    ON cl.dataset_id = c.dataset_id
   AND cl.cluster_id = c.cluster_id
  LEFT JOIN public.scrna_genotypes g
    ON g.id = c.genotype_id
   AND g.dataset_id = c.dataset_id
  WHERE c.dataset_id = ds_id
  ORDER BY c.cell_number ASC;
$$;

-- CREATE FUNCTION grants EXECUTE to PUBLIC; revoked so the list below is the
-- one that decides.
REVOKE EXECUTE ON FUNCTION public.scrna_cell_arrays(BIGINT) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.scrna_cell_arrays(BIGINT)
  TO anon, authenticated, bloom_user, bloom_admin, bloom_agent;

-- ─── 5. Read access ──────────────────────────────────────────────────────────

ALTER TABLE public.scrna_genotypes ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Anon users can select scrna_genotypes" ON public.scrna_genotypes;
CREATE POLICY "Anon users can select scrna_genotypes"
  ON public.scrna_genotypes AS permissive FOR SELECT TO anon USING (true);

DROP POLICY IF EXISTS "Authenticated users can select scrna_genotypes" ON public.scrna_genotypes;
CREATE POLICY "Authenticated users can select scrna_genotypes"
  ON public.scrna_genotypes AS permissive FOR SELECT TO authenticated USING (true);

DROP POLICY IF EXISTS "admin_all_scrna_genotypes" ON public.scrna_genotypes;
CREATE POLICY "admin_all_scrna_genotypes"
  ON public.scrna_genotypes AS permissive FOR ALL TO bloom_admin
  USING (true) WITH CHECK (true);

-- bloom_writer is the ingest role: it creates the genotypes cells point at.
DROP POLICY IF EXISTS writer_select_scrna_genotypes ON public.scrna_genotypes;
CREATE POLICY writer_select_scrna_genotypes
  ON public.scrna_genotypes FOR SELECT TO bloom_writer USING (true);

DROP POLICY IF EXISTS writer_insert_scrna_genotypes ON public.scrna_genotypes;
CREATE POLICY writer_insert_scrna_genotypes
  ON public.scrna_genotypes FOR INSERT TO bloom_writer WITH CHECK (true);

DROP POLICY IF EXISTS writer_update_scrna_genotypes ON public.scrna_genotypes;
CREATE POLICY writer_update_scrna_genotypes
  ON public.scrna_genotypes FOR UPDATE TO bloom_writer
  USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "user_read_scrna_genotypes" ON public.scrna_genotypes;
CREATE POLICY "user_read_scrna_genotypes"
  ON public.scrna_genotypes AS permissive FOR SELECT TO bloom_user USING (true);

DROP POLICY IF EXISTS "agent_read_scrna_genotypes" ON public.scrna_genotypes;
CREATE POLICY "agent_read_scrna_genotypes"
  ON public.scrna_genotypes AS permissive FOR SELECT TO bloom_agent USING (true);

COMMIT;
