-- gravi_scan_metadata_accession: per-plate accession metadata captured by the
-- GraviScan desktop. One row per (accession, plate_id, wave_number) tuple.
-- accession_name is denormalised alongside accession_id to make later lookups
-- by string name fast without a join (and to allow accession_id to be NULL if
-- the accession isn't yet known).
--
-- UNIQUE is enforced via an expression index (idx_gravi_scan_metadata_accession_unique)
-- rather than a column constraint because wave_number is nullable and Postgres
-- treats NULL = NULL as unknown — COALESCE(wave_number, -1) gives a NULL-safe
-- key so two rows with the same (accession_id, plate_id) and NULL wave_number
-- still conflict.

CREATE TABLE gravi_scan_metadata_accession (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    accession_id BIGINT REFERENCES accessions(id),
    plate_id TEXT NOT NULL,
    accession_name TEXT NOT NULL,
    wave_number INT,
    transplant_date TIMESTAMPTZ,
    custom_note TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX idx_gravi_scan_metadata_accession_unique
    ON gravi_scan_metadata_accession (accession_id, plate_id, COALESCE(wave_number, -1));

ALTER TABLE gravi_scan_metadata_accession ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS admin_all_gravi_scan_metadata_accession ON public.gravi_scan_metadata_accession;
CREATE POLICY admin_all_gravi_scan_metadata_accession ON public.gravi_scan_metadata_accession
    FOR ALL TO bloom_admin USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS agent_read_gravi_scan_metadata_accession ON public.gravi_scan_metadata_accession;
CREATE POLICY agent_read_gravi_scan_metadata_accession ON public.gravi_scan_metadata_accession
    FOR SELECT TO bloom_agent USING (true);

DROP POLICY IF EXISTS user_read_gravi_scan_metadata_accession ON public.gravi_scan_metadata_accession;
CREATE POLICY user_read_gravi_scan_metadata_accession ON public.gravi_scan_metadata_accession
    FOR SELECT TO bloom_user USING (true);

DROP POLICY IF EXISTS user_insert_gravi_scan_metadata_accession ON public.gravi_scan_metadata_accession;
CREATE POLICY user_insert_gravi_scan_metadata_accession ON public.gravi_scan_metadata_accession
    FOR INSERT TO bloom_user WITH CHECK (true);

DROP POLICY IF EXISTS user_update_gravi_scan_metadata_accession ON public.gravi_scan_metadata_accession;
CREATE POLICY user_update_gravi_scan_metadata_accession ON public.gravi_scan_metadata_accession
    FOR UPDATE TO bloom_user USING (true);
