"""Everything that names a plate's video object must name the same one.

A plate's video lives at
`graviscan-videos/{experiment_id}/wave-{wave}/{plate_id}.mp4`. Three places in
this repo build that key and none can import the others, so they are pinned
together here: the web app (TypeScript), services/workflows (Python), and
`scripts/render_plate_videos.py`, which already wrote objects under this layout
for the experiments whose videos were generated by hand.

Getting this wrong is silent every way: a web app looking in the wrong place
renders "no time-lapse video available" for a plate that has one, an encoder
writing to the wrong key reports success while producing something nothing
reads, and either one diverging from the script orphans the videos that already
exist.

The `plate_id` whitelist is pinned as a literal string rather than by behaviour.
A table of cases only proves two rules agree on the cases someone thought of;
comparing the pattern itself proves they are the same rule.
"""

from __future__ import annotations

import re
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
WEB_PATH_MODULE = REPO_ROOT / "web" / "lib" / "supabase" / "plate-video-path.ts"
WORKFLOWS_PATH_MODULE = (
    REPO_ROOT / "services" / "workflows" / "plate_video_path.py"
)
RENDER_SCRIPT = REPO_ROOT / "scripts" / "render_plate_videos.py"


def _web() -> str:
    return WEB_PATH_MODULE.read_text(encoding="utf-8")


def _workflows() -> str:
    return WORKFLOWS_PATH_MODULE.read_text(encoding="utf-8")


def _script() -> str:
    return RENDER_SCRIPT.read_text(encoding="utf-8")


def test_videos_bucket_agrees():
    web = re.search(r'GRAVISCAN_VIDEOS_BUCKET\s*=\s*"([^"]+)"', _web())
    assert web, f"no GRAVISCAN_VIDEOS_BUCKET in {WEB_PATH_MODULE.name}"

    # The service allows an env override; the default is what must match.
    service = re.search(
        r'VIDEOS_BUCKET\s*=\s*os\.environ\.get\(\s*"[^"]+"\s*,\s*"([^"]+)"\s*\)',
        _workflows(),
    )
    assert service, f"no VIDEOS_BUCKET default in {WORKFLOWS_PATH_MODULE.name}"

    script = re.search(r'target_bucket:\s*str\s*=\s*"([^"]+)"', _script())
    assert script, f"no target_bucket default in {RENDER_SCRIPT.name}"

    assert web.group(1) == service.group(1) == script.group(1), (
        f"videos bucket mismatch: web {web.group(1)!r}, "
        f"workflows {service.group(1)!r}, script {script.group(1)!r}"
    )


def test_images_bucket_agrees():
    """The encoder reads frames from the same bucket the script does."""
    web = re.search(r'GRAVISCAN_IMAGES_BUCKET\s*=\s*"([^"]+)"', _web())
    assert web, f"no GRAVISCAN_IMAGES_BUCKET in {WEB_PATH_MODULE.name}"

    service = re.search(
        r'IMAGES_BUCKET\s*=\s*os\.environ\.get\(\s*"[^"]+"\s*,\s*"([^"]+)"\s*\)',
        _workflows(),
    )
    assert service, f"no IMAGES_BUCKET default in {WORKFLOWS_PATH_MODULE.name}"

    script = re.search(r'source_bucket:\s*str\s*=\s*"([^"]+)"', _script())
    assert script, f"no source_bucket default in {RENDER_SCRIPT.name}"

    assert web.group(1) == service.group(1) == script.group(1), (
        f"images bucket mismatch: web {web.group(1)!r}, "
        f"workflows {service.group(1)!r}, script {script.group(1)!r}"
    )


def test_plate_id_pattern_is_byte_identical():
    """Two regexes that merely behave alike on the cases someone thought of are
    not the same rule. A plate id accepted by one end and refused by the other
    is a plate that can be rendered but never found, or the reverse."""
    web = re.search(r'PLATE_ID_PATTERN\s*=\s*"([^"]+)"', _web())
    assert web, f"no PLATE_ID_PATTERN in {WEB_PATH_MODULE.name}"

    service = re.search(r'PLATE_ID_PATTERN\s*=\s*"([^"]+)"', _workflows())
    assert service, f"no PLATE_ID_PATTERN in {WORKFLOWS_PATH_MODULE.name}"

    assert web.group(1) == service.group(1), (
        f"plate id pattern mismatch:\n  web:       {web.group(1)!r}\n"
        f"  workflows: {service.group(1)!r}"
    )


def test_wave_segment_agrees():
    """Wave is a path segment because plate ids repeat across waves; a plate
    rendered under the wrong segment overwrites another wave's video."""
    web_named = re.search(r'return\s+`wave-\$\{waveNumber\}`', _web())
    assert web_named, f"{WEB_PATH_MODULE.name} does not build `wave-{{n}}`"

    service_named = re.search(r'return\s+f"wave-\{wave_number\}"', _workflows())
    assert service_named, f"{WORKFLOWS_PATH_MODULE.name} does not build `wave-{{n}}`"

    script_named = re.search(r'f"wave-\{job\.wave_number\}"', _script())
    assert script_named, f"{RENDER_SCRIPT.name} does not build `wave-{{n}}`"

    web_none = re.search(r'return\s+"(wave-[a-z]+)"', _web())
    service_none = re.search(r'return\s+"(wave-[a-z]+)"', _workflows())
    script_none = re.search(r'else\s+"(wave-[a-z]+)"', _script())
    assert web_none and service_none and script_none, (
        "each side must name the no-wave segment as a literal"
    )

    assert web_none.group(1) == service_none.group(1) == script_none.group(1), (
        f"no-wave segment mismatch: web {web_none.group(1)!r}, "
        f"workflows {service_none.group(1)!r}, script {script_none.group(1)!r}"
    )


def test_key_shape_agrees():
    """The three parts in the same order, with `.mp4` on the end. A key built
    from agreeing constants can still diverge if the parts are assembled
    differently."""
    web = re.search(
        r'return\s+`\$\{experimentId\}/\$\{wave\}/\$\{plateId\}\.mp4`', _web()
    )
    assert web, f"{WEB_PATH_MODULE.name} does not build {{exp}}/{{wave}}/{{plate}}.mp4"

    service = re.search(
        r'return\s+f"\{experiment_id\}/\{wave\}/\{plate_id\}\.mp4"', _workflows()
    )
    assert service, (
        f"{WORKFLOWS_PATH_MODULE.name} does not build {{exp}}/{{wave}}/{{plate}}.mp4"
    )

    script = re.search(
        r'f"\{job\.experiment_id\}/\{wave_seg\}/\{job\.plate_id\}\.mp4"', _script()
    )
    assert script, (
        f"{RENDER_SCRIPT.name} does not build {{exp}}/{{wave}}/{{plate}}.mp4 — "
        "objects already exist under that layout"
    )
